### ISSUE TITLE
More than one not active chat can't be opened using shortcut

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#108]
1. Open not active chat
2. Press home button
3. Open another not active chat using shortcut

**Comment by andrewnenakhov** [comment]
Yes. Xabber should not behave this way. When shortcutting to not active chat, other 'intent' to start chat should be ended.

**Comment by grigoryfedorov** [comment]
Fixed in d47ff0d3aed35b57f6a0d1d7643f5f6581b4a1d4
