### ISSUE TITLE
Connection fails when "Store password" option is enabled

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#113]
1. Go offline
2. Disable "Store password" option
3. Go online
4. Wait for "Password required" notification
5. Don't touch this notification
6. Enable "Store password" option
7. Open notification
8. Press "OK" button
9. Go offline
10. Go online
11. Unable to connect, there is no notification

**Comment by andrewnenakhov** [comment]
This bug is now somewhat different: if account is offline and "store password" option is disabled, we should clear password and be unable to reconnect without providing passwords. Currently Xabber goes online without problems, it's wrong.

**Comment by Str4tocaster** [comment]
Fixed with https://github.com/redsolution/xabber-android/commit/ace77067612a8905b841cc590319949536ab684d and https://github.com/redsolution/xabber-android/commit/e786890605c7b6cf3ac9f7bc6069492aa303a3bf
