### ISSUE TITLE
Don't close previously open chat

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#122]
1. Open chat
2. Send message
3. Press home button
4. Share something with Xabber
5. Select the same chat
6. Press "Chat list"
7. Select the same chat
8. Close chat
9. Open Xabber from the home screen
10. Contact list will be shown

**Comment by andrewnenakhov** [comment]
Could not quite understand the issue. @grigoryfedorov please, check it out for new version.

**Comment by grigoryfedorov** [comment]
Oh, don't actual, I think.
