### ISSUE TITLE
[FR] SMS integration / unified messaging interface

### ISSUE THREAD

**Issue by ildar** [redsolution/xabber-android#137]
Is it possible to make Xabber work with XMPP _and_ SMS uniformly? That is (for one peer) having XMPP messages and SMS in one history/one window + allowing the option to send messages through XMPP or SMS and so on.

That is how messaging application works on Maemo OS.
Add MMS here and many things on to advance.

**Comment by jcrben** [comment]
This would allow a gradual bridge to XMPP replacing SMS over time, greatly increasing the possibility of growth.
