### ISSUE TITLE
Subsequent reconnection to the room on authorization error

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#142]
1. Turn on WiFi.
2. Join the room.
3. Immediately turn off WiFi.
4. Xabber joins the room using GPRS.
5. Conference server can block subsequent authorization.

Xabber should wait several seconds before reconnection.

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
