### ISSUE TITLE
Platform 9 is obsolete

### ISSUE THREAD

**Issue by Natureshadow** [redsolution/xabber-android#147]
Android Platform version 9 is obsolete and is not available through the SDK manager anymore. I think the project can easily be ported to default to API level 10, although the v9 resources cause some issues:

/home/nik/projs/xabber-android/res/values-v9/styles.xml:17: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.StatusBar.EventContent.Title'.
/home/nik/projs/xabber-android/res/values-v9/styles.xml:16: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.StatusBar.EventContent'.

**Comment by alanthehat** [comment]
A search of "gingerbread phone" on Amazon.com produces quite a few results that only list as Android 2.3. Is it reasonable to punish people for buying a device that's currently for sale? 
I feel that it's a good thing that the developers want to build for all available devices.

**Comment by grigoryfedorov** [comment]
New Xabber supports Android 4+ only
