### ISSUE TITLE
some messages in MUC not visible

### ISSUE THREAD

**Issue by snai** [redsolution/xabber-android#150]
In a MUC conference I often have the issue, that messages from certain users are not received / displayed.

On xabber I see this:
User A: ...
User A: ...
User A: ...

On gajim (connected with the same account) I see this:
User A: ...
User B: ...
User A: ...
User B: ...
User A: ...

It is not always the same User which I don't get the message from. Sometimes I don't see the messages from my account, written on gajim in xabber.

Furthermore _sometimes_, a `authentication error` is displayed in the notification area.

Let me know if you need further information, and how I can help to track down the bug.

**Comment by moshpirit** [comment]
I'm seeing that the error it's already detected: lines 228 to 230,, then, any idea about why isn't it implemented yet?
Please, @grigoryfedorov, could you check it out or at least tell us why this is not the solution? 
Thanks, @ghost!

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
