### ISSUE TITLE
Ping interval setting and ping wakelock

### ISSUE THREAD

**Issue by HerrCypher** [redsolution/xabber-android#152]
Hello!

Please add an option in the settings which lets the user decide when Xabber should ping (xmpp-ping) the server.

My mobile provider keeps idle connections for about 10 minutes, so I would like to save energy by setting the ping interval of the idling Xabber connection to about 9 minutes.
The hardcoded default is 1 minute, I think. //edit1: Actually 30 seconds.
An option in seconds instead of minutes would be even better, so I can use 9,5 minutes (570 second), which is even more efficient.

Thanks in advance! :)

//edit1:
Even worse, the default seems to be 30. It was just 60 for me because the phone was in deep-sleep, which sends the packet about 30 seconds later.

//edit2:
Just for fun I tested the deepsleep-delay from edit1:
Assuming a ping in Xabber should happen every 30 second after the last packet, the average delay for a xmpp-ping was about 30 to 35 seconds, with a maximum of 60 seconds, and a minimum of 0 when I had luck.
So the total time between two pings was 90 seconds in the worst case.

I also discovered, the opensource mail client k9Mail can send packets without delay even in deepsleep. 
Perhaps this helps to understand how: https://github.com/k9mail/k-9/blob/master/src/com/fsck/k9/service/SleepService.java
A reliable ping for Xabber would be much better than just setting it to 30secs and hoping the best.

//edit3:
But wait, there's more!
In some cases the delay increases to over 90, so the time between two pings is over 120. In that case the client will reconnect to the XMPP server. It doesn't even matter if the server answers the ping in time or not.
I always wondered why I keep getting login-messages in Pidgin about 4 times per hour from my Xabber-using contacts. Usually I blamed failures in the handover-process of the celltowers, but now I found the true answer: Xabber and it's inability to handle pings and timeouts. ;)

**Comment by andrewnenakhov** [comment]
Such small interval is not enough.
