### ISSUE TITLE
"You have new messages" icon and "no messages" icon hardly differ

### ISSUE THREAD

**Issue by LavirtheWhiolet** [redsolution/xabber-android#155]
"You have new messages" icon and "no messages" icon look almost the same on HD devices. It is suggested to change the icon's color or to increase the envelope's size or just to replace the "you have new messages" icon with one big envelope.

Flashing icon, IMHO, is not a good idea because it requires more time for experienced user  to determine the icon's state – "flashing" or "steady".

**Comment by grigoryfedorov** [comment]
Completely new icons used.
