### ISSUE TITLE
Allow to receive notifications only when the user is "highlighted" in conference

### ISSUE THREAD

**Issue by LavirtheWhiolet** [redsolution/xabber-android#156]
There is a setting which allows the user to receive notifications for any message in conference and to not receive any conference-related notifications at all. The user should be able to receive notifications only when his nickname is mentioned in the conference (so called "highlighting").

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.

**Comment by licaon-kter** [comment]
@andrewnenakhov ok, the new protocol, but the UI... will it allow the user to be notified "only on mention" then in 2020?

**Comment by andrewnenakhov** [comment]
@licaon-kter it will. I'll work mostly like telegram group chats.
