### ISSUE TITLE
Remove implicitly granted permission READ_CALL_LOG

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#160]
http://developer.android.com/reference/android/Manifest.permission.html#READ_CALL_LOG

**Comment by grigoryfedorov** [comment]
> Note: If your app uses the READ_CONTACTS permission and both your minSdkVersion and targetSdkVersion values are set to 15 or lower, the system implicitly grants your app this permission. If you don't need this permission, be sure your targetSdkVersion is 16 or higher.

Target SDK is 22 for now.
