### ISSUE TITLE
Don't pause music when notification is emitted

### ISSUE THREAD

**Issue by alexs77** [redsolution/xabber-android#161]
When I get a notification about a new chat message, music in various applications (TuneIn Radio, Amazon MP3, Spotify, …) is paused. When notification sound is done playing, music starts again - mostly…

But sometimes, when many notifications arrive in a pretty short time (unsure - in under 1 or 2 seconds?), music stays paused and I have to go to the app and unpause it.

Is it possible that you emit the notification sound in Xabber VIP in such a way, that other music apps do NOT pause?

**Comment by alanthehat** [comment]
Similar for me with Star N9599T, MediaTek MT6589T firmware, stock but rooted. 
It feels like an OS issue, but perhaps specifying which audio channel to use would work around it?
