### ISSUE TITLE
Contact's presence not always updated

### ISSUE THREAD

**Issue by ohmer1** [redsolution/xabber-android#163]
When I open Xabber to read my roster, I often see offline contacts still marked as online (they appears offline from my desktop client).  I can even disconnect from the xmpp server and I see all my contacts that was online to be still online!  When I connect it back, my roster is finally updated.

**Comment by andrewnenakhov** [comment]
Looks like an unconfirmed bug. We'll keep it for now.

**Comment by andrewnenakhov** [comment]
Things like this could happen it presences where not delivered properly. Haven't seen such issues on android in a while.
