### ISSUE TITLE
Xabber should change status to away and lower priority when screen saver is on

### ISSUE THREAD

**Issue by ohmer1** [redsolution/xabber-android#164]
I'm using the screen saver feature when my phone is in charge.  This make my phone to display the clock in "night mode". 

Xabber should change my status to away and change my xmpp priority when the screen saver is switched on like it does when the screen is locked.

Because of that, Xabber keep my status to available and high priority when I'm sleeping.

**Comment by andrewnenakhov** [comment]
Actually that's not how message delivery should work. However there is option to change priority based on status in connection settings and changing away status on inactivity time. That should do for described situations.
