### ISSUE TITLE
Please add Bonjour Chat as additional account protocol

### ISSUE THREAD

**Issue by DanScharon** [redsolution/xabber-android#172]
As xabber not only supports XMPP as account protocol, please add bonjour chat (also known as avahi or zeroconf) as additional account option.

**Comment by andrewnenakhov** [comment]
not in plans any more

**Comment by damascene** [comment]
One very useful case of Bonjour is being able to share files and text with desktop devices easily. There are only chatsecure that can do that but it only have iOS version on their website.
