### ISSUE TITLE
Build failure, setForeground

### ISSUE THREAD

**Issue by kenrestivo** [redsolution/xabber-android#202]
I'm sorry to bother you guys with build failures-- probably one of the main reasons you were reluctant to open source this for so long-- but here's one maybe someone else has seen and overcome:

```
    [javac] Compiling 856 source files to droid/src/xabber-android/bin/classes
    [javac] /home/localkens/embed/droid/src/xabber-android/src/com/xabber/android/service/XabberService.java:114: error: cannot find symbol
    [javac]             setForeground(true);
    [javac]             ^
    [javac]   symbol:   method setForeground(boolean)
    [javac]   location: class XabberService
    [javac] droid/src/xabber-android/src/com/xabber/android/service/XabberService.java:141: error: cannot find symbol
    [javac]             setForeground(false);
    [javac]             ^
    [javac]   symbol:   method setForeground(boolean)
    [javac]   location: class XabberService
    [javac] droid/src/xabber-android/src/com/xabber/android/utils/DummyCursor.java:25: error: DummyCursor is not abstract and does not override abstract method getType(int) in Cursor
    [javac] public class DummyCursor implements Cursor {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
```

I'm building for API 9, all stock per latest git head. AFIACT the Cursor class was added in API 1

I'm confused because my Google-fu tells me that this setForeground is a no-op and should have been replaced ages ago, in Android 2.0!  http://android-developers.blogspot.com/2010/02/service-api-changes-starting-with.html

So I'm confused why it's even trying to execute the startForeground path at all. This is API 9 (and yes I've done "android update project --path . --target 9")

Thanks again for open-sourcing it!

**Comment by zhongwcool** [comment]
Supporting for android 1.5/1.6 will drop most excellent ui effect which introduced by API level 17 and later.
