### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sevenkel** [redsolution/xabber-android#203]
hey there,
i have some suggestions
Plz wait until all 4 images are loaded.
1st
![1](https://f.cloud.github.com/assets/4427317/501153/225199c2-bc8f-11e2-9ab0-1179a458e87f.png)

2nd
![2](https://f.cloud.github.com/assets/4427317/501158/5ea9fdf6-bc8f-11e2-86ed-e37d184a5e40.png)

3rd

![3](https://f.cloud.github.com/assets/4427317/501164/82809c8a-bc8f-11e2-9504-abec77db12b6.png) 
![4](https://f.cloud.github.com/assets/4427317/501166/998e6ae2-bc8f-11e2-9566-2c919de4571c.png)

with this features i will never ever use bombusmod again! your the best xabber!

**Comment by andrewnenakhov** [comment]
Please specify your request in more understandable terms with full text description (and possibly mockups of interface you wantto implement)
