### ISSUE TITLE
Reduce Power consumption while running in background by disabling presence stanzas

### ISSUE THREAD

**Issue by balu-** [redsolution/xabber-android#205]
Please impment a method to disable presence stanzas on serverside while beeing in background ( XEP-0016 / XEP-0191 ). 
This could save a lot of battery by allowing the device to sleep and not waking up by all this presence notifications. 
See also http://www.deepdarc.com/2008/02/14/mobile-xmpp/

**Comment by andrewnenakhov** [comment]
no, we have different plan to save power
