### ISSUE TITLE
text in input-field ends up in the wrong chat (while having multiple chats active/open)

### ISSUE THREAD

**Issue by merge** [redsolution/xabber-android#208]
I haven't tested enough to say how to reproduce it, but have multiple chats open and have text in the textfield, maybe don't send it instantly, recieve messages and so on. Somehow text ended up in the _wrong_ chat! I'll provide more info as I have time to, but I thought it would be worth pointing out. I can't be the only one. I use 0.9.29a right now.

**Comment by andrewnenakhov** [comment]
This bug happened rarely in old versions of Android, but we were unable to reliably reproduce it.

**Comment by merge** [comment]
I don't use xabber anymore and since nobody else picked this up, let's close it.
