### ISSUE TITLE
Support for XEP-0313

### ISSUE THREAD

**Issue by bjo81** [redsolution/xabber-android#215]
Unfortunately, prosody doesn't support XEP-0136 any more. It will be superseeded by XEP-0313. Using the same history on desktopclients and on smartphones like it was possible with XEP-0136 would be nice.
http://xmpp.org/extensions/xep-0313.html

**Comment by moshpirit** [comment]
Totally agree with you :+1: 
I think I remember that Conversations also solved a Carbons error by this XEP.

**Comment by moshpirit** [comment]
Seriously, I'll donate for this XEP and for jingle file transfer.

**Comment by jerdog** [comment]
:+1:

**Comment by Shuro** [comment]
:+1:

**Comment by scuba323** [comment]
I have Openfire and it has XEP-0313 support. Sadly in 2.0, "Message Archive Management" is grayed out. Telling me it hasn't been determined if it's supported. Not sure if it should be a new issue? But it's still on topic :smile:

**Comment by zulguamusang** [comment]
+1

**Comment by andrewnenakhov** [comment]
XEP-0313 support is implemented in Xabber.2.* - at least it works for us on such servers as Jabber.at, XMPP.ru and of course Xabber.com 

@scuba323 if it doesn't work for you post a separate bug requests and email us, we'll try to look at what's going on with your server.
