### ISSUE TITLE
Android xmpp MUC setting default configuration

### ISSUE THREAD

**Issue by getchanu** [redsolution/xabber-android#216]
Am using the Xabber open source project and am able to create a new group, But it always says: This room is locked from entry until configuration is confirmed. I tried to set a default configuration but it throws me exception: 401 not authorized. Whats exactly the problem.

final MultiUserChat multiUserChat;
        try {
            multiUserChat = new MultiUserChat(xmppConnection, room);
            // Send an empty room configuration form which indicates that we want
            // an instant room
            try {
                multiUserChat.sendConfigurationForm(new Form(Form.TYPE_SUBMIT));
            } catch (XMPPException e) {
                e.printStackTrace();
            }

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
