### ISSUE TITLE
Enhancement: Magic “Offline” contact group

### ISSUE THREAD

**Issue by Aeyoun** [redsolution/xabber-android#218]
I want quick access to all my offline contacts. But I do not want to see them all the time. Other clients solve this by having a group called “Offline”. I can leave this group collapsed and still have quick access to it.

Thanks for considering. :)

**Comment by andrewnenakhov** [comment]
No, we do not plan to have 'offline' group in interface. Such interface decisions (group with offline contacts) were one of the reasons that inspired us to make a new XMPP chat app.
