### ISSUE TITLE
Enhancement: Display Google Hangouts contacts as offline instead of away

### ISSUE THREAD

**Issue by Mrrow** [redsolution/xabber-android#219]
A contact who uses the app Hangouts (replaces Talk) is always shown as "away" but he ends up getting my messages via Gmail or Gmail chat because the Hangouts app doesn't handle them. So maybe it would be wise to display such users as offline as long as they are not connected via another real xmpp resource.

The Hangouts app creates 1-5 resources named MessagingA[a-z0-9]{8}, priority 0, client "Google Talk User Account", type "registered".

**Comment by andrewnenakhov** [comment]
Hangouts have very little compatibility left with XMPP. Perhaps problem should be solved completely by google disabling federated capabilities at all.
