### ISSUE TITLE
PUSH-Notification: Cooperate with server-developers instead of storing the credentials

### ISSUE THREAD

**Issue by robert862** [redsolution/xabber-android#222]
In the FAQ you say, that you are not using PUSH on Android because you would need the password of the user on the pushing server. But what if you would cooperate with open source xmpp/Jabber-server-software, so that the jabber-server itself would send the PUSH to Xabber?

**Comment by andrewnenakhov** [comment]
Problem with push (GCM) is much more complex than stated here.
