### ISSUE TITLE
Display Resources

### ISSUE THREAD

**Issue by kevincox** [redsolution/xabber-android#226]
It would be nice to be able to view which resources contacts have online and send messages  to a specific resource.

It is especially useful for sending messages between your resources to share text or links between your phone and computer.  This will become even more useful after file sharing is implemented.  My current workaround is to start a chat on  my desktop and reply to that message with what I  want  to send.

**Comment by neoretix** [comment]
+1
I really need this! I often can't reply to customers from my mobile because of misconfiguration in customer's status priorities.
Please add this feature and I will be so much grateful to you!! It will be a good reason to donate.
