### ISSUE TITLE
Short keepalive drains battery

### ISSUE THREAD

**Issue by rkralovic** [redsolution/xabber-android#227]
Hello,

In my experience xabber heavily drains my phone battery. A bit of investigation suggests that a big culprit here is a very short keepalive timeout (30s) for xmpp connections. Another side effect of this is a big data consumption (about 2MB / day with 3 jabber accounts, not used at all).

Im currently testing increasing values of keepAliveInterval and keepAliveResponse in res/raw/smack_config.xml to 1800s. So far, my battery drain seems to be normal again.

Would you mind increasing those values or make them configurable?

**Comment by andrewnenakhov** [comment]
@horazont stream management has some flaws in design. Better than nothing, but not too good for proper message delivery control. Anyway, current Xabber battery usage is very modest, so I close this issue
