### ISSUE TITLE
Cannot access menu on HTC 4g LTE

### ISSUE THREAD

**Issue by tylerjw** [redsolution/xabber-android#229]
The HTC 4g LTE does not have a hardware menu button and as a result I cannot access the menu.  Is there a workaround?  Are you planning on adding a menu button to the UI for phones without a hardware menu button?

Thank you, unlike google's new worthless hangout messenger I get messages when they are sent with this app.  Google's new hangout has frustrated me to no end and I like how simple and effective your chat client is.

I saw on your blog post that this is something you are planning to work on.  I'll be looking forward to the update.

**Comment by andrewnenakhov** [comment]
New version should contain full appbar support, no menu button necessary since it's deprecated by Google.

**Comment by gjedeer** [comment]
Which version is it going to be? I'm using 0.9.30f on HTC Desire 500 without hardware menu button and the menu is still inaccessible. I've seen that Xabber shows the "..." soft button on the bottom on other phones without  menu button, but not on this one.

**Comment by grigoryfedorov** [comment]
@gjedeer try to touch and hold "recent apps" button (or may be other one) to get app menu.
New version of Xabber with new style menu is in development. You can get unstable builds from F-droid https://f-droid.org/repository/browse/?fdfilter=xabber&fdid=com.xabber.androiddev
