### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by tbeitter** [redsolution/xabber-android#23]
If there would be a way to send files via xmpp, and to see them in-chat, we could push whatsapp to the trash bin.

XEP-0096 - http://xmpp.org/extensions/xep-0096.html

**Comment by robert-scheck** [comment]
+1 for file transfer support

**Comment by sbrl** [comment]
We also have SOCKS5 proxies. Both prosody (XMPP server) and pidgin (XMPP client) supports it natively. Perhaps Xabber could too?

**Comment by esalazioneHg** [comment]
+1 for file transfer, the last "big" feature missing in xabber imho

**Comment by alkino** [comment]
Which way?
Old: http://www.xmpp.org/extensions/xep-0096.html
New: http://xmpp.org/extensions/xep-0234.html

In the new way you need UPnP or meeting point if you don't use IBB. You
shouldn't use IBB it's really slow...
Le 24 juil. 2015 01:38, "esalazioneHg" <notifications@github.com> a écrit :

> +1 for file transfer, the last "big" feature missing in xabber imho
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redsolution/xabber-android/issues/23#issuecomment-124269567>
> .
>

-- 




*This email and any attachment thereto are confidential and intended solely 
for the use of the individual or entity to whom they are addressed.If you 
are not the intended recipient, please be advised that disclosing, copying, 
distributing or taking any action in reliance on the contents of this email 
is strictly prohibited. In such case, please immediately advise the sender, 
and delete all copies and attachment from your system.This email shall not 
be construed and is not tantamount to an offer, an acceptance of offer, or 
an agreement by Aldebaran Robotics on any discussion or contractual 
document whatsoever. No employee or agent is authorized to represent or 
bind Aldebaran Robotics to third parties by email, or act on behalf of 
Aldebaran Robotics by email, without express written confirmation by 
Aldebaran Robotics’ duly authorized representatives.*
------------------------------

*Ce message électronique et éventuelles pièces jointes sont confidentiels, 
et exclusivement destinés à la personne ou l'entité à qui ils sont 
adressés.*

*Si vous n'êtes pas le destinataire visé, vous êtes prié de ne pas 
divulguer, copier, distribuer ou prendre toute décision sur la foi de ce 
message électronique. Merci d'en aviser immédiatement l'expéditeur et de 
supprimer toutes les copies et éventuelles pièces jointes de votre système.*

*Ce message électronique n'équivaut pas à une offre, à une acceptation 
d’offre, ou à un accord d'Aldebaran Robotics sur toute discussion ou 
document contractuel quel qu’il soit, et ne peut être interprété comme tel. 
Aucun employé ou agent d’Aldebaran Robotics n'est autorisé à représenter ou 
à engager la société par email, ou à agir au nom et pour le compte de la 
société par email, sans qu’une confirmation écrite soit donnée par le 
représentant légal d’Aldebaran Robotics ou par toute autre personne ayant 
reçu délégation de pouvoir appropriée.*

**Comment by tbeitter** [comment]
Another way would be to use xep-0114 (http://xmpp.org/extensions/xep-0114.html) as Conversations does since 1.5.0. Siacs implemented a little plugin to serve this (https://github.com/siacs/HttpUploadComponent).

The benefit is that you do not need the other client to support the file transfer xep, too. It's way more usable that way.

**Comment by sbrl** [comment]
I would go with the XEP-0114 that @tbeitter mentioned. I think pidgin uses this too? I have a SOCK5 file transfer proxy component set up in prosody on a subdomain that I use in pidgin.

**Comment by tbeitter** [comment]
the xep-0114 is not the socks transfer. It's used to upload the shared file to the server and the recipient will only get the http/https link to the file. That way there is no need to implement a file sharing logic on the recipient's side.

**Comment by sbrl** [comment]
@tbeitter Ok. So does pidgin handle this all automatically, or does it use some other method? I can't send files to someone using Xabber currently because it tells me that the recipient doesn't support it. This suggests that it uses some other method, but as for what I have no idea.

**Comment by moshpirit** [comment]
[XEP-0363: HTTP File Upload](http://xmpp.org/extensions/xep-0363.html) allows us to share files in conferences and with offline contacts but requires an [additional component](https://github.com/siacs/HttpUploadComponent) on the server already implemented in a lot of servers thanks to [Conversations](https://github.com/siacs/Conversations). It works perfectly so maybe it should be the best option to include instead of Jingle and Legacy because it's not necessary to have another client which enabled the XEP (it just shows a link to download the file).

**Comment by grigoryfedorov** [comment]
@moshpirit thanks! Could you suggest several servers for testing?

**Comment by moshpirit** [comment]
I'm on the street so I just can tell you that suchat.org allows it and works perfectly. Maybe mijabber.es too. Sorry for not telling you  more servers :(

**Comment by sbrl** [comment]
If my server supports it, I can give you an account or two on it if you want :)

Address: starbeamrainbowlabs.com
Server Software: Prosody 

I've just installed [mod_http_upload](http://modules.prosody.im/mod_http_upload.html) - I think that adds support to prosody. Here's the relevant snippet from my server's config file:

```lua
Component "filetransfers.starbeamrainbowlabs.com" "proxy65"
modules_enabled = {
    "http_upload";
}
```

Just ask and I will create you an account or two, and send you the login details by email.

**Comment by grigoryfedorov** [comment]
In new 1.0.51 version of Xabber Beta I've implemented HTTP file upload XEP-0363 (with new namespace, so server module should be updated). 
Also it now parses links to files.

**Comment by sbrl** [comment]
Awesome! Can't wait for the next beta release.

**Comment by grigoryfedorov** [comment]
@sbrl BTW you should update mod_http_upload on your server due to [this](http://hg.prosody.im/prosody-modules/rev/8ef500508c59) update. Thanks for test accounts :)

**Comment by sbrl** [comment]
@grigoryfedorov Done. No problem! Keep the test accounts and do whatever you like with them. Just contact me if you want a new module installing :)

**Comment by moshpirit** [comment]
A different name? Why??

Thanks for the great work here, but changing actual XEPs while requiring that the servers use it too doesn't sound really good to me :(

**Comment by sbrl** [comment]
@moshpirit Different name? I assumed that the new mod_http_upload that @grigoryfedorov linked to was just an update.

**Comment by moshpirit** [comment]
Oh, then I'm sorry, I've just woken and I probably I read it wrong. If that's the case, I'm really sorry for the misunderstanding. That's even better news!! \\o/

**Comment by sbrl** [comment]
@moshpirit I didn't read the diff properly.... so I don't actually have 
a clue what the update does :P

**Comment by grigoryfedorov** [comment]
@moshpirit you can see this issue siacs/HttpUploadComponent#51 in the HttpUploadComponent (namespace was different from XEP, and was fixed not far ago)

**Comment by moshpirit** [comment]
Oh, OK ;-)

**Comment by sbrl** [comment]
@moshpirit It's anyway been released in the beta channel!

**Comment by moshpirit** [comment]
Yes, but AFAIK you need a Google account for it.

**Comment by sbrl** [comment]
@moshpirit Don't you need a Google account to install any android app?

**Comment by moshpirit** [comment]
Of course not! I use F-droid. The only service I use from Google is YouTube and I use it from TOR browser. I've been living without any Google account for 2 or 3 years.

**Comment by sbrl** [comment]
@moshpirit I didn't know that. My phone asks me to sign in before I download apps.

-------- Original message --------

**Comment by moshpirit** [comment]
You don't need any account for using [F-droid](https://f-droid.org), just the [apk](https://f-droid.org/FDroid.apk). I don't want to be rude, but please, search on Internet or ask in the [forum](https://f-droid.org/forums), we are talking about an off-topic issue.  
You can contact me by using the link on my profile if you have more doubts.

**Comment by andrewnenakhov** [comment]
Now possible with http-upload in Xabber 2.0
