### ISSUE TITLE
Notification bar uses black icon with no content against black background becoming invisible

### ISSUE THREAD

**Issue by rogerbinns** [redsolution/xabber-android#231]
I just installed Xabber on an Android 4.3 Nexus 10.  The notification icon used comes up as pure black making it impossible to see.  It shows up like this 
![device-2013-07-30-150642](https://f.cloud.github.com/assets/553885/882547/d00328e4-f964-11e2-90b4-dce860acdd05.png)

Pulling down does show a Notification and a logo for the contact that has a black background with lots of blue in the middle.

**Comment by andrewnenakhov** [comment]
That was intended behavior in old versions of Android. No relevant for future version.
