### ISSUE TITLE
Change the notification icon (or make it monochrome)

### ISSUE THREAD

**Issue by Cal-A** [redsolution/xabber-android#232]
I've been using Xabber for a few days now, and have found that the red splodge on the notification bar is very eye-catching, so every time I glance down at my phone when there isn't a message waiting, I think an app wants my attention.

The yellow envelope to notify me of a new message is not at all eye-catching, it pretty much blends into the grey background. Worst of all, it hides the red part of the icon, so when I glance down at my phone and there's a message waiting, it looks like there's nothing needing my attention.

My suggestion to fix this would be to make the notification icon monochrome. That way, the envelope would appear as at least a small amount of colour and might get my attention. Better yet, make it (the "new message waiting" envelope) a bold colour such as red or blue.

**Comment by andrewnenakhov** [comment]
Material design guide for new androids tells us we should have blank single color icons. We'll try to make it such. As for this issue, it contradicts our former use of icon. It was red (colored) when Xabber was online and went grayscale when connection broke, so it was a handy way to see connection status. Closing issue, sorry.
