### ISSUE TITLE
XEP-0136: fetching message history from server?

### ISSUE THREAD

**Issue by lolmaus** [redsolution/xabber-android#233]
Hi!

I'm using Xabber with a XEP-0136-enabled server.

Xabber seems to update message history to server fine. When i view history from a desktop client, i can see messages sent from Xabber.

But it doesn't work vice versa. When i send messages from a desktop client, they do not appear in Xabber.

**Comment by andrewnenakhov** [comment]
Just use XEP-0313, it's supported by Xabber.
