### ISSUE TITLE
RTL messages should be right-aligned

### ISSUE THREAD

**Issue by tasn** [redsolution/xabber-android#234]
RTL messages should be right-aligned, not left aligned. There's a way in Android to let it automatically align according to text (LTR vs RTL). Just need to set it correctly and make the TextView the full width.

**Comment by grigoryfedorov** [comment]
It looks ok, I think. Here are some screenshots with RTL messaged. #374

**Comment by aelmahmoudy** [comment]
@grigoryfedorov actually those screenshots are old.

Currently, the outgoing arabic messages are left-aligned instead of being right-aligned.

**Comment by aelmahmoudy** [comment]
![xabber-arabic-dark](https://cloud.githubusercontent.com/assets/96682/7632444/c9108f38-fa55-11e4-9d2d-f7bd25b787d5.png)

**Comment by grigoryfedorov** [comment]
@aelmahmoudy I think, it become a little better now with 9937f1ba23bf2d976dc0f2fe0f3decb241eb06aa
But we probably should swap incoming and outgoing messages for RTL if the future.

**Comment by tasn** [comment]
It's really very simple. I've already explained how to solve it.
You need two things:
1. Make sure the text area is the full width of the surrounding "bubble".
2. Make sure that the text area has "auto align" (I forgot the correct name) depending on BiDi turned on (I think it's on by default, so you may have turned it off somewhere (or the issue is with 1).

**Comment by grigoryfedorov** [comment]
@tasn thank you. I did it almost as you said.

**Comment by tasn** [comment]
An alternative to moving the min width would have been to just change the wrap content to "match parent" (I haven't done Android dev in a while, don't remember the exact name), instead of wrap_content. Wrap_content is almost always a bad idea when dealing with bidi text.

**Comment by aelmahmoudy** [comment]
@grigoryfedorov Yes, RTL got fixed. Thanks
As for swapping incoming & outgoing messages, I suggest you do this based on the user's language/locale settings, not based on the language of the chat text.

**Comment by tasn** [comment]
@aelmahmoudy also with multiline text? If so, great to hear.
Swapping incoming & outgoing should be part of a whole set of changes for UI mirroring for the relevant locales (not based on the content of the conversation). If I remember correctly, I read somewhere that Android now has built in support for that, and you don't have to create a special layout for RTL languages, but maybe I'm wrong.

**Comment by aelmahmoudy** [comment]
@tasn yes, multiline text are right aligned.

Yes, Android has built-in support for RTL locales.

**Comment by aelmahmoudy** [comment]
Matter of fact, I'm not sure that swapping incoming & outgoing messages is even needed for RTL locales.

**Comment by tasn** [comment]
It's a whole different matter to this one, but as I said, it's part of ui mirroring, a whole different set of adjustments for RTL locales. You only want to do it for already translated locales (doesn't make sense otherwise), and is used by natives, not to mention the fact that Android does it anyway for the rest of the UI, so you might as well do it too for consistency.
