### ISSUE TITLE
what about a roadmap, particularly for key user features?

### ISSUE THREAD

**Issue by digisus** [redsolution/xabber-android#245]
There seems to be very little development activity going on since the move to open source xabber. In addition, judging from the version numbers, development happens in small steps only. Comments here are months old...

It leaves me wondering how much redsolution is still behind the project?

To be fair, starting an open source project, building a community, etc. are not easy tasks. Yet, I think a few steps could be made that show that RS is still actively behind the project. Announcing a roadmap for key user features - like file transfer and nice emoji support - that describes the features for a decent version 1.0 within half a year (and maybe some ideas for version 2.0) would go a long way giving trust to users to stay instead of looking for other xmpp alternatives, and help them convince their friends to switch, too. It would also signal to developers that it is worth to invest their time here rather than somewhere else.

Could Red Solution please reply and share their thoughts and ideally plans?
Thanks!

**Comment by andrewnenakhov** [comment]
Project had little care due to numerous issues.
