### ISSUE TITLE
Tapping lock symbol should open encryption menu

### ISSUE THREAD

**Issue by tanjeff** [redsolution/xabber-android#246]
I frequently enable/disable OTR manually, which involves quite a lot of tapping. It would be nice if the encryption menu were at hand on the lock symbol at the top of the conversation screen.

**Comment by alanthehat** [comment]
Can this go on an earlier milestone, please?

**Comment by grigoryfedorov** [comment]
implemented in e3c90c3d6d506f560ed4f567527095238e23f5c7

**Comment by alanthehat** [comment]
Thank you, that seems a lot more work than I was expecting
