### ISSUE TITLE
Contact information dialogue has menu button, but doesn't respond

### ISSUE THREAD

**Issue by schwindp** [redsolution/xabber-android#259]
Just open the information dialogue for one of your contacts and at the bottom of your phone there's a menu button to be seen. Unfortunately, it does not seem to have provide any action.

Android 4.1.1 on HTC One S, Xabber dev v0.9.30b

**Comment by andrewnenakhov** [comment]
I think it is no longer relevant, but check it pls.

**Comment by grigoryfedorov** [comment]
Not relevant.
