### ISSUE TITLE
No contact pictures, no automatic OTR, e-mail-address

### ISSUE THREAD

**Issue by BengaloBongali** [redsolution/xabber-android#260]
Hi! 3 Problems I encountered:
1. Contact pictures don't sync into Xabber even though I linked contacts.
2. I have to start OTR manually even though I put it on "automatic".
3. Linked contacts get their Xabber-addresses as e-mail-address and as chat-name.

Thx

**Comment by andrewnenakhov** [comment]
Please refer to one issue per, hm, issue.
