### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by bytemasteR66** [redsolution/xabber-android#263]
Hi,

whatsapp is very nice but when i add 50 contacts into my phone and send messages (no spam) whatsapp freeze my Account. 

My idea to fix it in all versions the Client string is not up to date ..

   "User-Agent: WhatsApp/2.4.7 S40Version? And an samsung galaxy s 3 string its old :(

**Comment by andrewnenakhov** [comment]
We do not plan to implement WhatsApp functionality in Xabber.
