### ISSUE TITLE
Own messages not shown in MUC when connected with multiple clients

### ISSUE THREAD

**Issue by Petteri** [redsolution/xabber-android#265]
One can log in to a MUC room with multiple Jabber clients using the same nickname. Normally I can see all my messages on all my connected Jabber clients. On Xabber this seems to be broken, as Xabber does not display messages typed on the other clients.

**Comment by nd2s** [comment]
It's 2016 and this version doesn't seem to be deployed yet? I'm still running 1.0.30 and just experienced this bug.

**Comment by NeoXiD** [comment]
@nd2s While I do not want to turn you away from Xabber Android, I still recommend you to take a look at other clients. A good example would be [Conversations](https://github.com/siacs/Conversations) which I am using myself since a while as Xabber doesn't seem to be very active anymore.

**Comment by nd2s** [comment]
@NeoXiD Well that's the only problem I have, and it seems to be fixed already. I just don't understand why there is no release.
I really like Xabber otherwise. Works better than any desktop client I am using!

**Comment by brahmann** [comment]
Hi all, bug still exists, same here. Pls release newest version with fixed bug. Thank you

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
