### ISSUE TITLE
Different aliases for different own accounts to show in chat window

### ISSUE THREAD

**Issue by openvoidab** [redsolution/xabber-android#267]
It is possible to set up alias for contact to fancy look in chat window. But I could not find option for alias to yourself and own messages always shown as user@domain.tld. With google apps domains messages from self shown as user@domain.tld@domain.tld what is weird.

**Comment by grigoryfedorov** [comment]
Own alias is not shown in chat window anymore. 
Own vcard editing would be implemented later.
