### ISSUE TITLE
Problem of permission with the chats multisesion with password

### ISSUE THREAD

**Issue by susobaco** [redsolution/xabber-android#269]
Hello
Xabber is giving me An error of permission in rooms multichat with password and limited to users. When it already is connected, after a time, goes out the error of permission, but seems that it follows connected.
Sorry by the question.Where is the archive log to be able to see the error?
Thank you

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
