### ISSUE TITLE
Xabber always use "Manual server" when adding new accounts

### ISSUE THREAD

**Issue by luisgf** [redsolution/xabber-android#275]
Hello:

The last version of Xabber always use "Manual server" to override DNS localtion of XMPP server, That's broke the standard and cause many problems with connections. Some domains can work if the DNS resolution of JID part is the same that the XMPP host, but this is not true for many servers.

**Comment by andrewnenakhov** [comment]
Will be fixed in by the time new version is ready.

**Comment by grigoryfedorov** [comment]
implemented in 8c8f7a70e7f141275a5d7142506977c58c1cbda3
