### ISSUE TITLE
Add support for images in text field

### ISSUE THREAD

**Issue by ignobble** [redsolution/xabber-android#289]
A non-nerd friend of mine, normally not caring about privacy, free software or whatever, made a first remark I would like to share: Why can't I send photos, videos and weblinks to you in the text like this: http://www.zdnet.de/wp-content/uploads/2013/04/whatsapp-unter-ios.jpg

Would be a nice feature.

**Comment by andrewnenakhov** [comment]
Because those features can't be implemented by client software only. Sent images need to be stored somewhere (peer to peer works poorly for such purposes), server should support it etc.

We plan to do something like that but not like suggested here.
