### ISSUE TITLE
data is not erasable

### ISSUE THREAD

**Issue by skoria** [redsolution/xabber-android#290]
Hi, Thanks for making xabber available still on the earliest android phones.. I'm proud to have a still working G1 with xabber on it, using otr etc. But it only has very little space for applications: about 100 meg in all, as it's such a prehistoric phone (5 full years old!). Xabber seems to accumulate data, and is now consuming 14m of data and also has a section where normally you can delete  cache, but whenever I look there is never any cache I can delete, there is always more data, and I can't delete just the data. The data should just be the message history or things like that.. Maybe contact lists.. All stuff I can get again. How can I add a bit of code to xabber to make it possible to clear this data?

**Comment by andrewnenakhov** [comment]
@skoria You re probably having your history stored on device. Just turn off storing read messages in Settings->XMPP Accounts -> your@account.domain -> History options (scroll down to bottom)
