### ISSUE TITLE
Send media 

### ISSUE THREAD

**Issue by KThand1** [redsolution/xabber-android#293]
Hey

Enhancement - Would be really cool to allow media/ contacts / location to be sent via  muc and single chats. Then I really would leave whatsapp forever.

**Comment by andrewnenakhov** [comment]
We're working on it but this issue can't be resolved in a meaningful way by means of client software only.

**Comment by TameOfGroans** [comment]
Leave whatapp forever anyway.  Privacy is not a commodity.
