### ISSUE TITLE
keyboard popup option

### ISSUE THREAD

**Issue by kjoe** [redsolution/xabber-android#294]
Hello,

Please provide an option to don't pop up the keyboard automatically when I enter a (previous) chat room. We use jabber to receive monitoring messages, and we don't want to reply to any messages, so continuously closing that keyboard is quite annoying.

Thanks!

**Comment by andrewnenakhov** [comment]
I think entering chat should not bring up keyboard. Only tap on text input area should.

**Comment by andrewnenakhov** [comment]
@grigoryfedorov close this if it's fixed.

**Comment by grigoryfedorov** [comment]
Now keyboard opens only after tap on input field.
