### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by nickelchen** [redsolution/xabber-android#300]
hi, there. Is the project still under maintained? The last commit is about 8 months ago and many issues and pull requests are left unhandled

**Comment by dbanet** [comment]
Updates?

**Comment by AnrDaemon** [comment]
> Xep-0280 looks almost like what we need to achieve that, but there are some cases where direct implementation will still cause mobile devices lose some messages.

You're thinking about [XEP-0313: Message Archive Management](http://xmpp.org/extensions/xep-0313.html), which is in direct relation to [XEP-0280: Message Carbons](http://xmpp.org/extensions/xep-0280.html).
Glad to see development going.
Though, if the final design will have a little less white, it'd be much appreciated.

**Comment by aelmahmoudy** [comment]
I hope the new version would get in-band registration #11, I did make an attempt to support it #305  , but it isn't working :(

**Comment by Bretos** [comment]
Guys, redsolution is looking for xabber [testers](https://twitter.com/Xabber_XMPP/status/560772996881989633)! Wish they had announced it here too...

**Comment by grigoryfedorov** [comment]
Hi!
Yes, you can now try early builds of new version of Xabber (alpha testing).
We're working on new UI with material theme. Supporting Android 4+. And currently only English and Russian translations. 
Changes so far: 
- material theme
- new options menu style
- improved notifications

These builds are base on develop and feature/* brunches, so you can build them yourself. 

Here is our Google Plus community: 
https://plus.google.com/u/1/communities/100341615050871433040
To become member of Google Play Xabber alpha test team you should join it and follow the link placed inside. Link will lead you to Google Play and alpha builds would be installed and updated automatically. And we will be able to see all error reports as usual published application. 

Reviews and bug reports are welcome. 
Thank you!

P.S. Don't share screenshots.

**Comment by aelmahmoudy** [comment]
@grigoryfedorov is the new Xabber compatible with data (accounts + chat history) from old Xabber ?

**Comment by grigoryfedorov** [comment]
@aelmahmoudy it's compatible with development version from play market (you can update), but you may have problems (need reinstall), if you would like to downgrade later.

**Comment by dbanet** [comment]
@grigoryfedorov can I test the alpha version without having to mess with Google, Google+, communities, social networks, Play Markets and all that sh*t so on?

Just an FTP/HTTP directory with fresh APKs?

**Comment by grigoryfedorov** [comment]
@dbanet I think, we can do that)

**Comment by Bretos** [comment]
@dbanet which XEP is Xabber using for storing history server-side?

**Comment by dbanet** [comment]
@grigoryfedorov thank you for understanding.

@Bretos XEP-0136 apparently.

**Comment by aelmahmoudy** [comment]
@grigoryfedorov just tested the one from tip of develop branch, very nice. I prefered the colored notification icon though ! Guess it's a matter of taste.

Do you mind we put that on F-Droid (but not as the default download) ?

**Comment by aelmahmoudy** [comment]
@grigoryfedorov Some comments:

* There is no "account's panel" anymore, yet the option to show it is still there. It is useful to have the account's panel to know which accounts are connecting/connected/offline

* The bar of the offline accounts are not marked with striped colors as it used to be in old accounts, I hope there would be some indicator for the status of each account

**Comment by grigoryfedorov** [comment]
@aelmahmoudy 
- notifications icons are not the final variant. Especially the persistent one. Colorless notification icons is new Android standart..
- account's panel will be returned surely. 
-  we'll think about F-droid, for me it looks like better solution, than simple FTP/HTTP directory with APKs.

**Comment by grigoryfedorov** [comment]
@aelmahmoudy it would be greate, if you put unstable builds of xabber to F-droid (as you said, not replacing the stable one).
@dbanet is F-Droid ok for you?

**Comment by aelmahmoudy** [comment]
@grigoryfedorov In progress, please consider #331

**Comment by dbanet** [comment]
@grigoryfedorov sure it is, thank you.

**Comment by andrewnenakhov** [comment]
Closing issue.l

**Comment by dbanet** [comment]
Up! Again no progress for two months! #128 is extremely essential!

**Comment by andrewnenakhov** [comment]
@dbanet enjoy #128 now
