### ISSUE TITLE
Ability to hide or change client info

### ISSUE THREAD

**Issue by sbriskin** [redsolution/xabber-android#302]
For security purpose need an ability to hide or change client info.
For example: client id could compromise someone and violate the anonymity while connected through Tor, because of static id "Xabber s0meRand0m?data="

**Comment by DefyMiners** [comment]
This can be seen in action by Psi+ 

Hide, spoof, mix.

**Comment by andrewnenakhov** [comment]
After long consideration, we'd rather not.
