### ISSUE TITLE
notification icon in android 4.4

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#306]
notifications for chats in android 4.4 face no icons. they show up fine, everything works fine, just no icon is placed in the navbar (so it shows up as empty spot in navbar)
![screenshot_2014-07-20-19-02-39](https://cloud.githubusercontent.com/assets/8217073/3638016/ede54700-1030-11e4-8f70-c32a8319135f.png)
![screenshot_2014-07-20-19-02-51](https://cloud.githubusercontent.com/assets/8217073/3638017/ee108f64-1030-11e4-9c67-621094767237.png)

**Comment by andrewnenakhov** [comment]
This is an effect of hack used in old androids to make persistent notification behave well. No longer relevant in new versions.
