### ISSUE TITLE
Clickable URL from vcard in contact information

### ISSUE THREAD

**Issue by flekmatik** [redsolution/xabber-android#308]
When I taphold contact in roster ... menu shows. In that menu I can select option "View Information" ... there is a list of details about user from his/her vcard.

There is a field named "Web Site" which shows user's website URL. Would it be possible for this field to be clickable? ... So when I tap on this field I am forwarded to default browser which shows me tapped URL.

Absolutely ideal would be to propagate this field to system contacts too.

**Comment by grigoryfedorov** [comment]
Implemented in cb77bd4e147fd6f603b754729afb69e3545edf8f
