### ISSUE TITLE
xabber crashes during otr enabled chat with a contact via bitlbee

### ISSUE THREAD

**Issue by lsm5** [redsolution/xabber-android#312]
So, I connect to my xmpp accounts using both xabber and screen+irssi+bitlbee (remote machine). I initiated an otr session via bitlbee with a contact of mine and noticed that xabber crashed.

Most probably a stupid question, but is it possible to have two xmpp clients use the same otr key (and would that be a good idea to begin with)?

Or is it some config option I'm probably missing?

**Comment by DefyMiners** [comment]
My understanding is one otr key per resource. I am not sure why you would want one resource shared by two devices.

Older but topical.. as I myself am behind on reading

https://lists.torproject.org/pipermail/tor-dev/2013-October/005640.html

Although it seems you could sync 
https://github.com/guardianproject/keysync

Additionally
http://op-co.de/blog/posts/mobile_xmpp_in_2014/

**Comment by andrewnenakhov** [comment]
You should not use same OTR key like described.

**Comment by lsm5** [comment]
sounds good, i stopped using bitlbee anyway, so it's probably a non-issue for me atleast. Thanks!

**Comment by kbramprasath** [comment]
hi please help me,am login same account to multiple device ,but only one device only  received msg .how to fix multiple device recived

**Comment by andrewnenakhov** [comment]
That is a fundamental problem that can't be solved solely on clientside.
Your server should support XEP-280, although that's not enough.

2015-02-18 13:54 GMT+05:00 ramprasath <notifications@github.com>:

> hi please help me,am login same account to multiple device ,but only one
> device only received msg .how to fix multiple device recived
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redsolution/xabber-android/issues/312#issuecomment-74831527>
> .
>



-- 
Ненахов Андрей
Директор ООО "Редсолюшн" (Челябинск)
(351) 750-50-04
http://www.redsolution.ru

**Comment by kbramprasath** [comment]
.thanks but iphone same xmpp its worked andrewnenakhov

**Comment by andrewnenakhov** [comment]
Well, no. It's not same xmpp, if you're talking about iMessage.

Actually we plan to fix xmpp's problem eventually, but not too soon.

2015-02-19 18:14 GMT+05:00 ramprasath <notifications@github.com>:

> .thanks but iphone same xmpp its worked andrewnenakhov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redsolution/xabber-android/issues/312#issuecomment-75049621>
> .
>



-- 
Ненахов Андрей
Директор ООО "Редсолюшн" (Челябинск)
(351) 750-50-04
http://www.redsolution.ru

**Comment by victort** [comment]
necropost, but i'm having a problem (was there an update recently?) with xabber disco'ing on recepit of OTR messages, is this a regression or something new?
