### ISSUE TITLE
120 second period client signout

### ISSUE THREAD

**Issue by krustyman** [redsolution/xabber-android#313]
I am using the 0.9.30b client on a couple of my Android devices and love it. However via wireshark I am seeing the client send a presence unavailable and a closing stream every 120 seconds approximately. The client reconnects without issue. I did not notice this behavior when I first installed it and wondering what within the app that would be causing it to send a closing stream every 120 seconds approx? Is it expecting something from the Server it is not getting within 120 seconds? 

Signed...stumped

**Comment by andrewnenakhov** [comment]
@a-iv please, comment on it
