### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by 6vasia** [redsolution/xabber-android#314]
Cannot connect to my account at hosted.im. Also certificate validation fails.
Xabber version 0.9.30b, log:

09-02 00:02:25.116 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update records for gadfly.tk:
09-02 00:02:25.116 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 10 0 5222 xmpp1.hosted.im.
09-02 00:02:25.116 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 20 0 5222 xmpp2.hosted.im.
09-02 00:02:25.116 I/com.xabber.android.data.connection.ConnectionThread@41d0cb18(  433): Resolve xmpp2.hosted.im.:5222
09-02 00:02:25.116 I/com.xabber.android.ui.AccountEditor@41a12da8(  433): onPause
09-02 00:02:25.136 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:25.136 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp2.hosted.im.:
09-02 00:02:25.136 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp2.hosted.im./184.73.173.246
09-02 00:02:25.136 I/com.xabber.android.ui.AccountList@417f1d38(  433): onResume
09-02 00:02:25.146 I/com.xabber.android.data.connection.ConnectionThread@41d0cb18(  433): Resolve xmpp1.hosted.im.:5222
09-02 00:02:25.146 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp1.hosted.im.:
09-02 00:02:25.146 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp1.hosted.im./184.73.173.246
09-02 00:02:25.146 I/com.xabber.android.data.connection.ConnectionThread@41d0cb18(  433): Use xmpp1.hosted.im./184.73.173.246
09-02 00:02:25.176 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:25.506 I/com.xabber.android.ui.AccountEditor@41a12da8(  433): onDestroy
09-02 00:02:26.137 W/System.err(  433): com.xabber.android.data.connection.CertificateManager@41a5b478
09-02 00:02:26.147 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 23, ticker: Неверный сертификат, sound: content://settings/system/notification_sound, vibro: 2, light: 4
09-02 00:02:26.387 I/com.xabber.android.data.account.AccountItem@41f69a80:me@gadfly.tk/phone(  433): onClose 1105874968 - 123, true
09-02 00:02:26.427 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:29.560 I/ActivityManager(  590): START u0 {dat=/db98fd546df6b1566f7b5ff1705d56637ddbafff/invalidTarget cmp=com.xabber.android/.ui.CertificateConfirmation bnds=[0,77][540,172]} from pid -1
09-02 00:02:29.560 W/ActivityManager(  590): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { dat=/db98fd546df6b1566f7b5ff1705d56637ddbafff/invalidTarget cmp=com.xabber.android/.ui.CertificateConfirmation bnds=[0,77][540,172] }
09-02 00:02:29.771 I/com.xabber.android.ui.AccountList@417f1d38(  433): onPause
09-02 00:02:29.781 I/com.xabber.android.ui.CertificateConfirmation@41fb9770(  433): onCreate: Intent { dat=/db98fd546df6b1566f7b5ff1705d56637ddbafff/invalidTarget cmp=com.xabber.android/.ui.CertificateConfirmation bnds=[0,77][540,172] }
09-02 00:02:29.801 I/com.xabber.android.ui.CertificateConfirmation@41fb9770(  433): onResume
09-02 00:02:29.871 I/ActivityManager(  590): Displayed com.xabber.android/.ui.CertificateConfirmation: +96ms
09-02 00:02:31.432 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update records for gadfly.tk:
09-02 00:02:31.432 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 20 0 5222 xmpp2.hosted.im.
09-02 00:02:31.432 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 10 0 5222 xmpp1.hosted.im.
09-02 00:02:31.432 I/com.xabber.android.ui.CertificateConfirmation@41fb9770(  433): onPause
09-02 00:02:31.432 I/com.xabber.android.data.connection.ConnectionThread@41fa7d20(  433): Resolve xmpp1.hosted.im.:5222
09-02 00:02:31.442 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:31.452 I/com.xabber.android.ui.AccountList@417f1d38(  433): onResume
09-02 00:02:31.452 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp1.hosted.im.:
09-02 00:02:31.452 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp1.hosted.im./184.73.173.246
09-02 00:02:31.452 I/com.xabber.android.data.connection.ConnectionThread@41fa7d20(  433): Resolve xmpp2.hosted.im.:5222
09-02 00:02:31.472 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp2.hosted.im.:
09-02 00:02:31.472 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp2.hosted.im./184.73.173.246
09-02 00:02:31.472 I/com.xabber.android.data.connection.ConnectionThread@41fa7d20(  433): Use xmpp2.hosted.im./184.73.173.246
09-02 00:02:31.502 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:31.823 I/com.xabber.android.ui.CertificateConfirmation@41fb9770(  433): onDestroy
09-02 00:02:32.323 W/System.err(  433): com.xabber.android.data.connection.CertificateManager@41a5b478
09-02 00:02:32.834 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:32.984 W/System.err(  433): com.xabber.android.data.account.AccountItem@41f69a80:me@gadfly.tk/phone
09-02 00:02:32.984 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.authorization(ConnectionThread.java:506)
09-02 00:02:32.994 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.access$8(ConnectionThread.java:504)
09-02 00:02:32.994 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$14.run(ConnectionThread.java:494)
09-02 00:02:32.994 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:663)
09-02 00:02:32.994 I/com.xabber.android.data.account.AccountItem@41f69a80:me@gadfly.tk/phone(  433): onClose 1106564264 - 124, true
09-02 00:02:33.014 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:33.054 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.authorization(ConnectionThread.java:537)
09-02 00:02:33.054 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.access$8(ConnectionThread.java:504)
09-02 00:02:33.054 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$14.run(ConnectionThread.java:494)
09-02 00:02:33.054 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:663)
09-02 00:02:35.537 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:35.567 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update records for gadfly.tk:
09-02 00:02:35.567 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 10 0 5222 xmpp1.hosted.im.
09-02 00:02:35.567 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): _xmpp-client._tcp.gadfly.tk.    1799    IN  SRV 20 0 5222 xmpp2.hosted.im.
09-02 00:02:35.577 I/com.xabber.android.data.connection.ConnectionThread@41e6c7f0(  433): Resolve xmpp2.hosted.im.:5222
09-02 00:02:35.747 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp2.hosted.im.:
09-02 00:02:35.747 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp2.hosted.im./184.73.173.246
09-02 00:02:35.747 I/com.xabber.android.data.connection.ConnectionThread@41e6c7f0(  433): Resolve xmpp1.hosted.im.:5222
09-02 00:02:35.757 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): Update address for xmpp1.hosted.im.:
09-02 00:02:35.757 I/com.xabber.android.data.connection.DNSManager@41a5af50(  433): xmpp1.hosted.im./184.73.173.246
09-02 00:02:35.757 I/com.xabber.android.data.connection.ConnectionThread@41e6c7f0(  433): Use xmpp1.hosted.im./184.73.173.246
09-02 00:02:35.757 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:36.598 W/System.err(  433): com.xabber.android.data.connection.CertificateManager@41a5b478
09-02 00:02:36.988 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:37.178 W/System.err(  433): com.xabber.android.data.account.AccountItem@41f69a80:me@gadfly.tk/phone
09-02 00:02:37.188 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.authorization(ConnectionThread.java:506)
09-02 00:02:37.188 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.access$8(ConnectionThread.java:504)
09-02 00:02:37.188 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$14.run(ConnectionThread.java:494)
09-02 00:02:37.188 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:663)
09-02 00:02:37.188 I/com.xabber.android.data.account.AccountItem@41f69a80:me@gadfly.tk/phone(  433): onClose 1105628608 - 125, true
09-02 00:02:37.188 I/com.xabber.android.data.notification.NotificationManager@41a511e0(  433): Notification: 1, ticker: null, sound: null, vibro: 0, light: 0
09-02 00:02:37.198 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.authorization(ConnectionThread.java:537)
09-02 00:02:37.198 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread.access$8(ConnectionThread.java:504)
09-02 00:02:37.198 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$14.run(ConnectionThread.java:494)
09-02 00:02:37.198 W/System.err(  433):     at com.xabber.android.data.connection.ConnectionThread$20.run(ConnectionThread.java:663)

**Comment by andrewnenakhov** [comment]
possibly  a bug

**Comment by andrewnenakhov** [comment]
Latest Xabber should probably work fine by now. @6vasia if it's not, reopen issue please
