### ISSUE TITLE
Empty notification for chat with disabled notifcations

### ISSUE THREAD

**Issue by prius** [redsolution/xabber-android#315]
See screenshot
![Bug]
(http://cs616824.vk.me/v616824303/1b000/viF9aGdEbHU.jpg)
The first notification is from Hangouts.
The second notification is from Xabber.

Btw all notifications for this contact in Xabber are disabled, because I'm using Google Hangouts app to talk with him.

There is a settings menu for this contact.
![Settings]
(http://cs616824.vk.me/v616824303/1aff8/GBM67JYaHl8.jpg)
Please fix this, I don't want to see any notifications from contacts with disabled notifications.

**Comment by DefyMiners** [comment]
Unchecking "show message in notification" is not the same as show zero notification. The feature does not place message content as shown in your screenshot.

**Comment by andrewnenakhov** [comment]
Notifications are heavily rewritten, but we should check for additional options to work properly

**Comment by grigoryfedorov** [comment]
As @DefyMiners mentioned, it is not actually a bug. 
Xabber do not have options to disable notifications for specific contacts or chats. We plan to implement such options and also "mute notifications for N hours" in next milestones.
