### ISSUE TITLE
bad choice: OTR notifications do pop up in background only

### ISSUE THREAD

**Issue by laclaro** [redsolution/xabber-android#319]
Hi,

all notifications of the xabber-client do pop up in the android notification area. I think it would be better (e.g. for OTR-authentification) if they would pop up directly in the xabber-application. If you are new to the client, a background-notification on OTR-auth is really not obvious!

We shall make things as easy as possible for unexperienced users, most importantly OTR!

best regards
Henning

**Comment by DefyMiners** [comment]
This should be optional if implemented.  Notification bar is where notifications are placed. Does not xabber also play you a notification sound?

**Comment by andrewnenakhov** [comment]
notifications will soon be completely rewritten, issue would not be relevant.

**Comment by mis2417** [comment]
i can confirm with 1.0.8 password prompts and ssl certificate issue

**Comment by andrewnenakhov** [comment]
We like how Xabber works with notifications now.
