### ISSUE TITLE
xabber locks my account immediately after password change

### ISSUE THREAD

**Issue by bkibbey** [redsolution/xabber-android#320]
Scenario:  My corporate XMPP server requires frequent password changes... I am forced to change it there first... if I do not disable the profile in xabber, it will immediately cause my account to be locked because it re-try's logon repeatedly even if the logon information is bad.   

Assumption: This assumes the XMPP protocol / server provide some level of detail on why the logon failed - I admit I don't know much about that protocol.

Suggested Repair: During logon attempts; xabber should evaluate the response from the server.  In the event the server replies with a logon failed message, xabber should stop attempting logon / disable the account in the client and notify the user of an issue.  [this could be setup as a user select- able option too]

Clarification: In the event the server can't be reached due to network issues, or if the server replies with messages indicating it is busy or whatever, it makes sense to continue attempting logon; but it should not continue if there is indication of bad logon credentials by the server.

thanks,
bruce

**Comment by DefyMiners** [comment]
An issue similar to this resolved between Conversations 0.9.3 and 0.1.0

**Comment by andrewnenakhov** [comment]
Actually it works almost like suggested now
