### ISSUE TITLE
Can't connect to servers with TLSv1 disabled

### ISSUE THREAD

**Issue by bluec0re** [redsolution/xabber-android#324]
Xabber uses TLSv1 to connect to XMPP servers. As TLSv1 is vulnerable to the BREACH attack, some servers disable the corresponding cipher suites.

**Comment by DefyMiners** [comment]
Is the server in question "rated A" via http://xmpp.net ?

**Comment by bluec0re** [comment]
Yes. Almost 100% rating in all scores:
https://xmpp.net/result.php?domain=xmpp.timoschmid.de&type=client

**Comment by KPEBETKA** [comment]
Не стал создавать новый тредик, решил написать здесь, ибо проблема похожая

Имеется сервер Prosody. В его настройках следующее
ssl = {
        key = "/etc/prosody/certs/certificate.pem";
        certificate = "/etc/prosody/certs/certificate.pem";
        dhparam = "/etc/prosody/certs/dh-4096.pem";
        curve = "secp521r1";
        options = {
                    "no_sslv2",
                    "no_sslv3",
                    "no_ticket",
                    "no_compression",
                    "single_ecdh_use",
                    "single_dh_use"
                    };
        ciphers = "ECDH+AESGCM:DH+AES256:!eNULL:!aNULL:!AES128:!SHA:!DSS";
        }
Т.е. включены только самые стоёкие шифры TLSv1.2. Пруф - https://kpebetka.net/screenshots/2015_Январь_01-21_06_45_ff4fc81672b2e4fd45cec600b43115a22ce0df0cf8188a8a2b093dac2fa094af.png

Pidgin коннектится без проблем, а Xabber не хочет ни в какую, хоть об стену колоти

В логах Prosody при попытке законнектится Xabber'ом вываливаются ошибки вида
    Dec 13 20:13:03 c2sa31090 info Client connected
    Dec 13 20:13:03 c2sa31090 info Client disconnected: ssl handshake failed
    
На телефоне Android 4.4.4 CyanogenMod. И если верить sslabs.com, то сей ведроид поддерживает TLSv1.2, причём, даже поддерживает самый стойкий шифр. Пруф - https://kpebetka.net/screenshots/2015_Январь_01-21_04_50_049403fba76ba212ed3be5c9075a9e5479a91a9e24fb3f6ad2dcc372b69d8809.png

Чтобы Xabber начал работать, приходится включать шифры TLSv1.0, меняя ciphers на ECDH+AESGCM:DH+AES256:!eNULL:!aNULL:!AES128:!DSS, чтобы появился хоть один шифр TLSv1.0. Пруф - https://kpebetka.net/screenshots/2015_Январь_01-21_11_44_33136413ebd7054d55f0e8bc2e30f83a2d82fee6d3377018917b74f9d8eebf7f.png

**Comment by vladamatena** [comment]
Hi, I also missed the TLS1.2 support. For some reason it has to be explicitly enabled in the code. I did the following modification and TLS1.2 now seems to work (tests against jabberd2-2.3.2 on Android 4.4.4):

	diff --git a/app/src/main/java/org/jivesoftware/smack/XMPPConnection.java b/app/src/main/java/org/jivesoftware/smack/XMPPConnection.java
	index fe9da08..3820abb 100644
	--- a/app/src/main/java/org/jivesoftware/smack/XMPPConnection.java
	+++ b/app/src/main/java/org/jivesoftware/smack/XMPPConnection.java
	@@ -868,10 +868,18 @@ public class XMPPConnection extends Connection {
		*/
		void proceedTLSReceived() throws Exception {
			enableEncryption(true);
	+
	+        // TODO: This does the TLS1.2 magic, but it should be done properly
	+        // Configure security
	+        SSLSocket sslSocket = ((SSLSocket) socket);
	+        sslSocket.setEnabledProtocols(new String[]{"TLSv1.2"});
	+
			// Initialize the reader and writer with the new secured version
			initReaderAndWriter();
	+
			// Proceed to do the handshake
	-        ((SSLSocket) socket).startHandshake();
	+       sslSocket.startHandshake();
	+
			//if (((SSLSocket) socket).getWantClientAuth()) {
			//    System.err.println("Connection wants client auth");
			//}

The resulting xabber build can be found here: http://share.mattty.cz/xabber-TLS1.2.apk
