### ISSUE TITLE
KitKat, no settings [resource, priority, pep, non-account]

### ISSUE THREAD

**Issue by DefyMiners** [redsolution/xabber-android#325]
KitKat, galaxy S5 DE, vzw

0930c dev fdroid 

Through google frippery the useful context key was replaced by a button whose feature was already present by holding the home button. Now how does one invoke the settings without overflow menu available?

The only Xposed Framework modules available are for  crippling android not restoring context button. The one claim8ng to function desirably seems to break other features as described by xda feedback.

I am stuck using Conversations;  and while I enjoy much of it I still would prefer to have both available.

**Comment by DefyMiners** [comment]
S5 long holding task button opens context menu

Hooray

**Comment by wiseoldman95** [comment]
Yes, long holding the task button opens up the context menu.
