### ISSUE TITLE
Switch otr4j to otr4j/otr4j implementation

### ISSUE THREAD

**Issue by languitar** [redsolution/xabber-android#330]
The internal otr4j implementation is quite old an contains several bugs, e.g. not otrv3 handling. There is currently an initiative to collect all different modifications of the original otr4j library back in the otr4j/otr4j repository. It would be good if xabber switched to this version.

**Comment by aelmahmoudy** [comment]
I see that you didn't include the last 4 commits in https://github.com/redsolution/otr4j , have you merged other commits/fixes doing the same objective ?

**Comment by eighthave** [comment]
One of the @jitsi developers said that they had included those commits in a different form, so I took them at their word and based the  https://github.com/otr4j/otr4j repo off of the latest that was in jitsi/otr4j.  Everything that is in  https://github.com/jitsi/otr4j is included in  https://github.com/otr4j/otrj4.

**Comment by aelmahmoudy** [comment]
I've done this on https://github.com/redsolution/xabber-android/tree/new_otr, but I wasn't able to compile otr4j/otr4j because I didn't find sources for org.bouncycastle packages, so I replaced it with org.spongycastle (it has a repo on github)

**Comment by languitar** [comment]
There is already an issue about that: https://github.com/otr4j/otr4j/issues/1

**Comment by aelmahmoudy** [comment]
Alright, I can now compile it against bouncycastle.

**Comment by aelmahmoudy** [comment]
Shouldn't this be closed ?
