### ISSUE TITLE
Please add QR code for F-Droid version in your website

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#331]
The F-Droid URL is: https://f-droid.org/repository/browse/?fdid=com.xabber.androiddev

**Comment by aelmahmoudy** [comment]
Attaching the QR code for convenience:
![xabber-fdroid-qr](https://cloud.githubusercontent.com/assets/96682/5975205/4096ba36-a886-11e4-9344-42effcf0db73.JPG)

**Comment by andrewnenakhov** [comment]
we'll think of it with website update.
