### ISSUE TITLE
de_DE translation

### ISSUE THREAD

**Issue by kr428** [redsolution/xabber-android#332]
Folks,

am thoroughly missing the German locales that seem to have been removed in recent builds. What needs to be done to get them back? :)
Cheers,
Kristian

**Comment by grigoryfedorov** [comment]
Hello!
You are right, German locale was excluded due to it's incompleteness. 
As written in Xabber [readme](https://github.com/redsolution/xabber-android#translations), we're using [webtranslateit](https://webtranslateit.com/en/projects/1218-xabber) and help of our community is highly appreciated. So 
> If you want to update any translation please email us to info[at]xabber.com and specify all the translation languages you want to edit. Then we'll send an invitation to our project on webtranslateit.com. 

Thank you!

**Comment by moshpirit** [comment]
Creating an account: 
>**Thank you for signing up to WebTranslateIt** 
>You are signing up to an unrestricted 30-day free trial period. You will choose a plan when the trial expires and when you know which plan you actually need.

Is it really necessary? I don't want a "premium" account.

**Comment by andrewnenakhov** [comment]
Well it wasn't necessary to create a paid account to take part in
translating Xabber он webtranslateit, but we've migrated to different
translation platform,
https://crowdin.com/project/xabber  :)

2015-05-21 3:30 GMT+05:00 moshpirit <notifications@github.com>:

> Creating an account:
>
> *Thank you for signing up to WebTranslateIt*
> You are signing up to an unrestricted 30-day free trial period. You will
> choose a plan when the trial expires and when you know which plan you
> actually need.
>
> Is it really necessary? I don't want a "premium" account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redsolution/xabber-android/issues/332#issuecomment-104062298>
> .
>



-- 
Ненахов Андрей
Директор ООО "Редсолюшн" (Челябинск)
(351) 750-50-04
http://www.redsolution.ru

**Comment by moshpirit** [comment]
I know, I translated the Spanish version on Crowdin, thanks for the migration!!

**Comment by andrewnenakhov** [comment]
well, thank you for your help )

**Comment by moshpirit** [comment]
My help is almost nothing compared to your huge work!  
When Xabber included jingle, MAM and fix the MUC user hidding error I'll help again creating some "why and how to use Xabber" tutorial. 

Btw, we can't translate the "About" AFAIK, should we?

**Comment by andrewnenakhov** [comment]
@moshpirit we believe we'll making significant changes to 'about' screen, so it's not wise to ask our translators to waste time translating something that we'll discard rather sooner than later. :)

**Comment by moshpirit** [comment]
Oh, OK
