### ISSUE TITLE
Removed key phrases do not actually get removed

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#334]
After key phrase removing and application relaunch, removed key phrase appears back in the list.

**Comment by Human** [comment]
I believe I've fixed this in the master branch ( https://github.com/redsolution/xabber-android/pull/806 ) as well as the develop branch ( https://github.com/redsolution/xabber-android/pull/805 ). Waiting on a merge.

Test procedure I followed:

1. launch app
2. go into Settings -> Notifications -> Key phrases
3. add a test key phrase
4. exit the app
5. kill the app by swiping away
6. force stop the app in Android Settings -> Apps -> Xabber Beta
7. re-launch app
8. go into Settings -> Notifications -> Key phrases
9. delete the test key phrase
10. exit the app
11. kill the app by swiping away
12. force stop the app in Android Settings -> Apps -> Xabber Beta
13. re-launch app
14. go into Settings -> Notifications -> Key phrases
15. _with the bug_ the test key phrase is still there; _without the bug_, the test key phrase is gone

**Comment by Str4tocaster** [comment]
Closed with https://github.com/redsolution/xabber-android/commit/d2a91261ffbfd263b48b949e04f678e82e196ed4
