### ISSUE TITLE
Chat notification reappears even if dismissed

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#337]
This occurs in version 0.10.10. When someone sends me some text, it displays that in notification, so far that's normal.
The problem is that if I dismiss the notification (by swiping it) instead of click it to read it in Xabber, the notification reappears again & again, until I click it to open Xabber.

**Comment by grigoryfedorov** [comment]
@aelmahmoudy is this still actual?

**Comment by aelmahmoudy** [comment]
Yes

**Comment by grigoryfedorov** [comment]
This is also not actually a bug. If message was not read in Xabber, notification will appear again for non-read messages, when new messages received for example. 
Xabber do not have indication for unread messages so far, but we plan to add it later. 
May be we will also change notification behavior later.
