### ISSUE TITLE
Sharing to Xabber does not work

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#340]
In Xabber 0.10.x, sharing does not work. If I share a link from a web browser to Xabber, then select the contact, nothing appears in the chat text edit.

**Comment by grigoryfedorov** [comment]
Seems to be fixed in 892510c5861887e58f6f3ba55924ad17848a594a

**Comment by aelmahmoudy** [comment]
Yes indeed. I think this can be closed.
Btw, I rebased #339 on that commit
