### ISSUE TITLE
Implement a tri-state option for contact specific notifications

### ISSUE THREAD

**Issue by andrewnenakhov** [redsolution/xabber-android#344]
Currently there is a checkbox (default is 'off')  display chat message in notifications. This is clearly wrong. It should be three options:
* use **default** settings (i.e. as set in Settings -> Notifications -> Display message)
* **show** message text
* **hide** message text

Two latter options should override possibly set value in general notifications settings.

**Comment by grigoryfedorov** [comment]
Implemented in mentioned commits.
