### ISSUE TITLE
changelog difficult to read & doesn't specify version

### ISSUE THREAD

**Issue by alanthehat** [redsolution/xabber-android#345]
https://github.com/redsolution/xabber-android/blob/master/app/src/main/res/values/change_log.xml 
is in XML so is difficult to read, plus it doesn't have version numbers like 'v9.3.0.f'
This is the changelog referenced by F-Droid & i can't see another after 30 minutes rummaging around on here, the website & google play 
From what I can make out it's not complete or current either.

**Comment by grigoryfedorov** [comment]
@alanthehat we have changelog in our wiki: https://github.com/redsolution/xabber-android/wiki/Xabber-Version-History
I've updated it to last official releases. 
@aelmahmoudy could you please use above link as the change log on F-droid? 
I'm also planning to add develop builds change log to some additional wiki page.

**Comment by alanthehat** [comment]
Thank you, very tidy. And thank you for passing it on to F-Droid 

Am I right to assume that v0.10.10 & v0.10.17 listed on F-Droid are developer versions? 
Should F-Droid have a separate listing for developer versions?

**Comment by grigoryfedorov** [comment]
@alanthehat yes, all 0.10.x versions are developer version for alpha testing. 
First stable release planned to be 0.11
I'm not sure how F-droid actually works, but I think v0.10.10 & v0.10.17 are already marked as not stable. 
If there is an ability to separate stable and developer releases on F-droid within one app, it would be great.

**Comment by alanthehat** [comment]
They have 0.9.30f starred as the recommended version. 
Pointing them at the changelog wiki as you have should keep them appraised if it has an RSS feed or similar notification system. 

Sorry I don't know their system, but there are some apps with 2 listings (I've seen 'normal' & 'bleeding-edge'). 
You can contact them at
team@f-droid.org 
https://gitlab.com/fdroid/fdroiddata/issues

**Comment by aelmahmoudy** [comment]
Changing changelog URL is in awaiting to be merged by F-Droid admins: https://gitlab.com/fdroid/fdroiddata/merge_requests/562

**Comment by alanthehat** [comment]
Problem reported, expanded & tidily resolved on 2 servers for 2 independent apps in 4 days.
I'm impressed! Thank you

**Comment by TameOfGroans** [comment]
Is there no plan to have a Xabber fdroid repo as there is for Chatsecure or other projects?

**Comment by aelmahmoudy** [comment]
@TameOfGroans I think you mean like Guardianproject's FDroid repo ?

**Comment by alanthehat** [comment]
Is there any point to having a separate repo? It's something else that has to be maintained, why do it when somebody else is prepared to do it competently for (what seems to be) free. Plus, it's something else for users to get confused about.
I also like the independent final check that F-Droid provides. 
I've written programs myself, I know how valuable that independent check is.

**Comment by aelmahmoudy** [comment]
@alanthehat what do you mean by the "independent final check" ?

**Comment by alanthehat** [comment]
As I read F-Droid's docs it seems that they compile the app themselves. 
I assume they would report back if it doesn't work as expected. They're certainly competent enough to find & replace sections that don't comply with their rules (generally advertising)
