### ISSUE TITLE
Design new set of dancing android avatars for users with no user picture

### ISSUE THREAD

**Issue by andrewnenakhov** [redsolution/xabber-android#359]
Should be white on transparent .svg avatars. Consider possibility to incorporate user name and surname in avatar to make John Doe appear with 'JD'-labelled avatar.

**Comment by TameOfGroans** [comment]
consider Xposed Framework module "Identiconizer!".

https://f-droid.org/wiki/page/com.germainz.identiconizer

https://github.com/GermainZ/Identiconizer

Since Xabber integrates with contacts [as a contacts provider? ].

**Comment by grigoryfedorov** [comment]
implemented in 4a6c5b6af8291003ad683e31f03a3215e62f5938
