### ISSUE TITLE
Grade of action bar yellow color needs to be changed

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#360]
When the color of the action bar is yellow, the text in the bar (which is white) becomes barely readable. I think the grade of that yellow color needs to be somewhat darkened.
I experienced this with version 0.10.22
Please see the screenshot.

![actionbar](https://cloud.githubusercontent.com/assets/96682/6215664/678833ee-b60b-11e4-95a1-adc280a5e0d1.png)

**Comment by aelmahmoudy** [comment]
The fix in 0.10.23 completely changed the colors.

ie. The  yellow account became red, the green account became cyan.
I notice though that for each account, the old color of the account action bar became assigned to the auto-generated account avatar.

**Comment by grigoryfedorov** [comment]
Sorry, color theme is not final.

**Comment by grigoryfedorov** [comment]
Color scheme changed. Account color could be selected.
