### ISSUE TITLE
Status change when Screen unlock

### ISSUE THREAD

**Issue by Lucky-Lancer** [redsolution/xabber-android#361]
Hi @ all,

i have found an annoying bug.
My status changes automaticlly 15 Minutes after locking the screen.
But when i wake up my Phone, my status changed back to available, even i did not open the Xabber app! 
So if I want to know what time of day we have, my status is back online!

I would prefer that the status only change if i open the app.

I hope everybody can understand my request and my english...
English is not my native language, so sorry for any (spelling) mistakes.

Thanks.

**Comment by TameOfGroans** [comment]
This is a feature. 

settings

connection settings

**Comment by Lucky-Lancer** [comment]
Yes, i know.
There you can set the time until the status changes.
But no matter what i set, even i wake up my phone, my Status is back online/available.
This is very sad.

I'd like to change the status back to online/abailable only if i enter the app.

**Comment by andrewnenakhov** [comment]
That's not how it should work. If we do it like you purpose, we should also change status to 'away' once you switch away from it. Presence is designed to show availability of a contact. If you're holding an unlocked phone with xabber running you are clearly ready to receive messages. If you don't want to or are busy, you might set status that says exactly that.
