### ISSUE TITLE
URLs in chat window are not clickable

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#362]
URLs in chat window/history are not clickable, so when the other party sends me a URL, I cannot click it to visit the webpage.

**Comment by lostfictions** [comment]
I'm experiencing this problem as well.

**Comment by aelmahmoudy** [comment]
I noticed that I need to tap the URL several times to get it opened

**Comment by TameOfGroans** [comment]
Is the message comprised of URI? or is the URI part of additional information in a message?  Does the addresses have a protocol prefix?

**Comment by aelmahmoudy** [comment]
Some messages are exclusively the URIs, some messages contain some text & URIs.

The URIs do have a protocol prefix.

**Comment by aelmahmoudy** [comment]
Since a simple tap now immediately opens the Quote/Copy/Remove from history submenu, it became completely impossible to open the URLs (no matter how many times I tap the URL)

**Comment by grigoryfedorov** [comment]
Should be fixed in f3027a3af4128a92da417b1e4f9817432c275f70

**Comment by aelmahmoudy** [comment]
Splendid ! Thanks...
