### ISSUE TITLE
crash 0.10.23

### ISSUE THREAD

**Issue by nomwerp** [redsolution/xabber-android#364]
crashes when starting/opening conversation , no issues with 0.10.1x versions

could be "No permission to prevent power key"?

```I/dalvikvm( 6702): Could not find method android.view.Window.setStatusBarColor, referenced from method com.xabber.android.ui.ChatViewer.updateActionBar W/dalvikvm( 6702): VFY: unable to resolve virtual method 11769: Landroid/view/Window;.setStatusBarColor (I)V D/dalvikvm( 6702): VFY: replacing opcode 0x6e at 0x0032 I/dalvikvm( 6702): Could not find method android.view.Window.getStatusBarColor, referenced from method com.xabber.android.ui.ChatViewer.onCreate W/dalvikvm( 6702): VFY: unable to resolve virtual method 11766: Landroid/view/Window;.getStatusBarColor ()I D/dalvikvm( 6702): VFY: replacing opcode 0x6e at 0x0065 I/dalvikvm( 6702): Could not find method android.view.Window.setStatusBarColor, referenced from method com.xabber.android.ui.ChatViewer.onPageSelected W/dalvikvm( 6702): VFY: unable to resolve virtual method 11769: Landroid/view/Window;.setStatusBarColor (I)V D/dalvikvm( 6702): VFY: replacing opcode 0x6e at 0x002f D/AndroidRuntime( 6702): Shutting down VM W/dalvikvm( 6702): threadid=1: thread exiting with uncaught exception (group=0x415a8ce0) E/AndroidRuntime( 6702): FATAL EXCEPTION: main E/AndroidRuntime( 6702): Process: com.xabber.androiddev, PID: 6702 E/AndroidRuntime( 6702): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xabber.androiddev/com.xabber.android.ui.ChatViewer}: java.lang.SecurityException: No permission to prevent power key: Neither user 10065 nor current process has android.permission.PREVENT_POWER_KEY. E/AndroidRuntime( 6702): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212) E/AndroidRuntime( 6702): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271) E/AndroidRuntime( 6702): at android.app.ActivityThread.access$800(ActivityThread.java:144) E/AndroidRuntime( 6702): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205) E/AndroidRuntime( 6702): at android.os.Handler.dispatchMessage(Handler.java:102) E/AndroidRuntime( 6702): at android.os.Looper.loop(Looper.java:136) E/AndroidRuntime( 6702): at android.app.ActivityThread.main(ActivityThread.java:5146) E/AndroidRuntime( 6702): at java.lang.reflect.Method.invokeNative(Native Method) E/AndroidRuntime( 6702): at java.lang.reflect.Method.invoke(Method.java:515) E/AndroidRuntime( 6702): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) E/AndroidRuntime( 6702): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566) E/AndroidRuntime( 6702): at dalvik.system.NativeStart.main(Native Method) E/AndroidRuntime( 6702): Caused by: java.lang.SecurityException: No permission to prevent power key: Neither user 10065 nor current process has android.permission.PREVENT_POWER_KEY. E/AndroidRuntime( 6702): at android.app.ContextImpl.enforce(ContextImpl.java:1749) E/AndroidRuntime( 6702): at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1778) E/AndroidRuntime( 6702): at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:572) E/AndroidRuntime( 6702): at android.view.Window.setFlags(Window.java:749) E/AndroidRuntime( 6702): at android.view.Window.addFlags(Window.java:709) E/AndroidRuntime( 6702): at com.xabber.android.ui.ChatViewer.onCreate(ChatViewer.java:139) E/AndroidRuntime( 6702): at android.app.Activity.performCreate(Activity.java:5231) E/AndroidRuntime( 6702): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) E/AndroidRuntime( 6702): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169) E/AndroidRuntime( 6702): ... 11 more W/ActivityManager( 583): Force finishing activity com.xabber.androiddev/com.xabber.android.ui.ChatViewer I/WindowManager( 583): Screenshot max retries 4 of Token{41cda500 ActivityRecord{41dca188 u0 com.xabber.androiddev/com.xabber.android.ui.ChatViewer t33 f}} appWin=Window{41c8eec0 u0 Starting com.xabber.androiddev} drawState=4 W/WindowManager( 583): Screenshot failure taking screenshot for (1080x1920) to layer 21080 W/ActivityManager( 583): Activity pause timeout for ActivityRecord{41dca188 u0 com.xabber.androiddev/com.xabber.android.ui.ChatViewer t33 f} I/Timeline( 897): Timeline: Activity_idle id: android.os.BinderProxy@419d9eb0 time:13051528 I/Timeline( 583): Timeline: Activity_windows_visible id: ActivityRecord{41f10050 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:13051914 I/Process ( 6702): Sending signal. PID: 6702 SIG: 9 W/InputMethodManagerService( 583): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41e4bb08 attribute=null, token = android.os.BinderProxy@41e0d800 I/ActivityManager( 583): Process com.xabber.androiddev (pid 6702) has died. I/ActivityManager( 583): START u0 {act=com.android.systemui.recent.action.TOGGLE_RECENTS flg=0x10800000 cmp=com.android.systemui/.recent.RecentsActivity} from pid 707 W/InputMethodManagerService( 583): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41cb5788 (uid=10016 pid=897) I/Timeline( 707): Timeline: Activity_idle id: android.os.BinderProxy@42207398 time:13055547 I/Timeline( 583): Timeline: Activity_windows_visible id: ActivityRecord{41b97a10 u0 com.android.systemui/.recent.RecentsActivity t19} time:13055817 I/InputReader( 583): Reconfiguring input devices. changes=0x00000004 I/InputReader( 583): Device reconfigured: id=19, name='sec_touchscreen', size 1080x1920, orientation 1, mode 1, display id 0 I/ActivityManager( 583): Config changes=480 {0.85 238mcc20mnc en_US ldltr sw360dp w640dp h335dp 480dpi nrml long land finger -keyb/v/h -nav/h s.40 themeResource=null} I/InputReader( 583): Reconfiguring input devices. changes=0x00000004```

**Comment by grigoryfedorov** [comment]
Hi. 
What is you Android version?
Are you using "Prevent sleep mode" option?

**Comment by nomwerp** [comment]
Hi, this is 4.4.4 . toggling prevent sleep mode doesn't seem to make any difference.
On Feb 20, 2015 6:27 AM, Grigory Fedorov <notifications@github.com> wrote:Hi. 
What is you Android version?
Are you using "Prevent sleep mode" option?

**Comment by grigoryfedorov** [comment]
So far I can not reproduce your issue. 
It looks strange for me now. 
Are you using stock Android or some Cyanogenmod, etc? What is your phone model?
May be you have some app, related to power button?

**Comment by dstolpmann** [comment]
I have the same Issue!

I am using Xabber 0.10.23 from F-Droid on an OnePlus One with CyanogenMod 11S (stock).

**Comment by nomwerp** [comment]
I'm using cm11 nightly on jactivelte
On Feb 20, 2015 3:36 PM, dstolpmann <notifications@github.com> wrote:I have the same Issue!

I am using Xabber 0.10.23 from F-Droid on an OnePlus One with CyanogenMod 11S (stock).

**Comment by nomwerp** [comment]
looks like cm issue,  might be related to this:
http://review.cyanogenmod.org/#/c/59931/2/core/res/AndroidManifest.xml

**Comment by dstolpmann** [comment]
I have also tested it on CyanogenMod 12 and everything works like expected. Looks like it only affects CM11.

**Comment by nomwerp** [comment]
@grigoryfedorov can you think of any changes recently that could have triggered this? a couple of versions ago I didn't have any issues.

**Comment by roadrunner2** [comment]
This problem was introduced in commit 42dca0e738fbdd152eee22f979e3807050a308df, and is indeed CyanogenMod specific. It stems from the fact that CyanogenMod defined a flag of their own, 'PREVENT_POWER_KEY', with a value that clashes with the new 'FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS' flag in Lolipop. The relevant definitions are:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS
https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/java/android/view/WindowManager.java#L919

CyanogenMod 12 fixes this by using a different value for their flag.

One possible workaround (besides folks modifying and building their own CyanogenMod) might be to check the current version of Android and only set that flag if running on API level >= 21, something along the lines of
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
}
```

**Comment by nomwerp** [comment]
Thanks for the great explanation!

**Comment by grigoryfedorov** [comment]
Thank you all, guys!
Actually, I added Android version check for this flag, but after 0.10.23 version, sorry. 
So I've just committed b273a762cf89cac486f117cc90c46cb4394de0b6 version 0.10.23a, which should fix this crash.
Btw, Xabber Dev was banned on Google Play a few days ago, and for now we don't really know what to do with our alpha test. 
Hope you're using F-droid..

**Comment by nomwerp** [comment]
Thank you!
 
yes F-droid here :)

**Comment by nomwerp** [comment]
okay got 23a from f-droid now and can confirm it is fixed.

**Comment by nomwerp** [comment]
okay got 23a from f-droid now and can confirm it is fixed.
