### ISSUE TITLE
Keyboard behavior on swipe chat

### ISSUE THREAD

**Issue by andrewnenakhov** [redsolution/xabber-android#367]
Current build has bad behavior for chat swiping:
if you start typing a message in one chat, then swipe to another, you see that chat with opened keyboard but input field gets no focus. 

This happens even with recent chats tab.

Correct solution to this issue would be to keep separate keyboard/ inputfield state for each active chat. So, if we swipe to chat that didn't have keyboard open, we shouldn't open chat there. If we typed some text, didn't finish it, swiped, then got back - we should be able to resume from the same place where we left.

(it could all be very different on tablets, but we'll get to it later)

**Comment by grigoryfedorov** [comment]
Keyboard is always hidden when entering new chat window (or scroll to another chat).
