### ISSUE TITLE
Some Xabber info messages are in Russian !

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#369]
In the alpha versions, some info messages get printed in Russian, although the locale of my device in English.

The attached image shows the message displayed when I sent a call attention to someone I am chatting with.
![xabber-russian](https://cloud.githubusercontent.com/assets/96682/6353425/d6b70a3c-bc51-11e4-9743-85518a706e62.jpg)

**Comment by grigoryfedorov** [comment]
Fixed in 82cbcb891224f58e2eb2c5f32ad1295d4936923e
Thank you!

**Comment by aelmahmoudy** [comment]
Thanks.
