### ISSUE TITLE
Xabber info messages are empty !

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#370]
Xabber info messages (like OTR related info, call attention,...) are empty, I found that this commit: https://github.com/redsolution/xabber-android/commit/92c39b279ad35e5cc7fa1b0f171ced43405b1349 is the cause of this problem. Although I don't understand yet which line of code caused this.

**Comment by grigoryfedorov** [comment]
Thank you!
I've found the bug already.

**Comment by grigoryfedorov** [comment]
Fixed in 08d03ebbacf518d00cdfe55cc57d55564694abde

**Comment by aelmahmoudy** [comment]
Thanks.
