### ISSUE TITLE
OTR submenu barely visible in new light theme

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#372]
As mentioned in https://github.com/redsolution/xabber-android/commit/14e17b78fbdc7eb854fcfbe9703cb4585e75a500, in the OTR submenu, both foreground & background have a light color making the menu items barely visible.is barely visible.
I got this issue on two devices:
1) Custom Android OS: OMNI 4.4.4
Phone: N7100 (Galaxy NoteII)

2) Custom Android OS: NightOwl (based on CM12) 5.0.3
Phone: N7000 (Galaxy Note)

Here's the screenshot:
![otr_encryption](https://cloud.githubusercontent.com/assets/96682/6409014/25685b48-be66-11e4-8cba-f3e5788bf77f.jpg)

The issue is only with this submenu.

**Comment by aelmahmoudy** [comment]
This issue also happens on a Samsung Tab3 with stock Android version 4.4.2

**Comment by aelmahmoudy** [comment]
@grigoryfedorov I think I understand why you don't see the issue. The issue happens when I use the phone's menu button to access the OTR encryption submenu.
Yet if I use the dropdown menu button (the 3 dots in the action bar), the OTR submenu is good indeed !

**Comment by grigoryfedorov** [comment]
@aelmahmoudy yes, I reproduces issue on a Samsung device. Thank you.

**Comment by aelmahmoudy** [comment]
Hello, since the upgrade to SDK version 22, the situation became worse:
1) The OTR submenu became hindered by the main chat menu (ie. click on OTR encryption menu item does not close the main chat menu !!!)
2) The theme of the main menu is also not good.

![menu](https://cloud.githubusercontent.com/assets/96682/6712687/93a88fe4-cd96-11e4-9461-807080b8c374.png)

Note, that this is only when the phone's menu button is used. The menu displayed when using the 3-dot menu button in the action bar is still very good.

**Comment by aelmahmoudy** [comment]
Since the upgrade to SDK 22, the situation became worse:
1) The OTR submenu gets hindered by the main chat menu (ie. clicking the OTR encryption menu item doesn't close the main chat menu !)
2) Now even the main menu subtheme isn't clear (white foreground on light grey background)

![menu](https://cloud.githubusercontent.com/assets/96682/6712839/6f39497c-cd97-11e4-857c-79de787018f2.png)

Note, that these problems are still only happening when using phone's menu button.
The menus displayed as a result of using the 3-dot menu button in the action bar look very good.

Seems that the problem might be in the SDK itself, ie. Google is dropping support for phone's menu button.

**Comment by kr428** [comment]
Am experiencing the same on the latest build found in f-droid repositories; the main menu and the menu in chat are barely usable, plus the background of chat window sometimes seems to "blink" between grey and the background color used in the chat contact icon (blue, green, ...).

**Comment by aelmahmoudy** [comment]
Fixed
