### ISSUE TITLE
Select all/cut/copy/paste buttons are invisible !

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#379]
This problem only appeared with the new feature/expanding_toolbar branch.
Note: The buttons supposed to appear in the white area above the (red) chat title:

![select_cut_copy_paste](https://cloud.githubusercontent.com/assets/96682/6802811/f895cb70-d23b-11e4-8611-3ca3bf082cac.png)

**Comment by grigoryfedorov** [comment]
Should be fixed in 946308f826bc820adb937b083c40ca2c5c20ef9e

**Comment by aelmahmoudy** [comment]
Splendid ! Thanks...
