### ISSUE TITLE
SSL handshake problem with lollipop

### ISSUE THREAD

**Issue by boistordu** [redsolution/xabber-android#382]
Hi, as stated in the subject I have a problem with one of my jabber server which i am affiliated to.
consortium-horizon.com if you want to know. 

I don't have any logs but you can try on your own devices with lollipop and you will see that it does'nt work.

here are the statement of the bugs : 
- Bug 1: https://code.google.com/p/android/issues/detail?id=103251
- Bug2 (avec Jetty!): https://code.google.com/p/android/issues/detail?id=93740
- Fix for android (merged in master but no released): https://android-review.googlesource.com/#/c/122080/
- Workaround pour Jetty: https://gist.github.com/tavianator/96e9daab0fd1a45f11f2

**Comment by andrewnenakhov** [comment]
I don't know what to make of this, so...
