### ISSUE TITLE
File transfer

### ISSUE THREAD

**Issue by haider-incubasys** [redsolution/xabber-android#387]
I cannot find anywhere how to send or receiver files between two xabber (XMPP) clients.
Can Anyone help me to integrate it ?

**Comment by aelmahmoudy** [comment]
It is not implemented in the GUI yet. Although the XMPP library that Xabber uses, does support the feature.
Have a look at: https://github.com/redsolution/xabber-android/tree/master/app/src/main/java/org/jivesoftware/smackx/filetransfer

**Comment by haider-incubasys** [comment]
I wrote my own app that sends and receives files through xmpp
The problem is it works ok while sending/receiving file from computer server to client android device.But when i try to do same on two android device the file is neither received nor send.

**Comment by moshpirit** [comment]
I hope it will use jingle instead of legacy. (Or even better: both)

**Comment by tanty** [comment]
Shouldn't this be closed as duplicate from #23 ?

**Comment by andrewnenakhov** [comment]
Duplicate #23
