### ISSUE TITLE
battery is very hot

### ISSUE THREAD

**Issue by vasyapupkin123456** [redsolution/xabber-android#390]
when I started xabber and it opened the conference and active chats with people, but I unplugged the phone online (gprs) and left xabber included, then in the morning I wake up, take up your phone and the phone battery is very hot. Answer me, if you read my message pls.

**Comment by moshpirit** [comment]
I've noticed that Xabber consumes 80+ MiB of RAM. Using the last version on F-Droid: 1.0.21
