### ISSUE TITLE
Messages don't show up

### ISSUE THREAD

**Issue by c143** [redsolution/xabber-android#391]
Hey
I had a [problem with a client](https://github.com/jcbrand/converse.js/issues/353#issuecomment-90523050) and an other user told me, that he had the same problem with your client.

Xabber doesn't show messages, if the ID generated by the client isn't unique. The jabber client on lima-city is fixed now and uses the timestamp as ID. But other Clients like Pidgin can show the messages, no matter what the ID is. And Xabber shows them even, if there is no ID at all. You might want to fix that.

```
#Pidgin
id='purple37c0a934'

#jabber.lima-city.de
id='sess_1'
```

**Comment by andrewnenakhov** [comment]
@Str4tocaster Xabber should disconnect if it sees other devices with identical resource ids.

**Comment by labdsf** [comment]
For me Xabber (from Google Play, 2.0.2, haven't tested Xabber Beta) doesn't show messages without ID in MUC. SleekXMPP generates such messages so instead of `send_message` I have to `make_message`, add unique ID and `send()` it manually.

**Comment by zaughon** [comment]
I'm experiencing the same issue. Messages sent from a bot using ErrBot isn't showing up on Xabber, but is showing fine for other accounts in the room, using Pidgin on Windows. 
I havn't tested `make_message` yet, but i'll give it a go (if i can figure out how to use it with ErrBot) :)
