### ISSUE TITLE
UI: Chat viewer back button closes app

### ISSUE THREAD

**Issue by tgrrr** [redsolution/xabber-android#394]
Big fan. Don't write Java unfortunately. 

If I click back from the chat view, it closes the app. Would be great if it could link to the chat list instead.

**Comment by andrewnenakhov** [comment]
@tgrrr Is it still an issue? version in april was in a very early alpha.

**Comment by tgrrr** [comment]
Yes, it is still an issue in 0.9.30f (current in app store)
