### ISSUE TITLE
Tor network support

### ISSUE THREAD

**Issue by artur1702** [redsolution/xabber-android#395]
Xabber can't connect to the server in the Tor network. (server address like xxxxxxxx.onion)

**Comment by aelmahmoudy** [comment]
I tried with Orbot proxy type & with SOCKS5 proxy type, and indeed I can verify this issue. Here's the relevant logcat:
```
I/com.xabber.android.data.connection.ConnectionThread@43b6b888(20701): Resolve xxxxxxxxxxxxx.onion:5222
W/System.err(20701): lookup xxxxxxxxxx.onion. A
W/System.err(20701): NXDOMAIN
I/com.xabber.android.data.connection.DNSManager@41d927c8(20701): Update address for xxxxxxxxxxx.onion:
I/com.xabber.android.data.connection.DNSManager@41d927c8(20701): null
I/com.xabber.android.data.connection.DNSManager@41d927c8(20701): Update address for xxxxxxxxxxx.onion:
I/com.xabber.android.data.connection.DNSManager@41d927c8(20701): null
```

**Comment by artur1702** [comment]
It's a bug or support for the servers in the TOR network is not implemented yet? It is very necessary to me.

**Comment by aelmahmoudy** [comment]
Not sure yet. I am planning to look at it when I got time. But as a workaround, if your device is rooted, you can set Orbot to transparent proxy the Xabber app.

**Comment by artur1702** [comment]
I checked already with transparent proxy. Unfortunately, does not work too. I'll be waiting for news. Thanks

**Comment by aelmahmoudy** [comment]
@a-iv @grigoryfedorov as a side note: why is DNSManager using Address.getAllByName (which according to your code comments does not support AAAA IPv6 addresses) while Android does provide InetAddress.getAllByName which supports both IPv4 & IPv6.

**Comment by aelmahmoudy** [comment]
@artur1702 wierd, could you give me the output of this command on your device (needs to be run as root):
iptables -t nat -L | grep domain

**Comment by artur1702** [comment]
The command does not return anything.

**Comment by aelmahmoudy** [comment]
@artur1702 how about: iptables -t nat -L | grep 5400

**Comment by artur1702** [comment]
does not return anything too.

**Comment by aelmahmoudy** [comment]
@artur1702 hmmm, how about: iptables -t nat -L

**Comment by artur1702** [comment]
I reboot the phone.
Now I have:
REDIRECT udp -- anywhere anywhere udp udp:domain redir ports 5400

**Comment by artur1702** [comment]
made a mistake. correct is:
REDIRECT udp -- anywhere anywhere udp dpt:domain redir ports 5400

**Comment by aelmahmoudy** [comment]
@artur1702 great, try Xabber now with .onion address

**Comment by artur1702** [comment]
Does not work. I checked with ChatSecure and this works without a problem.

**Comment by aelmahmoudy** [comment]
Works with me here.

**Comment by artur1702** [comment]
Try to install it on the new phone. Maybe it's my phone is the problem.

**Comment by aelmahmoudy** [comment]
I made a change that shouldn't require Orbot's transparent proxy. Later I will commit & submit a pull request.

**Comment by aelmahmoudy** [comment]
@artur1702 with this branch https://github.com/aelmahmoudy/xabber-android/tree/socks_remote_dns, you shouldn't need to use Orbot's transparent proxy. That would be useful for devices that are not rooted.

**Comment by aelmahmoudy** [comment]
@a-iv @grigoryfedorov @andrewnenakhov the above mentioned commit has the following issues:
* It assumes that if the user is using a SOCKS5 proxy, then he would always want to remotely resolve the DNS using that proxy (ie. not using the DNS configured for the device), I'm not sure if this is always a correct assumption.
* This still leaks the SRV DNS request to the DNS configured for the device. There is no solution for that one, except that the user would use something like Orbot's transparent proxy feature, and this requires the device to be rooted.

**Comment by artur1702** [comment]
@aelmahmoudy thanks for the patch, but i can't build xabber.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module otr4j : Configuration with name 'default' not found.

What im doing wrong?

**Comment by aelmahmoudy** [comment]
@artur1702 try:
git submodule init
git submodule update

**Comment by artur1702** [comment]
@aelmahmoudy Thank you. Now everything works fine.

**Comment by aelmahmoudy** [comment]
I think this could be closed now.

**Comment by aelmahmoudy** [comment]
@grigoryfedorov shouldn't this be closed already ?
