### ISSUE TITLE
Xabber and Hangouts chat - howto?

### ISSUE THREAD

**Issue by pejakm** [redsolution/xabber-android#401]
How do I connect to my Google/GTalk/Hangouts account? Google requires authentication of all apps, but Xabber doesn't offer any way (at least I can't see it) of doing that.

Whoops, sorry: dev version installed, 0.10.62

**Comment by andrewnenakhov** [comment]
it works for us, with all standard settings. Take note that Hangouts are only marginally compatible with XMPP - messages sent to you while you are offline will never be delivered to Xabber (or Gajim/Pidgin/etc). Also take note that Github is no support forum.

**Comment by pejakm** [comment]
If anyone cares, here's what was the issue: I had two-factor authentication enabled. All I need to do was to generate special password for apps in Google account settings. It works now, Xabber rocks!

**Comment by andrewnenakhov** [comment]
Well, it did work from the very start of 2-factor authentification. It's quite tricky to setup though, user interface is far from obvious. But we still believe that you should move to true xmpp service from hangouts before they'll cut out remaining xmpp compatibility.

**Comment by ldetmer** [comment]
@pejakm I'm running into the same issue - it won't let me add a gchat account unless that user has "Allow less secure apps: ON".  Do you know if you are using oauth to authenticate?
