### ISSUE TITLE
Xabber scrolls down by itself while looking in old chat history

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#410]
If I scroll up to see old chat history, Xabber would bring scroll down by itself without any clear reason.
This also happens if I click on a link in the chat history.

**Comment by marix11** [comment]
confirm this issue

**Comment by grigoryfedorov** [comment]
Should be fixed in ec6fd8d3b9692111be5e5ae98683b4045efd3ae4

**Comment by aelmahmoudy** [comment]
Yes, I tested it yesterday. Thanks.
