### ISSUE TITLE
cconfigure/disable chat background option

### ISSUE THREAD

**Issue by rigid** [redsolution/xabber-android#415]
while i like the new UI and finding the background gfx in the chat dialog really neat, it is quite annoying for visually impaired users.
An option to change or disable the background image would be awesome.

**Comment by marix11** [comment]
Yes that would help. Pgp messages not recognized. From beta versions even sent wrong format

**Comment by rigid** [comment]
i just found out that on another device, the chat background image is MUCH more subtle (very light grey, while on mine it's dark grey). The only reason I can think of, is that mine uses a higher color depth (retina display?) or other color system settings. If there already is an option to disable the bg image, I couldn't find it :-(

@marix11 open another issue for the PGP thing please.

**Comment by slmingol** [comment]
I too recently received the update to 1.0.30 and overall I like the new look, but would really like to swap the background out with just a solid color. I find it difficult to read messages. In my chat windows the background is a subtle white/gray image of all these little drawings. Is there a way to get rid of that?

**Comment by write-only** [comment]
@slmingol You can disable the background in Settings -> Chat

**Comment by slmingol** [comment]
@write-only - thanks, didn't see that option down there. Confirming that disables the background, works for me.
