### ISSUE TITLE
Crash when I enable notifications for conferences

### ISSUE THREAD

**Issue by stefannagy** [redsolution/xabber-android#418]
I'm using Xabber 1.0.2 from F-Droid on Android 4.4.4 (CyanogenMod 11 M12). When I enable notifications for conferences (Settings ->  Notifications -> Notification settings -> Chats and conferences) xabber crashes when a message appears in one of the active conferences.

After that, Xabber tries to restart but crashes again immediately. And so on.

I can also reproduce this behaviour with Xabber 0.10.62 from F-Droid. Version 0.9.30f seems to be the last one not affected by this bug.

**Comment by moshpirit** [comment]
I enabled it but it doesn't restart Xabber. In the other hand, I can't open it again because it crashes all the time (see #419) maybe is the same bug, if so, please, let me know in order to close my issue).

**Comment by stefannagy** [comment]
@moshpirit Sorry, my description wasn't correct. When I enable notifications for conferences and there's an incoming message in one of my conferences Xabber crashes two times – I get two error messages saying that Xabber was terminated (my language is German so the error message says "Xabber Beta wurde beendet"), I have to confirm by hitting "OK".

After that I have an empty light bulb icon on top of the screen. When I whipe down the status message it says "1 of 1 account connecting". When I touch on this message, Xabber tries to open up and crashes two times again.

I can't open Xabber again since it will always crash. I have to reinstall Xabber to use it again.

**Comment by grigoryfedorov** [comment]
Should be fixed dc5e534215b385f7408580acf90060dcedb7f87f
Thanks!

**Comment by stefannagy** [comment]
Sorry, I had to wait until Xabber 1.0.3 made it into the F-Droid repository. I can't reproduce this bug in Xabber 1.0.3 – so now I can confirm it's fixed. Thanks so much!!
