### ISSUE TITLE
Xabber 1.0.2 crashes when it starts 

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#419]
Android 4.3. Maybe is because my configuration, but I don't know why crashes now: 2 accounts, one MUC open, 2 more conversations. Maybe is because I have MUC notifications enabled. (see #418)

**Comment by grigoryfedorov** [comment]
Check 1.0.3+ please.

**Comment by moshpirit** [comment]
It's still not on F-Droid

**Comment by andrewnenakhov** [comment]
we do not maintain f-droid repository. If you'll find out know who is responsibe for it, let us know too.

**Comment by moshpirit** [comment]
Ok, in 1.0.3 looks like is fixed, thank you!

**Comment by moshpirit** [comment]
@andrewnenakhov [here](https://f-droid.org/about/) you can find these contacts:

- Email: team@f-droid.org
- Pump.io: fdroid@identi.ca
- Contribute: https://f-droid.org/contribute
