### ISSUE TITLE
compiling instructions

### ISSUE THREAD

**Issue by josinalvo** [redsolution/xabber-android#421]
Hey,

Would you mind providing some compiling instructions?

I never worked with an android studio project, and have been unable to import it.
Also, running the gradlew script does not seem to work (because it requires otr4j and that dir is empty)

What version of otr4j should I get?
(also, complete compiling instructions would be much appreciated)

thanks!

**Comment by grigoryfedorov** [comment]
You should just use git submodule command. See updated readme file: 
65f6084f520e19b55c25316d33f2375122408512

**Comment by josinalvo** [comment]
Thanks!
(I had other problems with Android Studio, but that was the only one with Xabber)

**Comment by josinalvo** [comment]
Btw, in the compile instructions, I'd add a last line:
"import to android studio as a Gradle project"
(and, if it is possible to compile from the CLI, the correct build target as well)
