### ISSUE TITLE
Spaces removed

### ISSUE THREAD

**Issue by marix11** [redsolution/xabber-android#422]
Spaces are auto removed in sent messages. Its big problem if you send copied text, large articles

**Comment by grigoryfedorov** [comment]
Should be fixed in 7ec1518c812945c28529135e754c15da032feef1

**Comment by marix11** [comment]
Thanks. Please update f-droid i will test gladly

**Comment by grigoryfedorov** [comment]
Version 1.0.5 is on F-droid
