### ISSUE TITLE
“Debug log” option greyed out

### ISSUE THREAD

**Issue by liotier** [redsolution/xabber-android#424]
Using Xabber Beta 1.0.2 from F-Droid, on Cyanogenmod 11-20141112-SNAPSHOT-M12-jflte (Android 4.4.4), I want to investigate an authorization error I encounter with my Ejabberd 14.07-4 (maybe the subject of another issue - when I manage to get the debug logs...)

I go to Menu → "Settings → “Debug settings” and find that "Debug log" is greyed out - so I cannot activate this option.

Is there anything required and that I might have forgotten to make this option available ? Thanks to any information...

**Comment by grigoryfedorov** [comment]
It is actually not a bug. Debug log option is only available if application build with debuggable flag. It is not available on release builds. 
Simplest way, I think is to build application yourself.
I made with option totally invisible, if unavailable.

**Comment by liotier** [comment]
Thanks, indeed total invisibility is better as it does not suggest that the option might be available.
