### ISSUE TITLE
Please, update the website

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#426]
The website is still showing the old design and probably there's more XEPs in Xabber.

**Offtopic**: when do you expect that [file transfer](https://xmpp.org/extensions/xep-0234.html) could be implemented?

**Comment by grigoryfedorov** [comment]
Both xabber.org and xabber.com updated to new design.
XEP list would be updated soon.
File transfer may be in distant future.

**Comment by moshpirit** [comment]
Thank you! You're great!!

**Comment by moshpirit** [comment]
Seriously, what a difference!! :+1:
