### ISSUE TITLE
"Quote message" quotes the wrong chat

### ISSUE THREAD

**Issue by vivia** [redsolution/xabber-android#428]
Steps to reproduce:
Open two chats.
Go to the second one.
Tap one message and select "Quote message" from the pop-up menu.
Nothing happens in that window.
Swipe to the first chat.
The last message from the first chat is quoted instead.

**Comment by grigoryfedorov** [comment]
Should be fixed in 877c729587e7fbc935ca644f70bc0fa2f8ce743e
