### ISSUE TITLE
send a message to a particular person in a conversation

### ISSUE THREAD

**Issue by call5** [redsolution/xabber-android#430]
Is it be possible to be able to click on the avatar of a person in a conversation to quote her nickname to respond to it and / or talk to this person in particular? it is painful to have to retype the nickname of a person and use for a while having "conversations" I had this behavior and I found it great. thank you

**Comment by grigoryfedorov** [comment]
We found out, that conferences in Xabber were poorly implemented. So we have plans to improve them. Thank you for suggestion!

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
