### ISSUE TITLE
Appbar slides under status bar in certain conditions

### ISSUE THREAD

**Issue by andrewnenakhov** [redsolution/xabber-android#432]
Steps to reproduce (possibly several configured accounts are needed):
1) select 'add conference' option
2) choose one account from dropdown list
3) move focus to nickname field
4) Interface breaks.

Also works:
1) select 'add conference' option
2) move focus to nickname field
3) choose one account from dropdown list 
4) interface breaks

**Comment by grigoryfedorov** [comment]
Was fixed in 27d458ebc7736186899eaec697e2a52299a908ed
@andrewnenakhov check version 1.0.6
