### ISSUE TITLE
Carbon Copy confuses other clients and causes resent messages

### ISSUE THREAD

**Issue by kaindl** [redsolution/xabber-android#437]
The new (and automatically activated) feature for Carbon Copys (XEP-0280) is causing some unexpected trouble...
When Carbon-copy is enabled, I can't predict and control, where the messages from my contacts will be delivered to, It depends on the client AND the server of the contact.
It seems like some clients and servers are confused by the messages like
    `<message from="me@my.server/Xabber" type="chat" to="you@your.server/Whatever" id="1BOWU-36">`
    `<active xmlns="http://jabber.org/protocol/chatstates"/>`
    `</message>`
which causes them to send the messages directly to `me@my.server/Xabber` instead of sending just to bare jid or looking at the Priority (Xabber has -1, PC has 50). But that is just a guess.

The other problem is, if I send a message from Xabber in a chat CCed from the PC, Xabber will resend all messages previosly from the PC to the contact. Some clients seem to notice this, others display them again..

**Comment by moshpirit** [comment]
Maybe it needs MAM (XEP 313)

**Comment by grigoryfedorov** [comment]
@Semenchikus it would be great, if you comment this. Thanks.

**Comment by GOshaSaveiko** [comment]
Maybe there is some problem with time- or chat-sync. If you sent message to contact on PC: "1", then "2", you ll get it on Android like "1","2" as forwarded carbon messages, then send message "3" from android phone. In Android phone message "3" will be BEFORE "1" and "2", and the other contact will receive messages "1" and "2" again like (Offline) messages.
Received messages by contact:
1
2
3
1 (offline)
2 (offline)
Xabber 1.0.30, PC Clients Spark 2.7.4, XMPP-server: ejabberd.

**Comment by bobobo1618** [comment]
I seem to have run into this or something similar as well. My setup:

- Prosody server (mod_mam, carbons enabled)
- Conversations client on phone1
- Conversations client on phone2
- Xabber client on phone1
- Conversations client on phone3, the destination (sole client)

If Xabber is running, messages sent from the other clients, after a few minutes delay, are resent both to the destination and the other clients. It's like it's repeating carbons for some reason.

When Xabber isn't running there are zero problems, even with other XMPP clients (Kaiwa, Monal) connected.

**Comment by andrewnenakhov** [comment]
Looks like no longer an issue.
