### ISSUE TITLE
Vague failed connection errors

### ISSUE THREAD

**Issue by mmcco** [redsolution/xabber-android#442]
When trying to connect to a Jabber server through Tor, Xabber seems to crash Orbot. That's a different, larger issue, though, and one that I want to look into more before reporting.

More generally, it would be nice if failed connections came with more specific information. For example, "proxy refused connection", "domain name resolution failed", "TLS connection failed", "server refused connection", etc. The kinds of things Firefox might tell you.

I think this is reasonably important because many users don't have enough experience to do blind connection diagnostics and will pretty quickly switch to another client if one is mysteriously failing.

Let me know if I'm missing a log somewhere that saves this information. In that case, though, I think it would still be valuable to persistently show the reason for connection failure in the main window.

Thanks for your time.

**Comment by mrmaxg** [comment]
Is there any progress or any more info on this issue?

I use xabber with orbot. When I add an account it instantly says connection error. But when I restart phone (or orbot and xabber apps) then it will connect.

Likewise, if I close xabber or xabber goes offline for any reason... It will not reconnect. I get connection error. I need to close both orbot and xabber and then open them both again. It's frustrating. Does anyone have any fixes or is anyone looking into this issue?
Thanks

**Comment by mrmaxg** [comment]
Sorry to comment again. But I seem to have figured out my issue. It's something to do with orbot auto torifying all my apps. When I disable this in orbot.... Everything connects just fine xabber and of course xabber is set to use orbot and fails to connect when I close orbot. So I don't know if it's an issue with orbot with xabber in the way it communicates with orbot when. Anyway.... Hope it helps somebody

**Comment by marix11** [comment]
I have similar issue when changing connectuon from different wifi/ mobile. When connection change some servers wont reconnect

**Comment by andrewnenakhov** [comment]
Connection issues are now explicit
