### ISSUE TITLE
multiple menus

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#443]
in beta version there are 3 different menus: settings, contact list menu and conversation menu. add to that different menu from phone software button and hidden otr menu otherwise not accessible. confusing. maybe consolidating menus and moving otr to conversation menu would help (i've been looking for otr menu for s long time)

**Comment by grigoryfedorov** [comment]
Oh, I thought we moved OTR menu to more visible and usable place. It was on second level menu, and now it's just near input. 
Menus may be changed in near future, we're still experimenting on UI. 
Thank you.

**Comment by mis2417** [comment]
it's still in the same place on 1.0.9 but i won't be opening it again since you're experimenting. thanks.
