### ISSUE TITLE
beta bugs

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#446]
1."opponent" is a weird name for contact, in other places it is "contact" 
2. contact disconnect results in empty notification (not shown here) 
3. resouce name (ie. "xabber") used in status change notification instead of contact name
4.event with "notify during conversation" option enabled, there is no sound on incoming message when conversation is open/active

(apparently can't upload picture from mobile, sorry) 
http://imgur.com/HzBivFT

**Comment by grigoryfedorov** [comment]
![hzbivft](https://cloud.githubusercontent.com/assets/6428909/7679595/cdd5cbe4-fd77-11e4-910f-a17ef7082f99.png)

**Comment by mis2417** [comment]
none of those were fixed in 1.0.9. 
that's not really a problem, just noticing. 

it would be easier to check if "bug fixes" in release notes was a little more descriptive (ie what bugs)

**Comment by grigoryfedorov** [comment]
Number 2 and 3 should be fixed now. Will be in next version.

**Comment by marix11** [comment]
Please update f-droid. Btw why updates on f-droid are late. Is there any way to download latest betas without google?

**Comment by grigoryfedorov** [comment]
@marix11 f-droid updated by their community, we're not related to them directly.

**Comment by grigoryfedorov** [comment]
@marix11 you can get latest dev builds from this Dropbox folder:
https://www.dropbox.com/sh/40x3y8zdy15j2wl/AABIXCVTPXlpp63eSnRXXZ-na?dl=0
But these builds signed by other signature, than f-droid, so you would have to reinstall app.

**Comment by marix11** [comment]
Thanks a lot

**Comment by grigoryfedorov** [comment]
number 4 fixed in 1.0.11

**Comment by mis2417** [comment]
2 and 3 are confirmed fixed in 1.0.10.
also, thanks for descriptive text in play store.

**Comment by mis2417** [comment]
#4 is confirmed fixed too. 
since #1 is unimportant - closing
