### ISSUE TITLE
typing notification 

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#455]
while writing to contact (me - beta, contact - normal xabber) typing notification shows as normal, but after text is sent and shows up on contacts phone, there is "entered text" notification showing, even though i'm not writing anything. 
i'm not sure if i've explained it clearly, i can try again if you want :-)

**Comment by mis2417** [comment]
also, whole writing notification in beta is weird - can't use other word :-) 
"contact is typing" notification shows up on beta for a very short period of time (like a second, message typed is longer than that), then nothing happens for few seconds (ie contact is "just available"), then message appears. 
notification sent to contact i've described above.

i have a feeling that typing notification is faster than the message and delay comes from message parsing on receiving (my) side, but it's only a feeling.

**Comment by mis2417** [comment]
i don't know whether it's someting you changed, or someting on my side, but in 1.0.11 it's ok.

**Comment by mis2417** [comment]
first part ("entered text") still exists. maybe it's a problem when chatting across versions? 

sorry about premature bug closing.

**Comment by grigoryfedorov** [comment]
"entered text" notification appeared every time you leave focus from text view (chat swipe, home button, etc), even if you were not typing at the moment. 
I disabled this notification.

**Comment by mis2417** [comment]
yes (i tend to do that a lot since android doesn't offer decent multiwindow) i enter text, send, go back to home screen. imho "entered text" shouldn't appear when no text is entered. 

anyway, it's better after the update. thank you.
