### ISSUE TITLE
inconsistent menu behaviour

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#456]
when i enter conversation in beta by clicking its notification, the back button exits to home screen, in previous version it was exit-to-contact-list. now it exits even if arrow in left upper corner is pressed. 

if conversation is entered by clicking main notification or from contact list, back button (which is fine) returns to main screen, but the arrow too (which is odd) as it suggests retutning to contact list. 

also, phone menu button works on contact list, but not in the conversation window.

**Comment by grigoryfedorov** [comment]
> now it exits even if arrow in left upper corner is pressed.
Yes, it's not good

> if conversation is entered by clicking main notification or from contact list, back button (which is fine) returns to main screen, but the arrow too (which is odd) as it suggests retutning to contact list.
Seems to be ok.

> also, phone menu button works on contact list, but not in the conversation window.
Yes, there are some problems with hardware menu button..

**Comment by mis2417** [comment]
not really fixed:

http://imgur.com/D6iG5ub

**Comment by mis2417** [comment]
perhaps i should clarify. in chat - menu is black text on dark background, in contactlist - menu is white text on dark background. 

i'm using ideal theme dark on cyanogenmod 11

https://play.google.com/store/apps/details?id=com.jaydvl.idealtheme.dark

**Comment by grigoryfedorov** [comment]
@mis2417 you can check fixed of your bugs in version 1.0.12

**Comment by mis2417** [comment]
yes, fixed, thank you.
