### ISSUE TITLE
account used in "Contact info"

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#458]
The V-Card doesn't show which account was used to add the contact, it would be could to show it and not just the colour thing.

**Comment by andrewnenakhov** [comment]
Well we thought that non-colorblind users can surely remember what account has what color. Isn't it so?

**Comment by moshpirit** [comment]
Yes, but people with several accounts can be confused, like non tech people. Even then, I think that including the account is a good idea.

**Comment by andrewnenakhov** [comment]
@moshpirit we'd rather leave it as it is. Sure, it can be troublesome for some users, but we have more important issues to take care of.
