### ISSUE TITLE
unreadable messages received Bug

### ISSUE THREAD

**Issue by lagosazules** [redsolution/xabber-android#471]
Hello, using the new Xabber beta and the stable 0.9.30 on multiple devices
in exclusive OTR required mode , we have notice that exclusive use
between de new betas many times we got "unreadable messages received"
between each other
This happens one way, so one can receive and read and the other not.
Between the old versions and the betas we have no problems at all.
Restarting encryption is not fixing the problem

Thanks for all the good work

**Comment by marix11** [comment]
Must same issue #413. Until fixed all betas unasable using OTR encryption. Very seriuos bug

**Comment by grigoryfedorov** [comment]
@lagosazules please check version 1.0.19 as it become available.

**Comment by lagosazules** [comment]
Great !

**Comment by lagosazules** [comment]
1.0.19 still same problem between the betas only, specialy when restarting one of the phones, we all use the same server, dukgo.com in OTR required mode

**Comment by marix11** [comment]
Confirm this. When restarting phone or when closing xabber offline, another side doesnt notice changed keys and unreadable messages recieved. Restarting conversation doesnt help. The only way to start need both side do stop encryption

**Comment by lagosazules** [comment]
To us it only happens always when restarting phone, just testing it and 
going offline or closing Xabber give no problems at this moment.
Restarting encryption on both phones doesn't help us to fix  unreadable 
messages received.






El 14 de junio de 2015 07:55:26 marix11 <notifications@github.com> escribio:

**Comment by grigoryfedorov** [comment]
@lagosazules I tried to shut down phone during Xabber running.. Xabber didn't recognized shut down and didn't closed connections, etc. 
Here 7190a9b91772d4216f4edce2e2f00583af692c29 I added correct shutdown for Xabber. Will be available today in next version (1.0.21). Test please.

**Comment by lagosazules** [comment]
Tested for two day's now between devices with 1.0.21 and  also to older 
versions,  rebooted many times on both sides, being off and online, 
changing networks etc.
No any unreadable message anymore, OTR works fine now

Thanks


El 17 de junio de 2015 12:21:33 Grigory Fedorov <notifications@github.com> 
escribio:
