### ISSUE TITLE
Vibration: honor global notification status

### ISSUE THREAD

**Issue by azrdev** [redsolution/xabber-android#473]
Xabber allows me to switch Vibration on new messages on or off. In the Android settings, I can also, globally, set vibration (and other alarm/notification means), e.g. via creating and selecting Profiles.
However, xabber doesn't honor my global settings: If I disable every notification (sound & vibrate) xabber still vibrates, which can be very annoying in quiet environments.

I'm using xabber 1.0.2 from f-droid on an Android 4.1.2 (CyanogenMod)

**Comment by grigoryfedorov** [comment]
@azrdev do you have "Ignore system vibration settings" option turned on?

**Comment by azrdev** [comment]
@grigoryfedorov nope

**Comment by azrdev** [comment]
Ok, the issue apparently was between me and android, not Xabber:
Recently, I stopped using "Profiles" in android, when I discovered I could switch the system to "vibrate" or "silent" mode without using these. This included Xabber, with the expected behaviour.
