### ISSUE TITLE
Migrate translation service to something else

### ISSUE THREAD

**Issue by pejakm** [redsolution/xabber-android#477]
Please consider migrating to some other, free translation service, like transifex.com or even better, crowdin.com. Webtranslateit requires payed account, this is an obstacle for many free software translator organizations and individuals.

**Comment by moshpirit** [comment]
:+1:

**Comment by grigoryfedorov** [comment]
Seems, we've done 
https://crowdin.com/project/xabber

**Comment by moshpirit** [comment]
Thanks! Hope to help as much as I can, that's a great project ;-)

**Comment by grigoryfedorov** [comment]
Thank you too )

**Comment by pejakm** [comment]
Thanks! :)

**Comment by pejakm** [comment]
@grigoryfedorov Could you please add Serbian, too, so I can start translating?

**Comment by grigoryfedorov** [comment]
@pejakm I added several variants, choose right one please)
