### ISSUE TITLE
show message in new line

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#479]
"show message in new line" menu option isn’t really doing anything with new layout..

**Comment by grigoryfedorov** [comment]
Thank you! Option removed.

**Comment by mis2417** [comment]
is there a possibility to tighten the layout a little? old version had a really condensed layout with many messages on screen, new layout, however nice, is a little big, even with smallest font.

**Comment by moshpirit** [comment]
I like how is right now, where would you put the time marks then? :-\

**Comment by mis2417** [comment]
maybe slimmer message popups? or time marks on the side of the message/inside popup?

**Comment by moshpirit** [comment]
Inside the popup could be a good option because it's more visible

**Comment by moshpirit** [comment]
OK, why not both? Inside and on the side of the text?

**Comment by andrewnenakhov** [comment]
we'll think of it a bit later, when we'll get to chat themes.

**Comment by moshpirit** [comment]
OK, but then why closing the issue?

**Comment by andrewnenakhov** [comment]
too many issues are a distraction. we know what we need to do and managing many issues is a pain. I hope you understand.

**Comment by moshpirit** [comment]
OK, yes, I get it
