### ISSUE TITLE
Taskbar icon is still shown even if it's disabled

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#483]
It hide the "Xabber Dev \n 3 of 3 accounts online" message but just momentously 

Android 4.3.

**Comment by susobaco** [comment]
in the same case in cyanogenmod 10.1

**Comment by grigoryfedorov** [comment]
@moshpirit @susobaco please check version 1.0.22

**Comment by moshpirit** [comment]
OK, we'll wait for this release on F-droid

**Comment by moshpirit** [comment]
OK I think it's fixed, thanks!!
