### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#486]
When trying arabic string translations in v1.0.20, I found the following issue:

![xabber-ar](https://cloud.githubusercontent.com/assets/96682/8188219/bec475f8-1454-11e5-87aa-7dd8cd17fc31.png)

The "أنت:" string (which is the translation of "You:") should be to the right of the message.

**Comment by grigoryfedorov** [comment]
53daa1f37548263d2245940cca53cd3114fb1a4f should fix that.

**Comment by grigoryfedorov** [comment]
@aelmahmoudy is it better now?

**Comment by aelmahmoudy** [comment]
yup, that fixed it. Thanks
