### ISSUE TITLE
Messages get lost when connection lost

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#487]
Serious problem, concerning XMPP
1. Use two different devices with Xabber for example.
2. Open chat between each other and send some messages.
3. Disable internet (shut down wi-fi for example) on one of devices.
4. It stays online! Send some messages to device with no internet. 
5. Turn internet on. 
6. Those messages would be never delivered. 

May be it depends on server used. But

**Comment by aelmahmoudy** [comment]
Yes, this problem is also present in classic flavour of Xabber.

I wonder if updating SMACK (which won't be easy) would fix that ?

**Comment by moshpirit** [comment]
Could be solved by implementing MAM? (XEP 313)

**Comment by ashutler** [comment]
This issue is also very noticable when using it on a cell network.  If you happen to send a message to someone who's just gone out of covereage for a few seconds, when they return (to the network) they miss messages.

**Comment by andrewnenakhov** [comment]
@moshpirit was solved by implementing XEP 313 )
