### ISSUE TITLE
Aesthetic changes for settings: font colour and About access 

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#489]
1. The settings categories are too light, maybe a darker colour would be a better option. 
2. Settings could gain a lot of simplicity just including the "About" into the Debug category. Not a big change but it creates a significantly change for us because it looks very much cleaner and simpler IMO.  Remember that we already have an access to this excellent menu by the lateral panel.

BTW, why is not included the "About" information in [Crowin](https://crowdin.com/project/xabber) to be translated?

**Comment by andrewnenakhov** [comment]
Translating too many text is a burden for most translators. And we feel like that those who are really interested in Xabber know english anyway. )
