### ISSUE TITLE
font size configuration for the roster

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#490]
We can change the messages font size, but not the roster one, I don't think that it's difficult to implement (I'm not a developer), but it could be a friendly change to the next version for people with visual deficiency or people who wants just change this font size.

Thanks for your great work!!

**Comment by andrewnenakhov** [comment]
it's actually hard to implement size changes in roster. You can't make interface elements smaller than they currently are, because it would be bad for touch input. Moreover, lots of subtle details in roster are not easily shrinkable no. So, no for now, sorry.
