### ISSUE TITLE
Xabber doesn't show the search and menu buttons when it starts 

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#493]
Steps:

 1. Start Xabber, look at the top bottom, there's only one button: the left panel one.
 2. Minimise Xabber and enter again, now there's 3 buttons: the left panel button, the searcher and the menu button.

Screenshot:
![screenshot_2015-06-30-14-20-34](https://cloud.githubusercontent.com/assets/7888062/8431202/276db1d0-1f38-11e5-838c-577d533cd18a.png)

Android 4.3, Xabber 1.0.22 (F-Droid)

**Comment by moshpirit** [comment]
Android 4.3, Xabber 1.0.22 (F-Droid)

**Comment by grigoryfedorov** [comment]
@moshpirit please check if it fixed in 1.0.23

**Comment by moshpirit** [comment]
OK, I'll do it as soon as it gets released on F-droid!

**Comment by moshpirit** [comment]
Fixed! Thanks!
