### ISSUE TITLE
MUC changes: aesthetic and Vcard access

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#494]
I've been thinking in a few changes for the MUC list:
1. Showing the used account in the MUC
2. Showing the avatars (touching them we can see them in a bigger resolution)
3. Changing the descriptions (touching them we can access to the Vcard)

I draw the points 2 and 3 just on Xabber account for GitHub

![screenshot_2015-06-30-14-20-51](https://cloud.githubusercontent.com/assets/7888062/8431274/94685ac4-1f38-11e5-81ed-a23a3940cb13.png)

Please, excuse my English.

**Comment by andrewnenakhov** [comment]
This was updated quite a bit. Closing anyway, since we're going to replace MUC protocol with new superior group chat protocol.
