### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by Blackhole16** [redsolution/xabber-android#495]
I am working on a PR to integrate an option to disable 'This Room is not Anonymous' messages for each room.

It is working, but trying to add the preference, I have some questions regarding Database Migration of Preference-Tables.
* Which is the current version, so to which version do I need to migrate?
* When and how is migration performed i.e. when is DatabaseManager::onUpgrade called?

Kind Regards,
BH16

**Comment by grigoryfedorov** [comment]
Hi and thanks for your work!

**Comment by Blackhole16** [comment]
Thanks, I'll test it out and if everything works the PR will be coming this WE.
