### ISSUE TITLE
Searcher colour integration

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#496]
It should be white like the others buttons, shouldn't it?

![screenshot_2015-07-02-14-35-08](https://cloud.githubusercontent.com/assets/7888062/8477471/b99be318-20ca-11e5-8180-9b8b587d4cd8.png)

**Comment by andrewnenakhov** [comment]
@grigoryfedorov , possibly a bug, pls check it.

**Comment by aileronajay** [comment]
The text colour in the search can be changed by adding below code to setUpSearchView in ContactList.java. However for changing the associated icon we will need an icon file


int searchPlateId = searchView.getContext().getResources().getIdentifier("android:id/search_plate", null, null);
        View searchPlate = searchView.findViewById(searchPlateId);
        int searchTextId = searchPlate.getContext().getResources().getIdentifier("android:id/search_src_text", null, null);
        TextView searchText = (TextView) searchPlate.findViewById(searchTextId);
        if (searchText!=null) {
            searchText.setTextColor(Color.WHITE);
            searchText.setHintTextColor(Color.WHITE);
        }

**Comment by aileronajay** [comment]
Though in SearchView.java, we have this code

  if (a.hasValueOrEmpty(R.styleable.SearchView_searchHintIcon)) {
            mSearchHintIcon = a.getDrawable(R.styleable.SearchView_searchHintIcon);
        } else {
            mSearchHintIcon = a.getDrawable(R.styleable.SearchView_searchIcon);
        }
so it tries to get value from R.styleable.SearchView_searchHintIcon and R.styleable.SearchView_searchIcon for the icon to use

**Comment by andrewnenakhov** [comment]
@moshpirit looks like it's fixed in latest releses.
