### ISSUE TITLE
Name of the setting is too long for just one line

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#497]
The translation into Spanish requires more than just a line.

[Related information](https://github.com/andstatus/andstatus/issues/187)

![screenshot_2015-07-02-14-31-38](https://cloud.githubusercontent.com/assets/7888062/8477503/f1a7d6c2-20ca-11e5-9a00-1d87ef4b6bc4.png)

**Comment by andrewnenakhov** [comment]
Such things happen with various languages. :( can hardly fix it all
