### ISSUE TITLE
Recent chats menu

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#498]
The actual windows shows a list of the open conversations and a top bar. In this bar, we have 3 items: the "back" button (←), the name of the window (Recent chats) and a button in build process (⚠)

This last button (⚠) could be used for now as a menu with these items:

- Mark all as read
- Close all chats
- Chat settings

**Comment by andrewnenakhov** [comment]
we'll get to this issue when we're done with proper recent chats window.
