### ISSUE TITLE
Contact info access using the avatar and the name in chat

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#499]
Right now, to access to the contact info (the Vcard) from the chat window, we have to open the menu and select Contact info or just pressing the avatar, but not the name of the user. I think that's a waste of a really big space and it should be included into the avatar button to access to the Vcard.

**Comment by andrewnenakhov** [comment]
Access to some functions should better be duplicated. Users know to search for options in menu, so it's ok to leave something there.
