### ISSUE TITLE
Better access to the lateral panel by lateral slide

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#500]
Right now, to access to the [lateral panel](https://crowdin.com/s/73a313d3m493v6a3b307130353039505l4m4o42685536545c6?size=origin) from the roster, we have to click on the biggest button (in the up and left side of the window) or sliding from the left side of the screen. But the used space is too small, it shoud use the entire screen in order to have access to the left panel even if we slide the finger in the centre of the screen just like we do [in the chat windows](http://www.xabber.com/media/upload/attachment/cache/upload/attachment/source/screen-quick-chat-switching.fw-8cbf-featureimage.png).

**Comment by andrewnenakhov** [comment]
That's actually a standard component of Android and not too often used to make it even easier to access. So i suggest it stay where it is.
