### ISSUE TITLE
Show the state under the Xabber logo

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#501]
Right now, the [lateral panel shows the Xabber logo](https://crowdin.com/s/73a313d3m493v6a3b307130353039505l4m4o42685536545c6?size=origin) with a coloured picture, is really cool but the space is wasted, so maybe it could show the current status that we're using and an access to change it if we press it.

Something like this: 
(Of course, with the coloured wallpaper, the colour of the font should be white, just like the Xabber logo.)

![g4231](https://cloud.githubusercontent.com/assets/7888062/8478770/afb765a8-20d3-11e5-9d75-b410f4303a62.png)

**Comment by moshpirit** [comment]
Maybe the pencil symbol could be changed by the main status symbol: ![](https://raw.githubusercontent.com/redsolution/xabber-android/master/app/src/main/res/drawable-hdpi/ic_status_available_18dp.png) ![](https://raw.githubusercontent.com/redsolution/xabber-android/master/app/src/main/res/drawable-hdpi/ic_status_away_18dp.png) ![](https://raw.githubusercontent.com/redsolution/xabber-android/master/app/src/main/res/drawable-hdpi/ic_status_dnd_18dp.png) ![](https://raw.githubusercontent.com/redsolution/xabber-android/master/app/src/main/res/drawable-hdpi/ic_status_chat_18dp.png) ![](https://raw.githubusercontent.com/redsolution/xabber-android/master/app/src/main/res/drawable-hdpi/ic_status_unavailable_18dp.png)

**Comment by andrewnenakhov** [comment]
we have some other plans for that space. For now it's left blank intentionally. :)

**Comment by moshpirit** [comment]
Mm OK, may I ask what plans?

**Comment by andrewnenakhov** [comment]
Special messages from us to Xabber users. ) Xmpp on mobile is broken, and we need to fix it.
