### ISSUE TITLE
Introduce first the name instead of the server when adding a MUC

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#503]
For the example `name-of-the-room@conference.jabber.org`, instead of:

- Multi Chat User server: `conference.jabber.org` 
- Conference: `name-of-the-room`

It should be:

- Conference: `name-of-the-room`
- Multi Chat User server: `conference.jabber.org` 

[Related picture](https://crowdin.com/s/73a313d3m493v6a3h30744j475o4r45545p455l6l4936373q4g4j463i443r4f44313v27383i4n4634395v4u4?size=origin).

Why? because when we share a room ID, we write just *`name-of-the-room@conference.jabber.org`* instead of *"In the server `conference.jabber.org`, the conference `name-of-the-room`"*, so IMO sounds more logic to input first the name of the room and later the server.

**Comment by andrewnenakhov** [comment]
we thought that server for the room is more important than conference name. After all, conferences are many, but servers that support them are few. Does anyone else have some other opinion? Would be nice with reasoning, too.

**Comment by moshpirit** [comment]
In most of the xmpp clients we introduce first the name and the server later, in fact, here in Xabber, we introduce first the name of the account and after that, the server so it should be great to keep it more coherent. 
At least, that's my view.

**Comment by Natanji** [comment]
Why is there any need for separation? When we add a contact, we simply give jid@server.com. Why not just do the exact same thing for conferences, i. e. giving conference@server.com instead of conference in one field and server.com in the other? That always seemed outright weird to me.

**Comment by sbrl** [comment]
I agree with @Natanji - why add in a separator? A simple text box that is set to the type email (so that the `@` symbol appears on the keyboard) should do just fine.

**Comment by andrewnenakhov** [comment]
Once you put in server name, you can look up for all conferences on it and choose conference from a list. So it makes perfect sense to input server first. 

Making just one JID is not good an option, imo, because conference jids tend to be rather long, and sometimes do not fit narrow mobile screen nicely.

Any other thoughts, anyone?

**Comment by moshpirit** [comment]
Well, right now this option is not implemented, so I think that it should autocomplete the server name and for this nice feature that you've just proposed maybe it should be added a "Search MUCs" button

**Comment by moshpirit** [comment]
BTW, I noticed that when we write the name of the room and we complete it by using the T9/Keyboard predictor there's added a space, but this doesn't happen when we write the name of the server. Is it a bug?

**Comment by andrewnenakhov** [comment]
Ok, we've found a better solution (currently seen in beta version) with searching for rooms. It's not yet final, but it looks way better than purposed here, so we close this issue.
