### ISSUE TITLE
Option to keep open the recent conversations 

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#504]
It would be really good for crashes and for people who talk with almost the same few contacts everyday and have a lot of them or just want something more similar to others IM to help them to make the transition to XMPP.

I've thought in adding a check item to the roster menu (up/right) or the Recent chats list, the Chat settings or wherever you prefer to include this option with the sentence "keep open the latest conversations". So it would automatically load the latest chats and keep them open until the user uncheck this option.

**Comment by andrewnenakhov** [comment]
recent chats will have basically the same functionality when we're done with it. But recent chats might be closed, they are sorted by most recent message anyway. 'open' status means that app is active, you don't want that for all chats. simple list should be enough to pick conversation from where it was left from. And crashes are,happily, not THAT often to make such an option viable.
