### ISSUE TITLE
In order to simplify the main menu, "close all chats" should be shown just in the "Recent chats" menu

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#509]
As I said in #501, "Set status" should be moved to the lateral panel, so if this feature would be done as well, the menu would only show:
- Add contact
- Add conference 
- Chat list / recent chats / Active chats (seriously, all of them should be called equally) and maybe this option should disappear if it's enabled the option to be shown in the roster.

I think that it's a really minor issue, but a good way to simplify the app.

**Comment by andrewnenakhov** [comment]
No, we like that option where it already is. We plan to do some improvements to main roster view in Xabber.
