### ISSUE TITLE
Private notification

### ISSUE THREAD

**Issue by xavihernandez** [redsolution/xabber-android#512]
Hi,

If I remember Sender was hidden in pre-Material releases when user had ticked lprivate notification. Now only message is hidden, sender is visible. Could you add back possibility to hide sender too?

**Comment by xavihernandez** [comment]
Just realized old Xabber was showing same infos... So could you add "private sender" to hide sender in notification please?

**Comment by andrewnenakhov** [comment]
You can already hide all info in notification.
