### ISSUE TITLE
application language

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#514]
up to 1.0.29 application was in english, since 1.0.29 it's native (presumably phones default) language. is there a chance to add this as a setting? i'd love to switch back to english. 

please don't make me regret contributing to translation :-)

**Comment by andrewnenakhov** [comment]
True. I personally hate some apps that are presented to me only in Russian locale, which is often autotranslated and ultra-bad.

**Comment by mis2417** [comment]
great, thanks.

**Comment by andrewnenakhov** [comment]
Sometime down the road we'll add choosing language to Xabber. But later.
