### ISSUE TITLE
Messages not delivered upon sign-in

### ISSUE THREAD

**Issue by tspacepilot** [redsolution/xabber-android#517]
If I'm disconnected and someone sends me a message, I'd expect it to be delivered when I sign in.  But this seems not to be the case.  Is my expectation incorrect or is this something which can be fixed.  I seem to recall that I received messages sent while I was signed out upon resigning in back when I used google-talk.

Thank you, btw, I love this app.  So happy not to be running google hangouts anymore!

**Comment by tspacepilot** [comment]
I wish I knew how to add labels, I see it on the right but it is greyed out :(

**Comment by aelmahmoudy** [comment]
This is a clone of #487

**Comment by andrewnenakhov** [comment]
Google talk quietly killed offline message delivery. Soon they'll kill Gtalk as well. Not Xabber issue.
