### ISSUE TITLE
Disconnections on chat open using OpenFire server (Xabber >=1.0.38)

### ISSUE THREAD

**Issue by grigoryfedorov** [redsolution/xabber-android#521]
Steps to reproducs:
1. sing in using OpenFire server account (I used http://www.coderollers.com/xmpp-server/)
2. Try to open chat by clicking contact from contact list
Immediate disconnect. Reconnection problems.
After migration to Smack 4.1.3 #502  (Xabber >=1.0.38)

**Comment by aelmahmoudy** [comment]
@Flowdalic Interesting ! If I recall correctly, OpenFire is developed by the same people who developed Smack as well, right ?

**Comment by Flowdalic** [comment]
Openfire, Smack and a few other XMPP related projects where initiated by Jive Software, but later (~2009) handed over to the Open Source community and are now under the umbrella of Ignite Realtime. So you are right except for the tense: "Openfire *was* developed by the same people...". I'm in close contact with Openfire's maintainer, but that's it. For example Smack's integration tests are run against a different XMPP server (prosody).

Regarding #520 and #521: Hard to tell what's going on with the information at hand. An XMPP trace and the full exception incl stacktrace are good starting points. I usually point people seeking help regarding an Smack issue to https://github.com/igniterealtime/Smack/wiki/How-to-ask-for-help-or-report-an-issue

**Comment by grigoryfedorov** [comment]
I found out, what the problem is in message archive. It I use "Store message history" "on server" I get disconnected as written above. In other case it works as usual. 
```
08-10 12:29:14.902    32361-679/com.xabber.androiddev I/System.out﹕ 12:29:14 PM SENT (1): <iq id='4s5r5-43' type='get'><list xmlns='urn:xmpp:archive'<list end="2015-08-10T07:28:21.130+00:00" with="grigory.fedorov2@blah.im" xmlns="urn:xmpp:archive"><set xmlns="http://jabber.org/protocol/rsm"><before></before><max>20</max></set></list></list></iq>
08-10 12:29:14.997    32361-680/com.xabber.androiddev I/System.out﹕ 12:29:14 PM RECV (1): </stream:stream>
08-10 12:29:15.000    32361-679/com.xabber.androiddev I/System.out﹕ 12:29:15 PM SENT (1): <presence id='4s5r5-44' type='unavailable'></presence>
08-10 12:29:15.003    32361-679/com.xabber.androiddev I/System.out﹕ 12:29:15 PM SENT (1): </stream:stream>
08-10 12:29:15.006    32361-680/com.xabber.androiddev W/Roster﹕ Roster not loaded while processing presence stanza
08-10 12:29:15.006    32361-680/com.xabber.androiddev W/Roster﹕ Roster not loaded while processing presence stanza
08-10 12:29:15.007    32361-680/com.xabber.androiddev I/System.out﹕ 12:29:15 PM XMPPConnection closed (1)
    [ 08-10 12:29:15.268 32361:32361 I/com.xabber.android.data.account.AccountItem@333c4567:grigory.fedorov@coderollers.com/androidonClose 617667962 - 1, true
```

**Comment by Flowdalic** [comment]
That sounds as there should be a corresponding causing exception in Openfire's logs. @grigoryfedorov do you have access to those?

**Comment by grigoryfedorov** [comment]
@Flowdalic unfortunately we don't have Openfire server. But, I think, should get one..

**Comment by Flowdalic** [comment]
If it turns out to be an Openfire issue, the please report your findings at https://community.igniterealtime.org/community/developers/openfire_dev

**Comment by jkutterer** [comment]
I have the same problem. From the log of the openfire server you see that there is an wrong formatting of the xml request xabber send to the server. In Line to the tag is not close correctly:

```xml
<iq id='Jek4e-664' type='get'>
<modified xmlns='urn:xmpp:archive'
<modified start="2015-10-27T14:49:01.541+00:00" xmlns="urn:xmpp:archive">
<set xmlns="http://jabber.org/protocol/rsm">
<before></before>
<max>20</max>
</set>
</modified>
</modified>
```
</iq>
