### ISSUE TITLE
1.0.38 (and later) not installable on devices that don't support camera autofocus

### ISSUE THREAD

**Issue by aelmahmoudy** [redsolution/xabber-android#523]
Versions 1.0.38 and later are not installable on devices that do not support camera autofocus, on F-Droid it says that app is not compatible with my device because it requires "android.hardware.camera.autofocus" permission.

**Comment by grigoryfedorov** [comment]
Should be possibly fixed in dadb28e3371571488386f888fe59ba7a06860bd0
Could not reproduce, unfortunately.

**Comment by esalazioneHg** [comment]
confirmed here, but you can still install it clicking on it. it just double check your will.
imho the choise not to set it as a requirement is a better solution. well done

**Comment by andrewnenakhov** [comment]
@aelmahmoudy is it still an issue?

**Comment by aelmahmoudy** [comment]
Not an issue anymore.
