### ISSUE TITLE
Using Tor  .onion server address on Xabber

### ISSUE THREAD

**Issue by lagosazules** [redsolution/xabber-android#525]
Looking how to use a direct Tor  .onion server address on Xabber
I use Calyxinstitute and they got a dirrect .onion server address, works fine with Tails and Pidgin but I did not found a way to do this in Xabber.
If not possible I think it will be a good extra security option.
Not leaving the onion web direct to and from the server, greet anonymity.

**Comment by lagosazules** [comment]
In chatsegure it works in Advanced account / connect server,  for calyxinstitute use ijeeynrc6x2uy5ob.onion 
Also great to register manual or burn accounts on Calyx

**Comment by mqhash** [comment]
Any updates on connection to onion servers from Xabber?

I tried to connect but "Unknown host" keeps popping up, I am using tor as a proxy. Orbot is up and running and had no problem at all connecting from ChatSecure on the same device.

I also tried to disable the proxy for Xabber and enforce orbot vpn on all apps but nothing changed.
Any ideas where am I going wrong>

**Comment by xeverse** [comment]
No custom .onion working hosts for us(

**Comment by licaon-kter** [comment]
Nothing new here?

**Comment by licaon-kter** [comment]
@lagosazules ?
