### ISSUE TITLE
Implement (unofficial) XMPP IM Design Guidelines

### ISSUE THREAD

**Issue by Flowdalic** [redsolution/xabber-android#527]
http://wiki.xmpp.org/web/XMPP_IM_Client_Design_Guidelines mentions a few guidelines how to implement XMPP clients. While Xabber already follows some of them, others are missing. Most importantly:
- Do not to encode any semantics into the resource, let the server generate a resource for you
- Show the type and name of a resource (mobile, pc, home, work, etc.) by means of Service Discovery and not the resource string itself. Also set meaningful 'identity' information yourself

I'm not actually sure if Xabber already sets the XEP-30 identity or does display the identity of other entities. If not, it should do so.
Also Xabber should provide a option to let the server assign a resource and probably default to this.

**Comment by andrewnenakhov** [comment]
No, we have other ideas about these things.
