### ISSUE TITLE
After updating to 1.0.38, can't connect to Prosody server

### ISSUE THREAD

**Issue by Cysioland** [redsolution/xabber-android#528]
Tries to reconnect ad nauseam, and doesn't succeed.

Excerpt from server logs:

```
Aug 13 14:07:36 c2sREDACTED info    Client connected
Aug 13 14:07:37 c2sREDACTED info    Authenticated as REDACTED
Aug 13 14:07:37 c2sREDACTED info    Client disconnected: closed
```

**Comment by Cysioland** [comment]
@grigoryfedorov On 1.0.42 I'm getting "Connection error: variable cannot be null".

**Comment by Cysioland** [comment]
@grigoryfedorov I cannot connect on 1.0.45.

**Comment by grigoryfedorov** [comment]
@Cysioland hi, could you tell, which server you are using? So I can test it by myself.

**Comment by Cysioland** [comment]
The problem is, I'm using my private Prosody server.

**Comment by teddybeermaniac** [comment]
I too use prosody (latest snapshot) and encountered the same issue using all versions of xabber available in f-droid (.45, .51, .53) and found this in logcat repeated for each connection failure:

    I/MemorizingTrustManager(25883): getAppKeyStore(/data/data/com.xabber.android.beta/app_KeyStore/KeyStore.bks) - exception loading file key store
    W/AbstractXMPPConnection(25883): Connection closed with error
    W/AbstractXMPPConnection(25883): java.lang.IllegalArgumentException: variable cannot be null
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.util.StringUtils.requireNotNullOrEmpty(StringUtils.java:263)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smackx.disco.packet.DiscoverInfo$Feature.<init>(DiscoverInfo.java:491)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smackx.disco.packet.DiscoverInfo.addFeature(DiscoverInfo.java:87)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:74)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smackx.disco.provider.DiscoverInfoProvider.parse(DiscoverInfoProvider.java:34)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.provider.Provider.parse(Provider.java:35)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:638)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:153)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:956)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:989)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
    W/AbstractXMPPConnection(25883): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
    W/AbstractXMPPConnection(25883): 	at java.lang.Thread.run(Thread.java:818)

And on the server side (which looks fairly normal to me):

    Nov 23 20:26:18 c2s801c8d480	info	Client connected
    Nov 23 20:26:18 c2s801c8d480	debug	Client sent opening <stream:stream> to przybys.eu
    Nov 23 20:26:18 c2s801c8d480	debug	Sent reply <stream:stream> to client
    Nov 23 20:26:18 c2s801c8d480	debug	Received[c2s_unauthed]: <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
    Nov 23 20:26:18 socket	debug	server.lua: we need to do tls, but delaying until send buffer empty
    Nov 23 20:26:18 c2s801c8d480	debug	TLS negotiation started for c2s_unauthed...
    Nov 23 20:26:18 socket	debug	server.lua: attempting to start tls on tcp{client}: 0x801e0d028
    Nov 23 20:26:19 socket	debug	server.lua: ssl handshake done
    Nov 23 20:26:19 c2s801c8d480	debug	Client sent opening <stream:stream> to przybys.eu
    Nov 23 20:26:19 c2s801c8d480	debug	Sent reply <stream:stream> to client
    Nov 23 20:26:19 c2s801c8d480	info	Stream encrypted (TLSv1.2 with DHE-RSA-AES256-GCM-SHA384)
    Nov 23 20:26:19 c2s801c8d480	debug	Received[c2s_unauthed]: <auth mechanism='SCRAM-SHA-1' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
    Nov 23 20:26:19 przybys.eu:saslauth	debug	sasl reply: <challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>--REMOVED--</challenge>
    Nov 23 20:26:19 c2s801c8d480	debug	Received[c2s_unauthed]: <response xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
    Nov 23 20:26:19 c2s801c8d480	info	Authenticated as michal@przybys.eu
    Nov 23 20:26:19 przybys.eu:saslauth	debug	sasl reply: <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>--REMOVED--</success>
    Nov 23 20:26:19 c2s801c8d480	debug	Client sent opening <stream:stream> to przybys.eu
    Nov 23 20:26:19 c2s801c8d480	debug	Sent reply <stream:stream> to client
    Nov 23 20:26:19 c2s801c8d480	debug	Received[c2s]: <compress xmlns='http://jabber.org/protocol/compress'>
    Nov 23 20:26:19 c2s801c8d480	debug	zlib compression enabled.
    Nov 23 20:26:19 c2s801c8d480	debug	Client sent opening <stream:stream> to przybys.eu
    Nov 23 20:26:19 c2s801c8d480	debug	Sent reply <stream:stream> to client
    Nov 23 20:26:19 c2s801c8d480	debug	Received[c2s]: <iq id='hki69-36' type='set'>
    Nov 23 20:26:19 c2s805155f80	debug	Disconnecting client, <stream:error> is: <stream:error><conflict xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Replaced by new connection</text></stream:error>
    Nov 23 20:26:19 c2s805155f80	debug	c2s stream for michal@przybys.eu/phone2 closed: Replaced by new connection
    Nov 23 20:26:19 c2s805155f80	debug	Destroying session for michal@przybys.eu/phone2 (michal@przybys.eu): Replaced by new connection
    Nov 23 20:26:19 sessionmanager	debug	All resources of michal are now offline
    Nov 23 20:26:19 c2s805155f80	debug	Received[c2s]: <presence type='unavailable'>
    Nov 23 20:26:19 c2s805155f80	info	Client disconnected: connection closed
    Nov 23 20:26:19 c2s805155f80	debug	Destroying session for (unknown) ((unknown)@(unknown))

Xabber 1.0.30 connects to the same server without any issues.

**Comment by teddybeermaniac** [comment]
I built Xabber from develop branch and captured a debug log - https://gist.github.com/teddybeermaniac/b06767270cea33cf42be

**Comment by grigoryfedorov** [comment]
@teddybeermaniac thanks a lot! As far as I could understand, it is a Prosody bug. 
@Cysioland @teddybeermaniac it would be greate if you could disable Message Archive on your servers and try Xabber again. Thanks.

**Comment by teddybeermaniac** [comment]
It works. Strangely, yesterday I tried .53 with nearly all prosody modules disabled and it failed, yet today even that version connects when I disable the mam_archive module which is at fault here. It's some kind of magic. Nonetheless, thank you very much for looking into it. :)

**Comment by Cysioland** [comment]
I confirm disabling mam_archive as a functional workaround.

**Comment by yuyuyak** [comment]
@grigoryfedorov I followed your link, did you continue on and file the bug with the prosody folks?  I don't see it on their issue tracker.  I have this same problem and I don't use any archive module on prosody.  Eventually prosody dies due to the loop and I have to reboot the server, too complex to just deal with prosody.  If not, I can file it with them, but you seem to have a better grasp of it.  A problem for many months now...
