### ISSUE TITLE
Persistent notification priority

### ISSUE THREAD

**Issue by LenaicTerrier** [redsolution/xabber-android#530]
Hi,
I've just try [Syncthing android app](https://github.com/syncthing/syncthing-android), and they have an option to set the permanent notification as ~~_low priority_~~ _[min priority](http://developer.android.com/design/patterns/notifications.html#correctly_set_and_manage_notification_priority)_. When activated, the persistent notification is not shown on the lockscreen and is seperated from the others notifications on the notification screen (when expanding the taskbar).

I think that would be a great feature for Xabber.

Regards

PS : I don't really know the underlying technicals implications, so I'm sorry if this is not possible.

**Comment by LenaicTerrier** [comment]
Here are 3 screenshots, to show what I mean.

[locked_full](https://cloud.githubusercontent.com/assets/5877651/9492731/901f0816-4bfa-11e5-985c-ce5b32c822a1.jpg)
[locked_main](https://cloud.githubusercontent.com/assets/5877651/9492732/901fb964-4bfa-11e5-9d0f-acc356edb3a4.jpg)
[unlocked](https://cloud.githubusercontent.com/assets/5877651/9492733/90254fbe-4bfa-11e5-94ec-b86a2bbd2d7e.jpg)

And [here](https://github.com/syncthing/syncthing-android/commit/54820d20f4aa509dda5a9e458e9dbed3b44c3c68) is a commit at **syncthing-android** about persistent notification priority.

Regards.

**Comment by andrewnenakhov** [comment]
If would make Xabber more likely to be unloaded from memory.
