### ISSUE TITLE
1.42 start new encrypted chat problem

### ISSUE THREAD

**Issue by marix11** [redsolution/xabber-android#538]
When i upgraded to 1.42. People cant start new chat with me. All messages waiting until i start chat. Back to 1.39 and problem gone

**Comment by Bujiraso** [comment]
I'll check the version, but I might be suffering from this, too, at the other end. I cannot seem to start private chats with my friend on the latest update, but he can start them with me. All my messages get lost.

**Comment by digititus** [comment]
I can confirm this behavior. Starting OTR conversations doesn't happen until both parties send messages. So if Alice sends a message to Bob, Bob never sees it. However, if Bob decides he wants to message Alice, then OTR session starts, minus first message from Alice.

**Comment by marix11** [comment]
Upgraded to 1.45. And it seems fixed the problem. Thanks

**Comment by RealRancor** [comment]
Can confirm this too. The changelog of 1.0.45 is also stating:

> message receiving bug fixed.

**Comment by digititus** [comment]
Yes, fixed for me in 1.0.45
