### ISSUE TITLE
Direct download link

### ISSUE THREAD

**Issue by grep-i386** [redsolution/xabber-android#541]
Hello!
Can you please give me a direct download link to Xabber classic (G Play Market didnt work on my phone)?
Thank you

**Comment by grigoryfedorov** [comment]
Hi! Try getting it from F-droid:
https://f-droid.org/repository/browse/?fdfilter=xabber&fdid=com.xabber.android.classic

2015-09-08 20:36 GMT+05:00 grep-i386 <notifications@github.com>:

> Hello!
> Can you please give me a direct download link to Xabber classic (G Play
> Market didnt work on my phone)?
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redsolution/xabber-android/issues/541>.
>



-- 
Grigory Fedorov
Software developer at Redsolution Ltd.
tel.: +79220150112 (mobile.)
www.redsolution.com

**Comment by grep-i386** [comment]
Big thanks :)
