### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by synthead** [redsolution/xabber-android#543]
Please add a dark theme to the UI. This application used to have it but it was taken away, and Xabber remains to be one of the few applications I regularly use without a dark theme.

**Comment by xeverse** [comment]
So true. Essential..

**Comment by RealRancor** [comment]
@synthead @xeverse Seems the new 1.0.73 is now shipping a dark theme. Quite nice in my opinion so give it a try. :-)

**Comment by andrewnenakhov** [comment]
Dark theme is implemented in v.2.
