### ISSUE TITLE
Authorization error when switching between WiFi and Mobile Data

### ISSUE THREAD

**Issue by KonomiKitten** [redsolution/xabber-android#555]
Every time my phone changes from WiFi to Mobile Data or vice versa, Xabber behaves in the following way: First it'll try to reconnect, takes about 2 minutes then the notification of "Authorization error" pops up and Xabber completely gives up reconnecting. At this point I have to close Xabber and reopen it to get the account to reconnect. Xabber will connect fine on both my Mobile Data and WiFi providing it isn't transitioning between either of them.

Android 5.0.2
Xabber 1.0.30

**Comment by andrewnenakhov** [comment]
Most likely it had to do with DNS roundrobin and Gmail accounts... Not too relevant now. It it still is, reopen bug and post some debug logs from device.
