### ISSUE TITLE
Add purple to the list of available account colors

### ISSUE THREAD

**Issue by HelderMagalhaes** [redsolution/xabber-android#557]
While using Pidgin at work, I got used to associating orange and purple (two colors associated to Pidgin itseld) with my workplace account (private XMPP server). While orange is currently available, it's also visually close to red, color which has been lately associated with Google services (Gmail/Google+). Therefore purple would be most fit, while also being more distinguishable than the set of available bluish/greenish tones IMHO.

**Comment by andrewnenakhov** [comment]
Purple, and lots of other colors were added.
