### ISSUE TITLE
Heartbeat (connection stabilization)

### ISSUE THREAD

**Issue by BlueMax** [redsolution/xabber-android#560]
Occasionally, connection gets lost and doesn't recover until phone gets woken up by user (screen on). A frequent 'heartbeat' (alarm event, contact xmpp server by null message, ping or something) every x minutes (configurable) should fix that problem. This is done by most push services as well (IMAP, GCM/Google Cloud Messaging and such).

**Comment by andrewnenakhov** [comment]
It's more complicated than you think and can't be done by client side only.
