### ISSUE TITLE
Optional system notifications

### ISSUE THREAD

**Issue by Null-Kelvin** [redsolution/xabber-android#561]
I'm using Xabber with LightFlow notifications control. LightFlow signals repeatedly if there is any notification from Xabber. But Xabber creates notification when it reconnect to server, and LightFlow can't recognize that it isn't message.
Can you add option for disabling any non-message notification from Xabber, please?

**Comment by davidchisnall** [comment]
This doesn't just affect LightFlow users.  On my phone (Moto G), the notification LED is constantly flashing while connected, which makes it impossible to tell if there are any waiting messages without turning the phone on.

**Comment by krushmp** [comment]
Ask Andrew what he would like from xabber dev to facilitate changes to Light Flow.

It would be best if LF could identify messages from JID or content

**Comment by andrewnenakhov** [comment]
Persistent notification helps Xabber stay connected and keep receiving messages. Without it app can be unloaded from memory by OS.
