### ISSUE TITLE
Can't see nor save transferred pictures

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#562]
The XEP works perfectly on my device, but I can't open the picture, nor even save it :( 
Maybe am I missing something?

**Comment by grigoryfedorov** [comment]
@moshpirit you should be able to open image with system viewer simply by tapping on it. Or you can open message menu (by tapping on message row - near the image). Menu has actions to open and save file.

**Comment by moshpirit** [comment]
>No application found to open this file

I have an images viewer (the gallery that Android brings by default) and I can't open the saved picture neither. But I can open the file if it's shared by Conversations :\

**Comment by grigoryfedorov** [comment]
interesting. it that for all images? is it correctly shown in Xabber chat? what is the file extension?

**Comment by moshpirit** [comment]
I only tried it with a JPG image, I can perfectly see it on the bubble:
![696f82ea-adcf-49af-a3fa-280e8ca5e169](https://cloud.githubusercontent.com/assets/7888062/10450102/44763b00-7198-11e5-9689-b01e671f134e.jpg)

**Comment by grigoryfedorov** [comment]
@moshpirit may be extension written in caps? (JPG) I think I missed that case.

**Comment by moshpirit** [comment]
Probably, I'm seeing that I can perfectly open a jpg picture that I sent (to myself)

**Comment by grigoryfedorov** [comment]
@moshpirit thanks for testing. It would be fixed in next version.

**Comment by moshpirit** [comment]
Thank *you* for all your work! ;)
