### ISSUE TITLE
Space distribution

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#563]
**Note**: This is an issue about my personal opinion of the aesthetic of Xabber. In addition, it's about the Chat view.

![e1e58bc2-d303-491d-ac4b-b910e2366484](https://cloud.githubusercontent.com/assets/7888062/10448895/40c008ea-7190-11e5-8334-9593c4382339.jpg)

I think that we have not much space to write right now, maybe it could be better to put the locker to the upper part of the screen or changing the clip icon and the arrow to send the message so we can have more space to write (like Telegram or Conversations do). At first, Xabber'd start showing:
- Emojis | Text space | Clip

When we start to write, now we have:
- Emojis | Text to send | Send arrow

In the upper side of the screen we would see: 
- ← | Avatar + name + status icon | locker | Menu

In fact, we could save even more space if the back arrow "←" and the status icon (the blue/red/etc circle) got put together that way: 

![40c008ea-7190-11e5-8334-9593c4382339](https://cloud.githubusercontent.com/assets/7888062/10449923/fd70a098-7196-11e5-8ea0-09eaa7b17d0e.jpg)

**Comment by andrewnenakhov** [comment]
No, that's not pretty.
