### ISSUE TITLE
Depending on the servers I can't send files (even when they have the XEP)

### ISSUE THREAD

**Issue by moshpirit** [redsolution/xabber-android#564]
A big implementation is always hard, I know that you're doing a lot of work here and it's really really appreciated but I'm having some troubles with file sharing: I can't use any server that includes the XEP.

My case:
I have 2 accounts on 2 different servers that allows the XEP-0363: HTTP File Upload. These servers are: suchat.org and mijabber.es.

On Conversations I have no problems sending files between these accounts (always by using this XEP and not Jingle, because it allows me to copy the original URL of the file so Xabber does). 
On Xabber I can send files from suchat.org to mijabber.es but not vice-versa.

**Comment by Notxor** [comment]
The same happens to me with mijabber.es

**Comment by grigoryfedorov** [comment]
It seems to me that mijabber.es does not support HTTP file upload correctly. 
Also I could not send any file even with conversations (1.6.11)
Here is the screenshot with server info from Conversations. 
![screenshot_2015-10-13-14-47-38](https://cloud.githubusercontent.com/assets/6428909/10451422/8b876944-71b9-11e5-8a01-958ecb5fe53d.png)

**Comment by moshpirit** [comment]
Sorry, you're totally right!
