### ISSUE TITLE
Incoming XMPP attention plays phone ringtone. There's no setting to change or disable it.

### ISSUE THREAD

**Issue by oskvta** [redsolution/xabber-android#566]
If a contact sends attention/buzz/poke request (XMPP attention), Xabber starts playing the phone's ringtone. There is no way to change the sound or to disable it.

There needs to be a setting where you can select the notification sound that is played when receiving XMPP attention request.

**Comment by andrewnenakhov** [comment]
You may set attention request ringtone in Chat settings.
