### ISSUE TITLE
Google Talk SmackException

### ISSUE THREAD

**Issue by smarek** [redsolution/xabber-android#569]
Having Xabber connected to my Google Talk account, there are stacktraces like this in console, replaced real e-mail address with `{contactusername}`

Running Xabber Dev 1.0.53 from F-Droid distribution

```
W/PacketParserUtils(32327): Failed to parse extension packet in Presence packet. Attributes: from={contactusername}@gmail.com/gmail.91D5BA8C id=null
W/PacketParserUtils(32327): org.jivesoftware.smack.SmackException: Caps elment with missing attributes. Attributes: hash=null version=1.1 node=http://mail.google.com/xmpp/client/caps
W/PacketParserUtils(32327):     at org.jivesoftware.smackx.caps.provider.CapsExtensionProvider.parse(CapsExtensionProvider.java:54)
W/PacketParserUtils(32327):     at org.jivesoftware.smackx.caps.provider.CapsExtensionProvider.parse(CapsExtensionProvider.java:28)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.provider.Provider.parse(Provider.java:35)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.util.PacketParserUtils.parseExtensionElement(PacketParserUtils.java:929)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.util.PacketParserUtils.addExtensionElement(PacketParserUtils.java:1060)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.util.PacketParserUtils.parsePresence(PacketParserUtils.java:583)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:155)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:956)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:989)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
W/PacketParserUtils(32327):     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
W/PacketParserUtils(32327):     at java.lang.Thread.run(Thread.java:818)
```

**Comment by andrew-bowley** [comment]
Here is an example of the error captured with debug tracing on. Couldn't drag extract from log for unknown reason, so will paste it. The complaint is about a missing hash attribute:

Caps element with missing attributes. Attributes: hash=null

04:04:30 PM RECV (3): &lt;presence from="andrew.james.bowley@gmail.com/MessagingAf60bec5c" to="andrew.james.bowley@gmail.com/cybertete8A20DFDE"&gt;&lt;show&gt;away&lt;/show&gt;&lt;caps:c node="http://www.android.com/gtalk/client/caps" ver="1.1" xmlns:caps="http://jabber.org/protocol/caps"/&gt;&lt;x xmlns="vcard-temp:x:update"&gt;&lt;photo&gt;ad4adf8994b761099bb66c5fd907ba7631ca474a&lt;/photo&gt;&lt;/x&gt;&lt;/presence&gt;

Nov 26, 2015 4:04:30 PM org.jivesoftware.smack.util.PacketParserUtils parsePresence
WARNING: Failed to parse extension packet in Presence packet. Attributes: from=andrew.james.bowley@gmail.com/MessagingAf60bec5c id=null

org.jivesoftware.smack.SmackException: Caps elment with missing attributes. Attributes: hash=null version=1.1 node=http://www.android.com/gtalk/client/caps

**Comment by grigoryfedorov** [comment]
Smack devs:

> Google Talk sends the "caps" element with an legacy/outdated specification and some now mandatory attributes are missing.
 
> Packet Extensions of Presence packets that throw an exception will just get ignored and logged. No need to worry. 
https://community.igniterealtime.org/thread/50168

**Comment by andrewnenakhov** [comment]
Farewell, Gtalk, we hardly knew ye..
