### ISSUE TITLE
Pre-populate conference server field

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#57]
> It would be good, if the field for the conference server on the Join Conference dialog would be "pre-populated". As the pre-defined (but of course user changeable) value, it should use "conference."$server-name; ie. if you take a look at the attached screenshot or picture below, where my Jabber name is ask@jabber.1st.ch, the conference server field should be pre-filled with "conference.jabber.1st.ch". That's also what eg. the Pidgin IM client uses. This would be good, because it can be somewhat "annoying" to enter domain names and such on a mobile phone keyboard.

**Comment by andrewnenakhov** [comment]
Conferencing is bad, so I'm fine with conference users suffering - they chose it voluntarily.
