### ISSUE TITLE
Xabber ignores Key Phrases in chatrooms

### ISSUE THREAD

**Issue by akomakom** [redsolution/xabber-android#575]
... or I don't know how to set them up. 
Tried current (Nov 4, 2015) versions of Xabber and Xabber Beta.

I'm trying to get nickname mention to trigger an alert in a persistent chatroom.
I've tried what seems to be every combination of turning notifications on/off globally and per chatroom, added key phrases and configured sounds for them (regex and not regex), and I have succeeded at either: 

1. Getting notified about every message in a chatroom (not what I want)
1. Not getting notified at all, regardless of key phrase matches.

This functionality works out of the box in desktop clients (ie Psi+, etc) and android clients (ie Conversations).

Is there a combination of switches I need to set or does this just not work?

**Comment by cyclingzealot** [comment]
I'm having exact same issue.

**Comment by akomakom** [comment]
**This is currently working for me**, although I don't know if it's something I did right or just because it randomly started working as configured.  I'm on Xabber Beta 1.0.74 now but it should be the same.

I believe that I set a different ringtone for the key phrase (different from the chatroom notification)

My configuration is below:

Main Notifications:
![screenshot_2016-04-05-14-57-26](https://cloud.githubusercontent.com/assets/12100822/14294452/3f0069b2-fb3f-11e5-8657-2eae14d5b81c.png)


![screenshot_2016-04-05-14-59-02](https://cloud.githubusercontent.com/assets/12100822/14294451/3e295e22-fb3f-11e5-80f1-7adcd6cfd04f.png)

KeyPhrase Regex (case sensitive, probably)
![screenshot_2016-04-05-14-58-25](https://cloud.githubusercontent.com/assets/12100822/14294454/404e1a26-fb3f-11e5-8379-24949710dceb.png)

Settings for the specific chat room:

![screenshot_2016-04-05-14-59-59](https://cloud.githubusercontent.com/assets/12100822/14294453/40345294-fb3f-11e5-95f0-21163d55acd0.png)
