### ISSUE TITLE
Xabber quietly closes after removing from recent applications

### ISSUE THREAD

**Issue by esoadamo** [redsolution/xabber-android#578]
When I remove Xabber from recent apps it stays a few minutes ok, but then, when I try to open it from status bar, it starts with blank screen and then "Launching application" appears. It is very annoying because I have to keep applications in recent list. Other background applications are working after removing from recent apps normally.

**Comment by andrewnenakhov** [comment]
Most likely you had android 5.0 which had a bug with background apps. Should not be occurning on any other version of android. If it still affects you, report it back.
