### ISSUE TITLE
file and image transfer?

### ISSUE THREAD

**Issue by prototype2118** [redsolution/xabber-android#580]
Is this feature going to be implemented soon?  I don't see anything in the milestone for this to be in the next release only the title for the Dec 20th milestone.

**Comment by grigoryfedorov** [comment]
XEP-0363: HTTP File Upload implemented now, available in Xabber Beta. See #23

**Comment by pejakm** [comment]
Is there any good server somewhere with the required XEP to test file transfer? Or even better, is there a way to test XMPP servers for particular XEPs?

**Comment by grigoryfedorov** [comment]
@pejakm suchat.org works well. 
Some XMPP clients allow to discover services supports, it may help. For example Gajim or Conversations. Also Xabber would show "attach file" button only if server support XEP-0363.

**Comment by sbrl** [comment]
I think that the image transfer is broken. I keep getting red crosses on the images I specify.

**Comment by tahatauqeer** [comment]
how to share a file? i can't see any attachment button in xabber?

**Comment by andrewnenakhov** [comment]
Implemented in v2 with http-upload
