### ISSUE TITLE
Proxy is never being used

### ISSUE THREAD

**Issue by Manouchehri** [redsolution/xabber-android#582]
On Android 6.0, the proxy settings are non-functional.

To reproduce:
1. Point proxy to localhost on a non-open port.
2. Connect to account. (The connection should be refused, but it connects anyway without the proxy.)

Related: #525 and #395.

**Comment by geebotron** [comment]
I have also noticed this.

I use the [firewall called netguard](https://f-droid.org/repository/browse/?fdid=eu.faircode.netguard). By default, apps have no network access until explicitly granted. The Orbot local proxy has been granted access but Xabber had not. This should not be a problem as Xabber claims to support the Orbot local proxy.
But - changing the settings on the Xabber account to use the local proxy has no effect and it still tries to  gain network access to connect. To no avail, obviously, as netguard does its job and prevents this.

**Comment by 9662** [comment]
I can confirm. Setting up Orbot as proxy type in Xabber then connecting to my own XMPP server, it shows that the connection is coming directly from my mobile device.

Also, sending a large amount of data via Xabber does not show any change in the Orbot upload/download statistics. The thing is, there is **zero indication** that the proxy is being bypassed. Which is a pretty serious flaw. :unamused:

**Comment by xr09** [comment]
Same here, I'm connecting behind a proxy, can't login ever. With debug enabled all I get is "can't resolve talk.google.com"

**Comment by andrewnenakhov** [comment]
@oxoWrk please check it out. I'm pretty sure proxy settings (at least ORBOT) are not ignored and/or bypassed. If everything's ok, issue should be closed.

**Comment by oxoWrk** [comment]
Checked. The proxy settings are not ignored.
