### ISSUE TITLE
No more dark theme or emoticons?

### ISSUE THREAD

**Issue by prototype2118** [redsolution/xabber-android#583]
The darker theme is sorely missed that was available in previous versions.  Also, why are there no emoticon support in the app anymore?

**Comment by RealRancor** [comment]
@prototype2118 Seems the new 1.0.73 is now shipping a dark theme. Quite nice in my opinion so give it a try. :-)

**Comment by andrewnenakhov** [comment]
Dark theme is implemented in v.2.
