### ISSUE TITLE
"# of # accounts online" should be low priority.

### ISSUE THREAD

**Issue by sentaidigital** [redsolution/xabber-android#585]
The "# of # accounts online" notification shows up on my lock screen, but isn't a very helpful notification there and it obscures my wallpaper.  According to https://code.google.com/p/android/issues/detail?id=174213 the notification can be removed by setting it to low priority.

**Comment by andrewnenakhov** [comment]
It's helpful to make sure Xabber is connected and not unloaded from memory.
