### ISSUE TITLE
Inaccurate certifcate exceptions

### ISSUE THREAD

**Issue by kousu** [redsolution/xabber-android#586]
The certificate error dialog says "Accept Unknown Certificate? The server certificate is not signed by a known Certificate Authority". But this is misleading: it can also be triggered by the clock being wrong so that the cert becomes outdated, _even if_ the CA cert is still valid. It could be triggered by a cert higher in the cert chain being edited, even if the CA is still valid. The wording should be "this certificate is invalid" and, if it's easy to do, add the reason: "because {it is not yet valid, it has expired, it is not signed by a known CA, 'xxxx' in the cert chain was invalid, ....}"

It would also be helpful if it said "SHA256 Fingerprint" and "SHA1 Fingerprint" instead of just "sha256" and "sha1".

**Comment by clickdriven** [comment]
How did you make out with this. I am having a similar issue.

**Comment by kousu** [comment]
I haven't tested it lately. To be honest, I switched to Let's Encrypt and forgot about this. Presumably that's where the devs are at too, now.

**Comment by andrewnenakhov** [comment]
These dialogs have been significantly changed. Most likely question is not relevant.
