### ISSUE TITLE
Its not able to connect with nimbuzz.com

### ISSUE THREAD

**Issue by uttamrajchauhan** [redsolution/xabber-android#589]
Xabber beta is not able to connected with nimbuzz.com its continuously connect n disconnected in 4 5 seconds, but xabber is working fantastic with nimbuzz.com
Kindly please fix it 
Thanks you in advance : )

**Comment by grigoryfedorov** [comment]
@uttamrajchauhan as far as I understand, version 1.0.73 fixed your problem?

**Comment by uttamrajchauhan** [comment]
Thank you developer for fixing my problem, its working awesome : )

Raj Chauhan

**Comment by uttamrajchauhan** [comment]
Now its lil bit hanging and enter send option is not working, earlier it
was fine.
