### ISSUE TITLE
Facebook Chat no longer works in Xabber Dev 1.0.74

### ISSUE THREAD

**Issue by francwalter** [redsolution/xabber-android#594]
Hallo
since around two weeks, the chat throuh chat.facebook.com no longer works. 
The login wouldnt work or something, it says:

> Verbindungsfehler: SASLError using 
> PLAIN: not-authorized

(german "Verbindungsfehler" means: connection error)
I know that Facebook stopped officially his open jabber protocol in April 2015 but in Xabber it worked continously since just weeks ago.
Pidgin works as well with another updated plugin, also Adium.
Is there plans to re-work this in Xabber also?
Thanks

frank

**Comment by mithat** [comment]
I just wanted to +1 that I've experienced the exact same thing: FB chat worked until a few weeks ago.

@francwalter , are you refering to the [jgeboski/purple-facebook](https://github.com/jgeboski/purple-facebook) Pidgin plugin? This or the Pidgin3 code might help answer the question of whether it's possible to use XMPP in some form at all with Facebook anymore--and if so how much of a hack to the protocol is needed.

**Comment by max1220** [comment]
You could always setup a Spectrum2 Server to support Facebook chat(Via the already mentioned libpirple plugin). But the XMPP chat API from Facebook is AFAIK dead for real now.

Some people speculated that this has to do with WhatsApp planing on offering a paid API for Advertisers(which would conflict with a free API on basicly the same platform), and IMHO this seems likely.

**Comment by synthead** [comment]
I'm also using purple-facebook on a daily basis without any problems.  It'd be really great to have this working in Xabber again.

**Comment by AlennGK** [comment]
Yea please =)

**Comment by andrewnenakhov** [comment]
Facebook removed XMPP gateway. You have to use transports if you want to still be usingFB chat with Xabber.
