### ISSUE TITLE
Messages from others don't always appear in MUC's

### ISSUE THREAD

**Issue by ghost** [redsolution/xabber-android#598]
Sometimes, in MUCs, messages from others do not appear in Xabber. However, when restarting Xabber and re-joining the MUC, the missing messages DO appear in the MUC's built-in "saved history", suggesting that the messages are being sent to the MUC, just not to Xabber itself.

This is on Xabber 1.0.30 stable.

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
