### ISSUE TITLE
Export chat > log name, cut and paste banner issue

### ISSUE THREAD

**Issue by ageru** [redsolution/xabber-android#604]
# Steps to reproduce
1. Make sure you are logging chats on your device  
2. Tap on the name of a user to access the chat window
3. Call up the option menu
4. Select Export Chat
## Actual result

When selecting text to cut or paste, the cut/paste banner comes down, but all the icons (except the confirmation checkmark) are white on a white background. The options are still available if you know where to tap.

![screenshot_2015-06-06-15-16-52](https://cloud.githubusercontent.com/assets/12240432/8020017/9b1e34ea-0c61-11e5-8b05-6ed9fd1b9fb9.png)
## Expected result

When selecting text to cut or paste, the cut/paste banner comes down, icons should be a different color from the background they are on
## Notes

This issue has been present since the redesign of the app. Confirmed still present on several devices in 1.0.74.

**Comment by andrewnenakhov** [comment]
That is probably a device issue. that dialog bar in action bar never appears on our devices. Reopen if it's still an issue.
