### ISSUE TITLE
unjoined conferences

### ISSUE THREAD

**Issue by kousu** [redsolution/xabber-android#606]
In the course of developing a transport with MUC support I sent Xabber stanzas something like this:

```
<message to="kousu@galleon/Xabber_4YDASVNK" type="groupchat" id="...." from="test2@irc.galleon/kousu"><body>Happy</body><thread>....</thread></message>
<message to="kousu@galleon/Xabber_4YDASVNK" type="groupchat" id="...." from="test3@irc.galleon/kousu"><body>Sad</body><thread>....</thread></message>
<message to="kousu@galleon/Xabber_4YDASVNK" type="groupchat" id="...." from="test4@irc.galleon/kousu"><body>Meanie</body><thread>....</thread></message>
```

but only test3 was joined from Xabber. The other two Xabber didn't know about until it got these messages. What Xabber does then is show the two unknowns as if they were regular direct message contacts. Xabber seems to be ignoring the 'groupchat' key, and instead using an internal lookup table to decide whether something is a conference or not.

Your behaviour here is like https://github.com/siacs/Conversations/issues/1687 and https://github.com/boothj5/profanity/issues/731, yet different. It seems that, unlike those two, you catch the initial <presence> with <status code=110> and spawn a room. So this weird case of getting messages from rooms you haven't joined only happens in degenerate situations with lazy transports. But you should still be checking the message type!

**Comment by kousu** [comment]
Here's a screenshot:

![xab](https://cloud.githubusercontent.com/assets/987487/12921143/c096f056-cf19-11e5-9a51-4a834dc61702.png)

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
