### ISSUE TITLE
LED notification 

### ISSUE THREAD

**Issue by mis2417** [redsolution/xabber-android#608]
when led notifications are enabled, during a conversation, if the screen turns off led blinks even without new message. to reset it I have to pull down notification area, and it's ok, until next message. then the situation is repeated.
this was an issue with cyanogenmod 12 and 13 (so i think this is xabber related) and happens only in xabber (can't remember whether it was happening with classic version)

**Comment by mis2417** [comment]
a follow up. this is a good behavior when xabber is running in the background, however if conversation is open, but "notify about every message in conversation" is on - that's where the problem is.

**Comment by krushmp** [comment]
bloat

instead install:  Light Flow Pro

**Comment by andrewnenakhov** [comment]
@mis2417  we cant reproduce it on our devices. Does it still affect current Xabber Beta?

**Comment by mis2417** [comment]
unfortunately I can't tell, switched to conversations.

**Comment by andrewnenakhov** [comment]
@mis2417 sorry for you then )
