### ISSUE TITLE
Store conferences for disabled account

### ISSUE THREAD

**Issue by jasonmacduffie** [redsolution/xabber-android#611]
When I disable an account and re-enable, I lose all the conferences that I joined. I believe a re-enabled account should automatically join the conferences it was in.

**Comment by Str4tocaster** [comment]
@jasonmacduffie  Please, check it out in Xabber Beta 2.3 (471). Now Xabber automatically rejoin in MUC after reconnection. We use bookmarks for storing you MUC-list.
