### ISSUE TITLE
SPAM / Msgs from roster contacts only

### ISSUE THREAD

**Issue by xeverse** [redsolution/xabber-android#615]
Considering the spammers activity has been on the rise.
This is the only spam prevention measue that i can think of.

Is there a possiblilty on the xmpp protocol level for that
or should this kind of filtering better be implemented in client?

**Comment by krushmp** [comment]
XEP 0016, Privacy Lists

**Comment by climf** [comment]
yes.  it is xep-0016

**Comment by petrpulc** [comment]
@climf well, not necessarily.
a) many severs do not support full xep-0016
b) blocking on client is sometimes a better solution

**Comment by andrewnenakhov** [comment]
Duplicate of #21
