### ISSUE TITLE
Conferences: rewritten roomnicks

### ISSUE THREAD

**Issue by kousu** [redsolution/xabber-android#617]
The MUC [spec](http://xmpp.org/extensions/xep-0045.html#enter-pres) allows

> The service MAY rewrite the new occupant's roomnick (e.g., if roomnicks are locked down or based on some other policy).

It then hints but doesn't come right out and say that you need to send `<status code=210>` embedded in the self-`<presence>` stanza to enable this. Because it doesn't say it outright, it might be correct to interpret it this way: the `<status code=110>` stanza tells you your current nick. I suspect the spec writers didn't think this part all the way through. In either case, Xabber handles neither. On joining #test@conference.localhost as "bromato", a room I'm already joined as "kousu" in (and that I've arranged to only allow one nick per JID in), even though Xabber receives the code=110 self-presence stanza

```
<presence to="#test@conference.localhost/bromato" id="tVLGi-1196" from="kousu@galleon/Xabber_4YDASVNK">
  <x xmlns="http://jabber.org/protocol/muc"><password /></x>
  <c xmlns="http://jabber.org/protocol/caps" ver="gGZ3D3n8WOVt3v3zt8VhSdcN4nY=" hash="sha-1" node="http://www.igniterealtime.org/projects/smack" />
</presence>

<!-- notice: incoming nick is 'bromato', outgoing is 'kousu'; 210 is supposed to tell the client to accept this forced change -->
<presence to="kousu@galleon" from="#test@conference.localhost/kousu">
  <x xmlns="http://jabber.org/protocol/muc#user"><item jid="kousu@galleon" affiliation="member" role="visitor" />
  <status code="100" />
  <status code="110" />
  <status code="210" />
</x></presence>
```

Xabber does not think the conference exists yet, does not display the member list button, and worst, lets me enter text and send it but does not actually send the stanzas.

See the same issue at https://github.com/siacs/Conversations/issues/1732

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
