### ISSUE TITLE
Can't send second message using Openfire 4.0 server

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#618]
Using Xabber 1.0.30 on two Android tablets (5.0 and 5.1.1) connected to Openfire 4.0.1 server. I can converse with Xabber and desktop client like Spark back and forth normally. Also if i use Yaxim client on both tablets conversation works fine. But if i try to chat between Xabber and Yaxim, or Xabber and Xabber, my first message goes through, then a reply goes back, but if i try to send a second message, it doesn't go through. But if i exit and relogin with that client, it then receives all the messages as if they were stored as offline. Maybe this is related to Openfire removing XEP-0091 support since 4.0 version. Althouh i see that Xabber supports XEP-0203, so it should be fine.

**Comment by wrooot** [comment]
You can test against public Openfire server at igniterealtime.org, although it might be using a bit newer code than 4.0.1.

**Comment by grigoryfedorov** [comment]
Hi! Could you please check, if your issue still exist in [Xabber Beta](https://play.google.com/store/apps/details?id=com.xabber.android.beta)?

**Comment by wrooot** [comment]
Yes, same issue with the Xabber Beta.

**Comment by supertick** [comment]
I can confirm.  I have the identical results as reported by wrooot.  Using Xabber & OpenFire, first message is received.  Subsequent messages are stored, but not received that session.

**Comment by hoaryhedgehog** [comment]
Have the same issue with Xabber and Openfire 4.0+.
Now on Openfire 3.10.3 works fine. If you need plugins for old version ask in PM.

**Comment by boomstick8x** [comment]
Same issue here

**Comment by QomariSanjaya** [comment]
I have same issue, using Openfire 4.0.2 + Xabber 1.0.30.
Openfire 4.0.2 with Conversations, Yaxim, IM+ is just work fine.
Xabber 1.0.30 with another XMPP server is just work fine.
I dont know this is bug on Openfire 4.0.2 or Xabber 1.0.30.
And this issue reported nearly a half years ago but still no resolution.

**Comment by ROKAISAKKON** [comment]
Same issue here,
Ubuntu 14.04.5 LTS
Openfire 4.0.3
Java 1.8.0_101-b13
Xabber 1.0.30

**Comment by wrooot** [comment]
Fixed in the latest version (2.x).
