### ISSUE TITLE
Bug: Strange disk and network activity with opened accounts page

### ISSUE THREAD

**Issue by Testertime** [redsolution/xabber-android#621]
I have seen this in the latest version of Xabber Dev on f-droid.org, version 1.0.74. These are the steps to reproduce:
- Add a Jabber account if you haven't done yet
- In the main contacts list window, click on the menu button, and touch on your XMPP account (it has your ID there, like myname@server.net)
- The strange activity starts. It is gone when I'm going back again.

Sadly I wasn't able to find interesting information about this via debugging, also because I haven't seen the option in Xabber about writing debug logs. But luckily it seems to be easy to reproduce.

Other information:
- Android 4.4 r5, from android-x86.org
- VirtualBox 4.3.12
- Tested with Jabber account on jabber.de

![2016-03-13_164613](https://cloud.githubusercontent.com/assets/17813048/13729721/38b4428c-e93c-11e5-9549-732f423ce6a1.jpg)
Backup screenshot when the one above doesn't work: http://abload.de/img/2016-03-13_1646138fqbk.jpg

Thanks in advance!

**Comment by grigoryfedorov** [comment]
Hi! That must be your account's vCard loading.
