### ISSUE TITLE
SyncManager

### ISSUE THREAD

**Issue by patelawp** [redsolution/xabber-android#622]
There is one entry in **prefences.xml** file
`<string-array name="managers">`
...
`<item>com.xabber.android.data.roster.SyncManager</item>`
...
`</string-array>`
But I didn't find **com.xabber.android.data.roster.SyncManager** class.
Where to find?

**Comment by grigoryfedorov** [comment]
We do not sync contacts now. This line should be removed, thanks.

**Comment by patelawp** [comment]
Okay, Thanks for reply.
I have one more problem. I'm getting **compose** status when user start typing but I don't get **online** status. User status shows **offline** always, except composing
