### ISSUE TITLE
Bad class file magic and ProcessException

### ISSUE THREAD

**Issue by GunaseelanArumaikkannu** [redsolution/xabber-android#623]
I am getting following two errors while import this app.

Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

Error:Execution failed for task ':xabber:transformClassesWithDexForBetaDebug'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

**Comment by grigoryfedorov** [comment]
Hi! Try to use java 7

**Comment by GunaseelanArumaikkannu** [comment]
Super bro :+1: Its working. Thank you :100:
