### ISSUE TITLE
Last active branch.

### ISSUE THREAD

**Issue by rhonyabdullah** [redsolution/xabber-android#625]
I see there's classic, develop, feature/mam, feature/tablet_design, feature/ui_refactoring and master branch, what is the current active branch ? Would be good if somebody want to give some explanation about:

- Master : (i think every body know what is the purpose of this branch)
- Develop : (i think every body know what is the purpose of this branch)
- Classic : this branch is for ...
- Feature/mam : this branch is for ...
- Feature/mam : this branch is for ...
- Feature/ui_refactoring : this branch is for ...

According to this [page](https://crowdin.com/project/xabber), this project need Indonesian translation, may be i can help.

Thanks.

**Comment by grigoryfedorov** [comment]
Hi! Thanks for question. 
We should update the readme, you're right.
I've done some merging, now develop is up to date (but surely, not stable enough).
classic is for Xabber Classic only (fine old Xabber with old Androids support)
And feature/tablet_design contains some code for two panels UI, but is out of date. 

You can register on crowdin and apply to become Indonesian translator. All our translations (except Russian) made by volunteers, thanks to them.

**Comment by moshpirit** [comment]
Is there any chance you'll include HTTP upload to Xabber Classic? Is it even possible? :) 

Thanks for your work! 

PS: **Just curious**, why is the next update taking more time than the others?

**Comment by grigoryfedorov** [comment]
@moshpirit we do not have plans to make any changes to Xabber Classic. I think, it's much more easier now to add support for old Android to current Xabber, but does it really important?

Next update going to contain MAM, Carbons and some internal changes which took some time to implement. And now we're thinking about how to change preferences concerning history storage.

**Comment by rhonyabdullah** [comment]
Sorry, what is MAM ? And what kind of "carbons" that will going to use ? Can you refer to me links about that so i can learn more, thanks.

**Comment by moshpirit** [comment]
Thanks for the answer, very complete!! I really appreciate it! :)

[This is MAM](xmpp.org/extensions/xep-0313.html)  
Does exist several types of Carbons? AFAIK, [there's only one](xmpp.org/extensions/xep-0280.html)

**Comment by grigoryfedorov** [comment]
[Message Archive Management](http://xmpp.org/extensions/xep-0313.html)
[Message Carbons](http://xmpp.org/extensions/xep-0280.html)
