### ISSUE TITLE
Multi window mode in Android N: Chat does not update

### ISSUE THREAD

**Issue by daviessm** [redsolution/xabber-android#630]
When Xabber is the "secondary" window (i.e. the other window has focus) in multi-window mode in the Android N Developer Preview, incoming chat messages to the currently open chat don't update the view with the new messages. Once focus is brought back to the Xabber window by tapping it, the 
messages appear.

http://developer.android.com/preview/features/multi-window.html

**Comment by andrewnenakhov** [comment]
@daviessm i've just checked it, messages appear immediately on current Xabber Beta.
