### ISSUE TITLE
Get roster contact by using jid 

### ISSUE THREAD

**Issue by GunaseelanArumaikkannu** [redsolution/xabber-android#638]
`ProviderManager.addIQProvider("query",
                    "jabber:iq:search", new UserSearch.Provider());
            ProviderManager.addExtensionProvider("x",
                    "jabber:x:data", new DataFormProvider());
            ConnectionThread connectionThread = AccountManager.getInstance().getAccount(account).getConnectionThread();
            XMPPConnection connection=connectionThread.getXMPPConnection();
            ProviderManager.addIQProvider("vCard",
                    "vcard-temp", new VCardProvider());
            UserSearchManager searchManager = new UserSearchManager(connection);
            Form searchForm;
            try {
                searchForm = searchManager.getSearchForm("username." + connection.getServiceName());
                Form answerForm = searchForm.createAnswerForm();
                answerForm.setAnswer("Username", true);
                answerForm.setAnswer("search", user);
                ReportedData data = searchManager.getSearchResults(answerForm, "username." + connection.getServiceName());

```
            if (data.getRows() != null) {
                for (ReportedData.Row row: data.getRows()) {
                    Log.i("Iteartor values......", " " + row.getValues("jid").size());
                    user = row.getValues("jid").get(0);
                    Log.i(TAG, "user : " + user);
                    for (String value: row.getValues("jid")) {
                        Log.i("Iteartor values......", " " + value);
                    }
                }
                Toast.makeText(getActivity(), "Username Exists", Toast.LENGTH_SHORT).show();
            }
        } catch (SmackException.NoResponseException e) {
            e.printStackTrace();
        } catch (XMPPException.XMPPErrorException e) {
            e.printStackTrace();
        } catch (SmackException.NotConnectedException e) {
            e.printStackTrace();
        } catch (Exception e){
            e.printStackTrace();
        }`
```

So now I can get the jid of user by this code. Now I want to know how to get other details like name, avatar, status for this user. Any help will be highly appreciable.

**Comment by andrewnenakhov** [comment]
This issue tracker should not be used for such questions. Try Stackoverflow perhaps.?
