### ISSUE TITLE
Auto Away issue with Samsung S7

### ISSUE THREAD

**Issue by Tangocarrot** [redsolution/xabber-android#640]
I recently downloaded Xabber onto Samsung S7 to use an Olark XMPP live chat account. Had the Auto Away setting on Never as recommended. Connection is lost when the phone goes to screen lock mode.
Was using an S4 before and did not have this problem.
Have contacted Olark about this but they could not help. Can you?
Many thanks.

**Comment by rfc2822** [comment]
You have to disable energy saving for Xabber in your S7 settings.

**Comment by andrewnenakhov** [comment]
Yes, Samsung phones are known to aggressively shut down all apps that are active in background.
