### ISSUE TITLE
Handle asynchronous messages

### ISSUE THREAD

**Issue by sagarnayak** [redsolution/xabber-android#642]
I have ejabberd at my server side and xabber at my client side. so if there are 100 offline messages and my client comes online then the xabber gets flooded with 100 messages at a time. in this condition how xabber handles it ? how it gets all the messages in same order as it was in server ?

**Comment by casperklein** [comment]
I can confirm this.

How to reproduce: Send 100 messages (or less ;-) to an jabber account and then connect with xabber. All messages are received, but some of them are not in the right order.

**Comment by andrewnenakhov** [comment]
We plan a solution for this issue in the works - clients should use only server-side timestamps (even for outgoing messages) and server should timestamp traffic coming through in any direction.
