### ISSUE TITLE
Reccurrent disconections

### ISSUE THREAD

**Issue by galuel** [redsolution/xabber-android#643]
Using Xabber on Android last version up-to-date, I have many random disconnections / connections since some days. Before updating last Android version it worked well without disconnections. It is now difficult to know what happens on my chat, I need to disconnect from internet and reconnect to force Xabber to reconnect.

**Comment by climf** [comment]
disconnections from what?

**Comment by andrewnenakhov** [comment]
@galuel New Xabber has debug log option, enable it and it'll start generate log files. attach them here or post extracts from it at times of disconnection. Better create separate issues for each encountered type of disconnection.
