### ISSUE TITLE
Constantly crashes

### ISSUE THREAD

**Issue by iamsimakov** [redsolution/xabber-android#644]
Constantly crashes when I leave the dialog by pressing the upper left or button Back. I use beta version on htc. I send report from device.

**Comment by adde9708** [comment]
well it is the beta one i recommend you use the non-beta one :)

**Comment by adde9708** [comment]
Probably wont crash then. Cause it works perfectly for me the regular one haven't even tried the beta one yet :)

**Comment by adde9708** [comment]
i*

**Comment by casperklein** [comment]
I am using also the beta branch and have no issues with crashes. Which dialog are you talking about?

**Comment by iamsimakov** [comment]
Not beta version is stable. Close
