### ISSUE TITLE
Xabber update

### ISSUE THREAD

**Issue by nadimhd** [redsolution/xabber-android#647]
Why don't you guys update the xabber? There is no private option in conference...

**Comment by moshpirit** [comment]
👍 +1

**Comment by JeremyRand** [comment]
The `develop` branch is getting regular updates, but no releases are being tagged there.  Are the commits that change the version (such as https://github.com/redsolution/xabber-android/commit/53e03ecca5dd485c342047a69a22c80d1c4cd2fc or https://github.com/redsolution/xabber-android/commit/be722ad90e246123190f179b4c9d1bf6cc549fe8 ) intended to be releases?  If so, is there a reason that they are not being tagged as releases?

**Comment by grigoryfedorov** [comment]
Hi everyone!
We're working on next Xabber release. These versions are for internal testing, they have some problems so far.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Thanks @grigoryfedorov .  Feel free to decline to answer this, but may
I ask whether the next release is expected to be (ballpark) closest to
a couple months from now, 6 months from now, or significantly longer
than 6 months from now?  (I'm not in a hurry, the latest release is
working just fine for me, so please don't feel any pressure from my
end.)  :)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYhgIzAAoJELPy0WV4bWVwVGEQAMVpIwpEak7ULG+071bPpBYA
qcbHs4DwdU+szNvxApi5PIwvf0mHoewKWBYGX3ihvo8A3s/FKYBZCxMTypXn9Eqc
QbPHOgbKvTK8z7llR2wbFyC8UT12kk3vkW2ZStqmjxmE8sqZCAAfR+3cMOlWdNg5
4mZH11vMojLlY6VU2KLJTSoB4XERvh/iJOldZsiQdpTeZXUpnTaEnYkHCcmB9OIb
6yKZYDUaChlaTmoShgCN/2bjbg66eNA86lD6WMdOl3fL5GmvOTmlfEJ8DqozkDDS
oGtu9iOM0Gr/YDTj42AeexHhFzHrPAXZvW3jLN1M0laz5OxcE93NOiLNfdlY5wRU
jGllMFPg+sfZBvbZk+MBRics4OrRRrwDtyB+b3M8X3+E5OC6SiQZzhBMedBJhyPv
zSYOIgASBtlFG6F+SHnqDv4KaaaRUFx7I/QWlvnEPLVLdyn2G+F9/Epl/oV0nmw7
LV1dL5REHotP7aECSKkoKXU2WGJ+q4vNpimq+9O4S1Z04cVZHzKTNjFAM+zLIIaN
YPS9f6g5aqQsk6X/7xfJS+1sU2ES6iEo2AIqk8l4342jtK819eJW8jMXiz/cgZhA
MBi3pcfeeSv5R0KuBIxW8r3jfvqnJUfhEJ6czvz4WPtfq6sqLlj4JBRVbxHtY2mk
Tk9Ow3sYGl1prv8h3tqH
=aX4V
-----END PGP SIGNATURE-----

**Comment by grigoryfedorov** [comment]
@JeremyRand couple of months, I hope (also Smack 4.2 going to be released). But things can change.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Awesome, best of luck.  Looking forward to it, whenever it's ready.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYhgeHAAoJELPy0WV4bWVw7WQQAI5W5JZZT8ay4sFEnuQQxHjv
GwtKGklkm6DtRr4bzBHi8dw2aw4v8dHztp81HpL5iaCYu53sKxQmtKQ+9sFg1Nyr
MpY806frWUPEjCtvSoPBuGkgfwuwevd1Hq1ittsY34GJInfNUidXLCqtrlJ6mIw2
lSOgI/MyZc/sM1mnY5NW5tESXAy96+kun95Gl6c9Quyu/ieA75iJTmO7ybHd+ROc
oMo3ivg3UlpgqT9kTe3X5cG/DIFu1rjfpiE0RtX9q2C5ney6BJ3BRAQgS9Jt1CV+
AVpZEf9zT0UVzIEfBbawS/yHTKbaVGH5E+r9XnAWl2God2mcDdejMW/RREujAl1J
9cmj2jEe1d8O5QLvrgszpgTiMx7305CfyKYRVjh1/8G1TIWemw1lC4iUbMHuNB0W
rTv6xkbAGCIcJs+kKgXSOkB+ltfqhQcrh+sXUp3NblzooWVo+3f2pAINjSe3KG7W
FhRvBRXw2I5srNhH1eCSj/3SlYGEGMtQZMPNYUWkdDbO1ANGyBuMK5CrCKvhZAEu
MVc61+bpJ2NQBwn2wwcd9yJQFOXqaoqB/B3c9o65lrlT7QIqC9qDxyeooEsKM+Wf
PXN1ZAXBtTm3055oDQT9MqXB9OfOCPjrDJ4V+MQ9kEbXdbGPXsY2v55HZqDw0P5B
VqKd6qelAWOuYIIjAJbR
=GThd
-----END PGP SIGNATURE-----
