### ISSUE TITLE
Doesn't show messages in MUC from another client with same nick

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#649]
If you join a MUC from another client using the same nickname (same JID) as you already use with Xabber, it doesn't show messages sent from that another client. 

http://xmpp.org/extensions/xep-0045.html

> However, if the bare JID localpart@domain.tld of the present occupant matches the bare JID of the user seeking to enter the room, then the service SHOULD allow entry to the user, so that the user has two (or more) in-room "sessions" with the same roomnick, one for each resource. If a service allows more than one occupant with the same bare JID and the same room nickname, it MUST route in-room messages to all of the user's resources and allow all of the user's resources to send messages to the room;

**Comment by krushmp** [comment]
There are varying server preference to factor in your scenario

**Comment by krushmp** [comment]
Oh I do love me some samsung autoincorrect transmographying my posts into Engrish. 😬

**Comment by wrooot** [comment]
Fixed in the latest version (2.x).
