### ISSUE TITLE
xabber project was closed?

### ISSUE THREAD

**Issue by amoskong** [redsolution/xabber-android#653]
We didn't see any update from last Dec? And the officinal hongouts doen't work in my cell phone.

xabber is a good option in the past, but it doesn't work now :-( I'm investigating if it's blocked by google, or caused by device issue.

**Comment by ItchyBugReporter** [comment]
I can't answer the first question regarding the update (I'm not a Xabber developer, and I'm guessing you're using Google Play Store), but I *think* I can answer the question regarding Hangouts.

Xabber is a chat client for Jabber (a.k.a. XMPP) servers. The old Google Talk service is (was) a Jabber server, but Hangouts is not. Google basically abandoned  Jabber in favor of their own Hangouts protocol. Google Talk is still there, but they officially don't maintain it anymore.

I don't know if "upgrading" from Google Talk to Hangouts will affect your ability to log in to Google Talk from Xabber, I've been avoiding Hangouts like the plague (I need to chat from several platforms Hangouts doesn't work on). Just in case it helps, here is the server information you'll need to plug into Xabber for Google Talk:

User name: <your user name>@gmail.com (I don't know if you need to change the @gmail.com part for Google Apps accounts)
Server: talk.google.com
Port: 5222 (should be the default anyway)
Enable encryption: Yes
Allow plaintext passwords: Over ecnrypted connection only

This works for me in both Xabber and in my desktop chat client (Psi+), but again I can't garuntee it will work if you've "upgraded" to Hangouts.

**Comment by kongove** [comment]
Thanks for your reply, I will try later.

Right now, I switch to hangouts, I used Xabber to avoid installing unsupported google service/app in my mobile. However I found a solution for global proxy. Hangouts works for me on Mac, mobile.

**Comment by krushmp** [comment]
android: conversations, chatsecure, jitsi

ios: chatsecure

osx: jitsi 
windows: jitsi
linux: jitsi
