### ISSUE TITLE
HTML entities not decoded in OTR conversation with someone using Pidgin

### ISSUE THREAD

**Issue by Takiro** [redsolution/xabber-android#654]
When you are in a conversation with someone who uses Pidgin with pidgin-otr HTML entities are not decoded when message is received. It only happens as long as OTR is active and the conversation is private.  

Steps to reproduce:  
- Login to xabber on android.  
- Start conversation with someone who uses pidgin with OTR.
- (Optional) the other messenger sends `<3`
- (Optional) the message revieved is `<3`
- Start private conversation
- The other messenger sends `<3`
- The message recieved is `&lt;3` but should be `<3`

As far as I can tell it happens with all HTML entities if the conversation is private and only on xabbers side. Pidgin shows them just fine when sending a otr message from xabber.  
It doesn't happen when sending from xabber to xabber so maybe it's a bug in pidgin or pidgin-otr.

**Comment by casperklein** [comment]
I think, this was fixed some time ago. Have you tried the development branch? I just tried it and couln't reproduce this with the dev branch.

**Comment by Takiro** [comment]
Nope, I didn't, sorry. It happens with xabber dev 1.0.74, installed with F-Droid.
Since it's called xabber dev I blindly assumed it's from the development branch.

**Comment by casperklein** [comment]
Current dev branch version is 1.0.105. I guess that f-droid is using the master branch (which is v 1.0.74).

**Comment by andrewnenakhov** [comment]
Was fixed
