### ISSUE TITLE
Suppress "Joined Conference", "Left Chat" Messages

### ISSUE THREAD

**Issue by tparikka** [redsolution/xabber-android#655]
I use Xabber to connect to several high-traffic conferences and regularly see my chat history cluttered with "joined conference", "left chat" messages. Is it possible to add an option to suppress these messages in the chat log so that there is more space for the messages sent by the actual users?

![screenshot jun 27 2016 15-19-42](https://cloud.githubusercontent.com/assets/7715790/16394461/f0a0f9d0-3c7a-11e6-8a0b-c28faec4f2b8.png)

**Comment by jaymarin** [comment]
It's possible turn off in Xabber Settings-Chat-Show status changes-Never

**Comment by tparikka** [comment]
I looked for this but couldn't find it. Thanks for your response!
