### ISSUE TITLE
Add support for omemo

### ISSUE THREAD

**Issue by tanty** [redsolution/xabber-android#657]
Please, add support for this XEP:
https://conversations.im/omemo/

**Comment by krushmp** [comment]
I second this wise suggestion.  OMEMO is even easier for the typical user than OTR

This is how we convert people from sms texting to #JabberTexting

**Comment by JonasT** [comment]
For what it's worth, there is already a ticket for this here: https://github.com/redsolution/xabber-android/issues/540

**Comment by tanty** [comment]
Duplicated of #540

**Comment by bqv** [comment]
It's 2025 now. Has the position been rethought? Redsolution no longer operates in Russia. What is the reason for not implementing OMEMO now?
