### ISSUE TITLE
Conference authorization error

### ISSUE THREAD

**Issue by jaymarin** [redsolution/xabber-android#659]
Hello
We use Openfire server and Xabber client for android for work in our company. Also we use conference rooms(Group Chat Rooms) on Openfire and they are connected on users phones in Xabber. Users often receive messages from conference room - authorization error
![xabber4](https://cloud.githubusercontent.com/assets/20456125/16873877/a5cd99d6-4a9e-11e6-998d-38effeb280fd.JPG)
. I think messages appear when connection is droped. How can fix this problem? Which setting can change? Thank you.
![xabber](https://cloud.githubusercontent.com/assets/20456125/16841012/12275e56-49e0-11e6-9321-1d01e8021cf9.JPG)
![xabber2](https://cloud.githubusercontent.com/assets/20456125/16841087/510ddc30-49e0-11e6-8d6e-3fcd4b524c9e.JPG)

**Comment by sivabe35** [comment]
very often I am  Getting this Authorization error. Any Ans?

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
