### ISSUE TITLE
Regular Vs VIP apk?

### ISSUE THREAD

**Issue by BuenasIdeas** [redsolution/xabber-android#661]
Dear friends,

I've seen at Google Play this two download options. What's the difference? (not only the price)

Thank you in advance for your support && thank you x 10 for sharing the code.

**Comment by casperklein** [comment]
No difference, except the application icon.

> This VIP version of Xabber is in no way any better than regular version of Xabber, gold coin on an application icon being it's only distinct feature. It is very useful to show off how gorgeous you are when buying something that anyone can get for free.
