### ISSUE TITLE
 Xabber ignores capital letters in resource identifier on replies

### ISSUE THREAD

**Issue by litnialex** [redsolution/xabber-android#665]
From message log audit:

`<message xmlns="" id="VS3nT-15" to="test3@somdomain.com" type="chat" from="test1@somdomain.com/android8f6BnhWV">`
test3 gets it. Reply:
`<message xmlns="" id="tTDgG-121" to="test1@somdomain.com/android8f6bnhwv" type="chat" from="test3@somdomain.com/androidniD7X0SQ">` 
test1 doesn't see reply.

According to XEP-0029 Resource identifier is case sensible. But as we see there is no capital letters in resource identifier in reply.

Using xabber version 1.0.30 on both devices. XMPP server is OpenFire 4.0.3.

**Comment by Str4tocaster** [comment]
Xabber 2.0.2 (355) don't have this problem.
