### ISSUE TITLE
Self-Signed certificates.

### ISSUE THREAD

**Issue by RobertZenz** [redsolution/xabber-android#666]
Is it possible to use Xabber with servers which are using a self-signed certificate?

When trying to connect to one the client just sits there with "Connecting..." but doesn't seem to do anything.

**Comment by casperklein** [comment]
Yes. Just tested it. I get a prompt, asking me to accept the certificate or not.
Under Settings - Security there is an option "Check server certificate" or similar. Did you try that?
Which version did you use? You can try the _dev_ or the even newer _smack_4.2_ branch.

Or just don't use a self signed certificate :) You can get some for free at startssl or letsencrypt.

**Comment by RobertZenz** [comment]
Thank you for the fast response. I just tried again and now it connects without hassle. Curious.

Yes, that option is/was unchecked (so it is ignoring certificate errors). This is awesome that you have this option! Thank you! I wish all applications which are dealing with certificates would have such an option.

So, sorry for wasting your time and thank you for the fast response and an awesome app.
