### ISSUE TITLE
More file upload issues

### ISSUE THREAD

**Issue by sbrl** [redsolution/xabber-android#669]
Hello again,

I've just been reconfiguring the file upload component on my jabber server at `starbeamrainbowlabs.com` again, such that files appear over at `https://im.starbeamrainbowlabs.com/`. After performing the reconfiguration, I tried it with Xabber, but it didn't work and I got a red cross!

I tried doing it manually with Pidgin's XMPP Console & `curl`, but it worked fine ([proof](https://im.starbeamrainbowlabs.com/upload/7c0239de-2bf7-4ac5-a8d4-012f43aefc18/SBRL%20Twitter%20Header.png), available for ~30 days)!

I need to inspect Xabber Beta's logs in order to determine the problem, but I can't seem to get it to work :confused:

Can anyone help me please?

Thanks.

**Comment by sbrl** [comment]
Upon further inspection, it seems that _Conversations_ is able to send images ok (it even gets a green tick!), but when Xabber receives it, it gets confused and doesn't receive the message :-(

Upon further thought, I think the problem may be related to the fact that I accept SSL client certificates optionally. Does Xabber's SSL library support this?

**Comment by sbrl** [comment]
Theory DEBUNKED! That doesn't seem to be the issue - I've just disabled it.

Thoughts?

**Comment by casperklein** [comment]
fyi:

Xabber uses XEP-0363 (must be enabled on the xmpp server) and Conversation using XEP-0166/XEP-0234 (I guess).

So for example, If xabber "sends an image" to an other client, it basically sends an URL. Its up to the receiver client to display the image inline or just represent the URL (which can be opened to display the image in a browser or so).
The other way, sending an image from conversation to xabber does not work at all (afaik).

**Comment by sbrl** [comment]
The issue in having is that Xabber can't send images either. It just fails. . Thankfully, the latest closed beta of Xabber fixes the issue ☺


-- Starbeamrainbowlabs (keybase.io/sbrl)

-------- Original message --------

**Comment by climf** [comment]
@sbrl please quote much less poorly

**Comment by sbrl** [comment]
@climf Oops! I think I replied to this in an email, an d GitHub got confused. I've cleaned it up.
