### ISSUE TITLE
Stream management support

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#67]
http://xmpp.org/extensions/xep-0198.html

**Comment by gjedeer** [comment]
![Bountysource](https://www.bountysource.com/badge/issue?issue_id=1025378)

**Comment by tejasinamdar** [comment]
We have developed the plugin to ensure that no messages are lost (in the context of Openfire). Using Openfire, in the presence of a weak network, messages/packets are lost. Hence, to ensure deliveries (at-least-once) and no message/packet losses we have developed the plugin. The plugin ensures 'Stanza Acknowledgements' (the ability to know if messages have been received by one's peers) with no losses (at-least-once deliveries). 
See 'https://www.atklique.com/bridge/blog/?q=node/5'.

**Comment by alanthehat** [comment]
Thank you andrewnenakhov

**Comment by SafwatHalaby** [comment]
@busybit
[Conversations.](https://github.com/siacs/Conversations)

**Comment by sbrl** [comment]
This is getting really bad. Recently on the mobile network I've just 10% of messages sent / received have got through. I don't want to, but I might have to switch out from Xabber temporarily while this is implemented.

**Comment by schtobia** [comment]
I've thrown in an additional $15 bucks. This issue needs to be done.

**Comment by denschub** [comment]
Smack supports stream management since 4.1.0...

**Comment by Ape** [comment]
Why is this issue still open if #595 was merged?

**Comment by sbrl** [comment]
@Ape Good question. I'll have to try and see if I am dropping any messages now.

**Comment by LogicParrot** [comment]
Note that "Stream Management" does not guarantee messages are never dropped. In the case where a client disconnects and stays offline from a while,  stream management will timeout. If a message was pending to be sent to said client and such a timeout occurs, then Ii is up to the server implementation to either notify the sender of an error, or store the message and treat it as a message sent to an offline contact.

The latter behavior is required for a true 100% guarantee of security. So pick the right server. I know that Ejabberd optionally supports the latter option via the [resend_on_timeout](https://docs.ejabberd.im/admin/guide/configuration/#listening-module) listening module setting.

**Comment by LogicParrot** [comment]
Note that "Stream Management" alone does not guarantee messages are never dropped. In the case where a client disconnects and stays offline from a while,  stream management will timeout. If a message was pending to be sent to said client and such a timeout occurs, then it is up to the server implementation to either notify the sender of an error, or store the message and treat it as a message sent to an offline contact.

The latter behavior is required for a true 100% guarantee of security. So pick the right server. I know that Ejabberd optionally supports the latter option via the [resend_on_timeout](https://docs.ejabberd.im/admin/guide/configuration/#listening-module) listening module setting.

**Comment by LogicParrot** [comment]
Note that "Stream Management" alone does not guarantee messages are never dropped. In the case where a client disconnects and stays offline from a while,  stream management will timeout. If a message was pending to be sent to said client and such a timeout occurs, then it is up to the server implementation to either notify the sender of an error, or store the message and treat it as a message sent to an offline contact.

The latter behavior is required for a true 100% guarantee of delivery. So pick the right server. Ejabberd optionally supports the latter option via the [resend_on_timeout](https://docs.ejabberd.im/admin/guide/configuration/#listening-module) listening module setting.

**Comment by sbrl** [comment]
@LogicParrot My server should be configured to support both stream management and storing messages sent to offline contacts.

**Comment by weiss** [comment]
You don't usually want the server to write such pending messages to offline storage unless you _know_ the recipient wasn't online with a second device which already received those messages (by means of [carbon copies][1], for example).  ejabberd's `resend_on_timeout` option can be set to `if_offline` which does the right thing™ in most but not all cases.  The details are explained in an [FAQ entry][2].

The proper way to ensure reliable delivery (and at the same time, multi-device sync) is to use [MAM][3].

[1]: http://xmpp.org/extensions/xep-0280.html
[2]: https://www.ejabberd.im/faq/tcp
[3]: http://xmpp.org/extensions/xep-0313.html

**Comment by LogicParrot** [comment]
Can MAM act as a complete substitute for Carbon Copies and/or Stream Management?

**Comment by weiss** [comment]
No, you want to use carbon copies to synchronize online clients and MAM to let offline clients catch up.  You also want to continue using stream management to figure out which _outgoing_ messages must be resent after network outages, and for quick stream resumption.

**Comment by denschub** [comment]
@grigoryfedorov do you mind closing this feature request?

**Comment by ItchyBugReporter** [comment]
I say keep it open. It's definitely a must-have for mobile-only users.

**Comment by denschub** [comment]
This was implemented in #595 almost 8 months ago.

**Comment by ItchyBugReporter** [comment]
Ah, I didn't realize you've already submitted the code for it. Looks like it just needs to be merged in :-)

**Comment by denschub** [comment]
It, uh, was merged 8 months ago. That's the reason I insist on having this issue closed, because this is resovled. :)

**Comment by ItchyBugReporter** [comment]
If it's been merged, then github is lieing to me about the contents of the files you changed. Neither of the files referenced in your pull request have your changes in Redsolution's repository.

**Comment by denschub** [comment]
https://github.com/redsolution/xabber-android/blob/develop/xabber/src/main/java/com/xabber/android/data/connection/ConnectionThread.java#L95-L97

**Comment by sbrl** [comment]
Just a note: I still appear to be dropping messages in both directions when switching networks on my phone (e.g. 3G <-> WiFi or moving mobile network cells).

**Comment by ItchyBugReporter** [comment]
@denschub Ah, I was looking at the master branch, not the dev branch. Whoops.

@sbrl Since it's been merged into development, I'm guessing you'll need to use the development version of Xabber for the time being if you want to get stream management support.

**Comment by sbrl** [comment]
@ItchyBugReporter Right. It'll be in the next beta release then I assume?

**Comment by ItchyBugReporter** [comment]
I'm the wrong person to ask, I'm not a developer for Xabber, and other than this particular thread on the issue tracker I have no communication with the Xabber developers.

I do know that the version on FDroid (which uses the development branch) was built _after_ the merge, so if you're using the FDroid version you probably already have it.

**Comment by denschub** [comment]
@grigoryfedorov please... close this issue. ;)

**Comment by sbrl** [comment]
Ping @a-iv

**Comment by andrewnenakhov** [comment]
Implemented in v2.0.

**Comment by gjedeer** [comment]
@andrewnenakhov it seems this is implemented but you did not claim the reward in bountysource, check it out if interested https://www.bountysource.com/issues/1025378-stream-management-support
