### ISSUE TITLE
invalid MUC can't be deleted

### ISSUE THREAD

**Issue by bugtrapper** [redsolution/xabber-android#670]
I accidentally tried to join a conference with nickname@conference instead of conference@server. Now, every time I start up Xabber, I get a error message for joining the invalid MUC and it's back in my contact list - even though I have deleted the invalid conference from my contact list the last time I started Xabber.

(Xabber 1.0.74)

**Comment by Str4tocaster** [comment]
Xabber 2.0.2 (356) doesn't have this bug.
