### ISSUE TITLE
To run this with android studio is just like begging the moon!

### ISSUE THREAD

**Issue by shahidkarimi** [redsolution/xabber-android#671]
Trillions of erros

**Comment by casperklein** [comment]
Same problem here. I got even quadrillions of errors, when I tried to run it in Excel or Powerpoint.

But then i realized, that all I need for building is gradle, android SDK and JDK. Puh, that saved my day.

**Comment by wiktordev** [comment]
I can't build this project with Android Studio, too. I got below error.

Error:Configuration with name 'default' not found.

**Comment by grigoryfedorov** [comment]
Hi! Please read build instructions. Hope it can help.
https://github.com/redsolution/xabber-android#build-instrustions
