### ISSUE TITLE
Block messages from users not in my contact list

### ISSUE THREAD

**Issue by readyblue** [redsolution/xabber-android#673]
Can you please add simple block from users not in my contact list?
I receive 3-4 random spams every day when on xabber.

**Comment by mis2417** [comment]
yes!  privacy lists are really, really needed. please.

**Comment by mis2417** [comment]
#615 is a duplicate

**Comment by climf** [comment]
xep-0016 is a true joy

**Comment by andrewnenakhov** [comment]
Duplicate of #21
