### ISSUE TITLE
Connection Failed to ejabberd 16.01-2

### ISSUE THREAD

**Issue by DonRichie** [redsolution/xabber-android#675]
Hello,

I try to use Xabber to connect to an ejabberd Server Version 16.01-2.
Using pidgin I can connect with the exact same credentials.

My Android Version is 7.1.1
With adb I got these log entries when I press "reconnect":

`
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager: getAppKeyStore(/data/user/0/com.xabber.android.beta/app_KeyStore/KeyStore.bks) - exception loading file key store
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager: java.io.FileNotFoundException: /data/user/0/com.xabber.android.beta/app_KeyStore/KeyStore.bks (No such file or directory)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.io.FileInputStream.open(Native Method)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.io.FileInputStream.<init>(FileInputStream.java:146)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at de.duenndns.ssl.MemorizingTrustManager.loadAppKeyStore(MemorizingTrustManager.java:338)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at de.duenndns.ssl.MemorizingTrustManager.init(MemorizingTrustManager.java:155)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at de.duenndns.ssl.MemorizingTrustManager.<init>(MemorizingTrustManager.java:133)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at com.xabber.android.data.connection.ConnectionThread.onReady(ConnectionThread.java:197)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at com.xabber.android.data.connection.ConnectionThread.createConnection(ConnectionThread.java:186)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at com.xabber.android.data.connection.ConnectionThread.access$900(ConnectionThread.java:73)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at com.xabber.android.data.connection.ConnectionThread$17.run(ConnectionThread.java:648)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-15 10:39:53.929 31344 31896 I MemorizingTrustManager:        at java.lang.Thread.run(Thread.java:761)
01-15 10:39:53.953 12409 12409 V NotificationService: pkg=com.xabber.android.beta canInterrupt=false intercept=true
01-15 10:39:53.954 31344 31344 W System.err: org.jivesoftware.smack.SmackException$NotLoggedInException: Client is not logged in
01-15 10:39:53.954 31344 31344 W System.err:    at org.jivesoftware.smack.roster.Roster.reload(Roster.java:290)
01-15 10:39:53.955 31344 31344 W System.err:    at com.xabber.android.data.roster.RosterManager.requestRosterReloadIfNeeded(RosterManager.java:133)
01-15 10:39:53.955 31344 31344 W System.err:    at com.xabber.android.data.roster.RosterManager.getContacts(RosterManager.java:123)
01-15 10:39:53.955 31344 31344 W System.err:    at com.xabber.android.ui.adapter.ContactListAdapter.onChange(ContactListAdapter.java:148)
01-15 10:39:53.955 31344 31344 W System.err:    at com.xabber.android.ui.adapter.ContactListAdapter.run(ContactListAdapter.java:441)
01-15 10:39:53.955 31344 31344 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
01-15 10:39:53.955 31344 31344 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
01-15 10:39:53.955 31344 31344 W System.err:    at android.os.Looper.loop(Looper.java:154)
01-15 10:39:53.955 31344 31344 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6176)
01-15 10:39:53.955 31344 31344 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-15 10:39:53.955 31344 31344 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
01-15 10:39:53.955 31344 31344 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
01-15 10:39:53.973 12409 12409 V NotificationService: pkg=com.xabber.android.beta canInterrupt=false intercept=true
01-15 10:39:54.957 31344 31344 W System.err: org.jivesoftware.smack.SmackException$NotLoggedInException: Client is not logged in
01-15 10:39:54.957 31344 31344 W System.err:    at org.jivesoftware.smack.roster.Roster.reload(Roster.java:290)
01-15 10:39:54.957 31344 31344 W System.err:    at com.xabber.android.data.roster.RosterManager.requestRosterReloadIfNeeded(RosterManager.java:133)
01-15 10:39:54.957 31344 31344 W System.err:    at com.xabber.android.data.roster.RosterManager.getContacts(RosterManager.java:123)
01-15 10:39:54.958 31344 31344 W System.err:    at com.xabber.android.ui.adapter.ContactListAdapter.onChange(ContactListAdapter.java:148)
01-15 10:39:54.958 31344 31344 W System.err:    at com.xabber.android.ui.adapter.ContactListAdapter.run(ContactListAdapter.java:441)
01-15 10:39:54.958 31344 31344 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
01-15 10:39:54.958 31344 31344 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
01-15 10:39:54.958 31344 31344 W System.err:    at android.os.Looper.loop(Looper.java:154)
01-15 10:39:54.958 31344 31344 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6176)
01-15 10:39:54.958 31344 31344 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
01-15 10:39:54.958 31344 31344 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
01-15 10:39:54.959 31344 31344 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
01-15 10:39:55.101 31344 31896 W System.err: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'ricl.de:5222' failed because java.net.ConnectException: Bad file descriptor
01-15 10:39:55.101 31344 31896 W System.err:    at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:605)
01-15 10:39:55.101 31344 31896 W System.err:    at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:839)
01-15 10:39:55.102 31344 31896 W System.err:    at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
01-15 10:39:55.102 31344 31896 W System.err:    at com.xabber.android.data.connection.ConnectionThread.connect(ConnectionThread.java:337)
01-15 10:39:55.102 31344 31896 W System.err:    at com.xabber.android.data.connection.ConnectionThread.access$000(ConnectionThread.java:73)
01-15 10:39:55.102 31344 31896 W System.err:    at com.xabber.android.data.connection.ConnectionThread$2.run(ConnectionThread.java:233)
01-15 10:39:55.102 31344 31896 W System.err:    at com.xabber.android.data.connection.ConnectionThread$18.run(ConnectionThread.java:674)
01-15 10:39:55.102 31344 31896 W System.err:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-15 10:39:55.102 31344 31896 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-15 10:39:55.102 31344 31896 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-15 10:39:55.102 31344 31896 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-15 10:39:55.102 31344 31896 W System.err:    at java.lang.Thread.run(Thread.java:761)
01-15 10:39:55.174 12409 12409 V NotificationService: pkg=com.xabber.android.beta canInterrupt=false intercept=true
01-15 10:39:58.645 12409 12409 W WindowManager: Attempted to remove non-existing token: android.os.Binder@af4f1c6
`

Can someone try to have a look at it?
I wonder if it is an issue with Xabber, the ejabberd server, the Android Version or the Custom ROM I use.

**Comment by tahatauqeer** [comment]
you're running ejabberd on linux or VMware?

**Comment by DonRichie** [comment]
I use Ubuntu 16.04.1 LTS 64 Bit as platform for my ejabberd. 
Inside a Virtual Machine

**Comment by tahatauqeer** [comment]
and what ip are you using as a host is xabber ?

**Comment by DonRichie** [comment]
I use "ricl.de" as host and 5222
It got and A and an AAAA Record
As mentioned this should work since it is the same configuration I use in pidgin

**Comment by DonRichie** [comment]
Thanks to a hint of a friendly xabber user I found out the Xabber APK in Google App Store and F-Droid is outdated by a year.
I used the beta version of google app store which isn't up to date, too.
After that I tried the Non-Beta version and it workes fine. In conclused the error is caused by using an unstable outdated version. 
Therefore I close the issue now. Thanks for your help.
