### ISSUE TITLE
Xabber beta is not connecting with ejabberd on virtual machine

### ISSUE THREAD

**Issue by tahatauqeer** [redsolution/xabber-android#676]
Can anyone tell me how to get the host ip on which server is running. i've installed ejabberd on linux as a virtual machine in VMWare.

**Comment by DonRichie** [comment]
I suppose you have the same problem as me. The beta version is outdated by a year. The development branch of this repo seems to have some activity. But no APK is provided.
Solution would be to use the non-beta Xabber version or compile one based on the sourcecode by yourself.

**Comment by tahatauqeer** [comment]
@DonRichie kindly send me the link of non-beta version which you're using.

**Comment by DonRichie** [comment]
This one on google app store: https://play.google.com/store/apps/details?id=com.xabber.android

**Comment by tahatauqeer** [comment]
i've tried this but it doesn't support file sharing. Beta version supports XEP-0363 HTTP file upload.

**Comment by andrewnenakhov** [comment]
I don't think this question is relevant on this issue tracker. Xabber does work with ejabberd if ejabberd is reachable and is properly set up.

**Comment by DonRichie** [comment]
Thanks, but as mentioned the reason for my problem was the outdated version of "Xabber beta" in the play store.  The usual "Xabber" apps works since it is newer than "Xabber Beta"

**Comment by andrewnenakhov** [comment]
Well actually Xabber Beta on Google Play always had newer versions than regular Xabber, as far as I know.
