### ISSUE TITLE
No Updates?

### ISSUE THREAD

**Issue by Taekus** [redsolution/xabber-android#677]
Is this project dead? cause seriously, this is one of the better XMPP Clients for Android, Conversations and ChatSecure seem to have some issues that Xabber doesn't.

Update, also include Omemo!

**Comment by JeremyRand** [comment]
This appears to be a duplicate of https://github.com/redsolution/xabber-android/issues/647 .

**Comment by Taekus** [comment]
The only simularity between my post and that post is the fact that I was asking about an update. I don't care about "private mode in conference", muc wasn't made for that purpose.

What I was asking to support is Omemo; http://xmpp.org/extensions/xep-0384.html

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Gabriel R.:
> The only simularity between my post and that post is the fact that
> I was asking about an update. I don't care about "private mode in
> conference", muc wasn't made for that purpose.
> 
> What I was asking to support is Omemo;
> http://xmpp.org/extensions/xep-0384.html

Perhaps it would make sense to have a more accurate title for this
ticket than "No Updates?", then?  :)


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYi7rDAAoJELPy0WV4bWVwafcQALWlmQSMxdyzOTtr9A4kb6T4
qeRRJnKseYUQgwtugtOuC5kIdpCViKpfA0Ly7d0vlDo5y/CNCuTCd6tS3XEkntyL
sTcQi0YcvIFGM6a7XcLbbDnkZNpSzWDD77oJnyFbvkESh+LF2h25IYHxidVVHbe2
lXMiJCfg6eUvzEUAo2SFTddrH3TyaWJ0CooDDSUb2QBK+FBbkPTq1R7OJ+SQlUmO
Fku//H/eJFDQQ0T/Wvpjsyi12SsGerCu1ftr1VwJbZkUrLF+2O0NjmGhzGn/dDSl
YFiOcyF/Bm5/wPNBFi9EIMJKrQANpIfyQ2UigvLD6JAFCqRWZ5xHCJMznn/69FEL
+uktpa8tWyMnlm+5heM9zKyTpEtPfg3eKsYuprrrsEPA9VoNquc+uit8aDNf24uf
VFnezqPrpcEaS1/pUBg/GxOYvxRNy3K3R2oIlvNfhnx32wffQXAsWhAySDjA9a50
QJpwILFwZad4yqzwYtjYEt5s4DATZLhs+/5MdMhLmL/7Tyg4ZjKF2mZxva6eg08W
vV++mXjBoEYSfYqeHoJhds42x/dpT0HRk54E4B8mYT0fPCALFNWqwHT0pnxfD6Ei
vxXjGeTpntEERYWQlYz2/J9kV5zqdjEHDgjXkcXCN0SASH7qSsQjbnpDmBgDfsQw
GrJj+KWRqarLJU0s9UZj
=qsY+
-----END PGP SIGNATURE-----

**Comment by ItchyBugReporter** [comment]
OMEMO support was already requested via Issue 540:

https://github.com/redsolution/xabber-android/issues/540

**Comment by andrewnenakhov** [comment]
@Taekus plenty of updates, stay tuned.
