### ISSUE TITLE
Cannot build APK

### ISSUE THREAD

**Issue by devmgs** [redsolution/xabber-android#679]
In the latest android studio with all updates. The build apk doenst work. For making it work 

Following lines needs to be  updated in (build.gradle of otr4j module)

```
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```

Please add this to Build instructions

**Comment by mello33** [comment]
I made it work with this build.gradle(Module:xabber)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 247
        versionName '1.0.74'
        //multiDexEnabled true
        jackOptions
                {
                    enabled true

                }

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }




    lintOptions {
        // problems with generated "applicationId" string resource
        disable 'MissingTranslation'
    }



    productFlavors {

        dev {
            applicationId "com.xabber.androiddev"
            resValue 'string', 'application_package', applicationId
        }

        beta {
            applicationId "com.xabber.android.beta"
            resValue 'string', 'application_package', applicationId
        }

        prod {
            applicationId "com.xabber.android"
            resValue 'string', 'application_package', applicationId
        }

        vip {
            applicationId "com.xabber.androidvip"
            resValue 'string', 'application_package', applicationId
        }

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
}

ext {
    smackVersion = '4.1.5'
}
configurations {
    all*.exclude group: 'xpp3', module: 'xpp3'
}

dependencies {
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:support-v13:25.3.1'
    compile 'de.hdodenhof:circleimageview:1.2.2'
    compile 'com.melnykov:floatingactionbutton:1.2.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.google.zxing:android-integration:3.1.0'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.soundcloud.android:android-crop:1.0.1@aar'
    compile 'io.realm:realm-android:0.85.0'

    compile "org.igniterealtime.smack:smack-android-extensions:$smackVersion"
    compile "org.igniterealtime.smack:smack-experimental:$smackVersion"
    compile "org.igniterealtime.smack:smack-tcp:$smackVersion"
    compile project('otr4j')
    compile project('MemorizingTrustManager')
    compile project('emojicon')
}
`
It generates xabber-beta-debug.apk file in the "xabber-android\xabber\build\outputs\apk" path.
But when I run it on my android device it crashes.

**Comment by Str4tocaster** [comment]
Latest version 2.3 (473) builds correct
