### ISSUE TITLE
New conversation button not working

### ISSUE THREAD

**Issue by Comm4nd0** [redsolution/xabber-android#683]
Hi guys,

Any idea why when clicking the new conversation button nothing happens. neither does the little android icon either. Both buttons I’m referring too are in the bottom right hand side of the screen.

Any ideas how I can trouble shoot. 

Many thanks

**Comment by climf** [comment]
is your jid signed in?

**Comment by Comm4nd0** [comment]
It's ok, we got it working ;) thank you for your resopse though!
