### ISSUE TITLE
File transfer behind NAT

### ISSUE THREAD

**Issue by 1dimitar1** [redsolution/xabber-android#688]
Hello,
I am running a private XMPP server (prosody) behind my router and cannot use Xabber to transfer files. The issue is, that Xabber is trying to establish a connection to the local IP or the "virtual host" (e.g. 192.168.1.1) on port 5281, instead of connecting to the custom host that I've specified. I guess that file transfer works just fine, if you provide your server's domain name, but as I mentioned I do not have a dedicated domain and use my router's public IP as host. Is the way that the XEP-0363 handles the file transfers compatible with my configuration at all? Should the client connect to the custom host, or to the server when file transfer is initiated? I've read that you are planning to release an update soon, could you please review this issue, in case that it is a Xabber related one?  I am also curious whether you plan a future support for Jingle (I saw a probably abandoned fork on GitHub). Thank you in advance !

**Comment by queegipus** [comment]
jingle!  :ftw:

**Comment by casperklein** [comment]
I don't get exactly your setup from your post. Are you within the same network as prosody? Are you trying from the internet through your router? 

Some general thoughts:

- Use the hostname from your temporary IP address (for a quick test)
- Or try a DynDNS service
- Did you forward all necessary ports on your router to Prosody? (tcp 5222, 5269 + 5281) ?
- Does it work with other XMPP clients (to see if it's a Xabber or Prosody Issue).
- You could ask the nice guys from Prosody. Maybe Prosody is only aware of it's local IP and communicates that to the client (just a very wild guess!).

**Comment by 1dimitar1** [comment]
Thanks for the suggestions, I figured it out. 

This is what I wanted to have: a Prosody server with SSL/TLS enabled, sitting quietly in my home network, a router with port forwarding enabled and clients from all around the world connecting to its public IP. It does not get simpler than that :)

My first mistake was in the server configuration. I assumed, that the VirtualHost MUST be either the domain, or the IP of the server. Since I do not own a domain I entered my server IP address (an internal IP). With port forwarding enabled the chat worked just fine. It turns out, that I can specify any name for the server in Prosody - so I entered my router public address as such. After this change Xabber tried to establish a connection to the router on port 5281, and not to 192.168.whatever, which looked promising. I tried sending a file, but it failed with nothing registered on the Prosody log. So I tested it out with Conversations and the file did get on the server. Everything seemed fine on the server side.    

So I downloaded the source code, compiled the latest dev version and took a peek at the Xabber log files. After spending some time on the issue and tracing several different error messages to their probable causes, it eventually came down to this - incorrect certificate! I used a self-signed root certificate to sign the server certificate, which, apparently, is something you should not do. Several sites suggested to use the root certificate to sign an intermediate one and use the latter to sign the server certificate. I did that and got a different message, compaining about mismatching names. Going deeper into the rabbit hole, I dug out, that the certificate should be issued to the corresponding domain. Note that I did get a warning from Xabber about mismathing certificate names the first time I connected, but there was an option to accept the certificate anyways, so I did it and the chat was OK with that. So I looked around, found how to trick openssl to sign a certificate for an IP address instead of for a domain, deployed the certificates on the phones and voila - file sharing is now fully functional.

**Comment by casperklein** [comment]
Hi, great to hear that you solved the problem! And thanks for the detailed feedback 😃

One further suggestions: You really should think about DynDNS. If for what ever reason, your IP changes, all your users have to change their client settings.
Another benefit would be, that you could use e.g. LetsEncrypt to get a valid certificate.

**Comment by andrewnenakhov** [comment]
@1dimitar1 @casperklein that's a very curious story, however, we believe it is not good practice to run XMPP server without proper domain name and DNS records. XMPP is all about federation and ability of users from different servers to chat with each other
