### ISSUE TITLE
Xabber with Smack 4.2

### ISSUE THREAD

**Issue by mello33** [redsolution/xabber-android#692]
Xabber is too old I guess. I have tried to get an apk file almost 1 week. Finally I got an apk but got 148 Warning in the Messages. There were deprecated java codes. Your smack version is 4.1.5 The latest version is 4.2 and there are many changes on the code as far as I know. And also you know about JDK1.8 problem. Android Studio doesn't allow to use jdk 1.7 anymmore.

Are you going to put new version of xabber. I looked at the other xmpp clients for android but I liked to use xabber. But I want to make changes accordingly but I am kinda new in Android programming. I can make small changes I want.

So if you put new version on github with smack 4.2 we can use it learn how to use smack.

Thanks...

**Comment by casperklein** [comment]
The develop branch supports smack 4.2

**Comment by mello33** [comment]
Do you mean this one?
https://github.com/redsolution/xabber-android/tree/develop

**Comment by mello33** [comment]
How can I dwonload it with git?
When I check the git link it is same with the master one. And actually I tried to download with git and it downloaded the master one. Then I download as zip file but when ı open it with Android studio it was messed up. I don't know how to download it. I guess it needs to have a different git clone link.

**Comment by casperklein** [comment]
git clone -b develop https://github.com/redsolution/xabber-android.git

**Comment by mello33** [comment]
Thank you very much. I downloaded and got the apk. It works
Thank you again.
