### ISSUE TITLE
Gradle 'xabber-android' project refresh failed -- Error:Cause: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Kishore1224** [redsolution/xabber-android#696]
Hi

Am unable to build the source in my android studio. getting this while building..

Gradle 'xabber-android' project refresh failed
Error:Cause: unable to find valid certification path to requested target

Can some one suggest me the solution to overcome this..

Thank you

**Comment by zulguamusang** [comment]
me too..  did you solve it?

**Comment by grigoryfedorov** [comment]
Hello!
Did you run 

> git submodule init
> git submodule update

as it written in readme?

**Comment by Kishore1224** [comment]
Hi 
Thanks for your reply

its solved by changing the Smack version. build successfully

**Comment by powyin** [comment]
chang which Smack version？

**Comment by Kishore1224** [comment]
compile "org.igniterealtime.smack:smack-android-extensions:$smackVersion"
    compile "org.igniterealtime.smack:smack-experimental:$smackVersion"
    compile "org.igniterealtime.smack:smack-tcp:$smackVersion"
    compile "org.igniterealtime.smack:smack-resolver-dnsjava:$smackVersion"
