### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by MudraPatel** [redsolution/xabber-android#697]
In the app, I have setup all configuration but I am not getting the push notification for Conference chat and it working for one to one chat but notification is not coming on the spot, sometimes I received notification and sometimes I won't receive. 
Please help me for solving this issue.

**Comment by grigoryfedorov** [comment]
Did you check settings->Notifiations->Notification settings -> chats and conferences?

**Comment by MudraPatel** [comment]
That I have enabled chats and conference and i received the notification.
my problem was When I am testing the application and after a certain moment on 1 one cell-phone i am able to receive the notification but on another cell-phone not able to receive notification even there is no update of conversation on another cell-phone.

**Comment by MudraPatel** [comment]
Now my Group Notification is coming properly but for one to one chat notification is not coming properly.
Still facing the same issue for one to one chat
please help me

**Comment by andrewnenakhov** [comment]
Perhaps your server does not support carbon copies and one of your accounts has higher priority, so it's receiving messages.
