### ISSUE TITLE
integrate with travis CI

### ISSUE THREAD

**Issue by graingert** [redsolution/xabber-android#7]
It is possible to support automated testing using travis CI with android

see: http://levi-wilson.blogspot.co.uk/2012/06/maven-android-travis-ci-and-more.html

**Comment by Human** [comment]
At the moment, travis CI builds fail because of a missing API key:

>java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null.

**Comment by Str4tocaster** [comment]
Done
