### ISSUE TITLE
seems to be ignoring legacy ssl and using TLS instead

### ISSUE THREAD

**Issue by badfiddler** [redsolution/xabber-android#700]
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 30000ms (~30s). While waiting for establishing TLS
at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(Unknown Source)
at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(Unknown Source)
at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(Unknown Source)
at org.jivesoftware.smack.AbstractXMPPConnection.connect(Unknown Source)
at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:761)

**Comment by zulguamusang** [comment]
exactly just like me.. dont know how to solve it :(

**Comment by grigoryfedorov** [comment]
hi! which servers do you use?

**Comment by Djangel321** [comment]
I get the same thing. I'm using Openfire 4.1.3.

**Comment by konradwilk** [comment]
I see the same issue. If you have a fix, I would be glad to test it out.

**Comment by nmhu77** [comment]
Hi, Same issue here after update.

**Comment by emvilliger** [comment]
Same issue here after recent update.

**Comment by Andy-2639** [comment]
My sister has the same problem.
Xabber is configured to use SSL but starts unencrypted.
Server: ejabberd 17.04 - expects SSL (TLS 1.0 - 1.2) on TCP 5223.

I made a packet capture:
[packet capture.zip](https://github.com/redsolution/xabber-android/files/922560/packet.capture.zip)

**Comment by marnvin** [comment]
Having same issue since last update unfortunately and therefore can't login anymore. Please look into it.

**Comment by cleme1q** [comment]
same issue for me.

**Comment by coolmaddy007** [comment]
Same issue. Please let me know what was the earlier version of apk that was released so that i can install that for the time being.

**Comment by kapitan-iglu** [comment]
Same issue here, I'm using Xabber Beta 1.0.171

**Comment by d9h02f** [comment]
Legacy SSL provides no security at all, why are you still using it?

**Comment by nmhu77** [comment]
Its not our decision, The server uses it which we want to connect,

**Comment by Andy-2639** [comment]
d9h02f
> Legacy SSL provides no security at all, why are you still using it?

Legacy SSL just means start a SSL/TLS connection immediately after establishing the TCP connection.
StartTLS means establish a TCP connection, talk unencrypted until the StartTLS command occurs and then start using SSL/TLS.

So the term "Legacy SSL" only states the way the secure connection is established and not which SSL/TLS version is used. In fact, my own jabber server requires at least TLS 1.0 when using "Legacy SSL". I whish I could require at least TLS 1.2 but the last time I tries this, Xabber wanted to use TLS 1.0 ...

This setting is comparable with FTP:
"Legacy SSL" is comparable with "Implicit FTP over TLS" (establish TCP connection, start TLS session immediatly, talk about what you want).
"StartTLS" is comparable with "Explicit FTP over TLS" (establish TCP connection, talk unencrypted, send StartTLS command, start TLS session, talk encrypted).

**Comment by casperklein** [comment]
Until the issue is fixed, you can try "xabber-legacyssl-1.0.30.apk"

Quote from Twitter:

> We've put together an old version of Xabber, check it out
> https://twitter.com/Xabber_XMPP/status/852971455012798464

**Comment by mariusft** [comment]
Problem appears since release [1.0.38](https://github.com/redsolution/xabber-android/wiki/Xabber-Version-History#1038-release-date-2015-08-05) (release date 2015-08-05)

You can use latest working build [1.0.33](https://github.com/redsolution/xabber-android/wiki/Xabber-Version-History#1033-release-date-2015-07-27), available on F-Droid archived repository, [build 206](https://f-droid.org/archive/com.xabber.androiddev_206.apk).

**Comment by d9h02f** [comment]
Thanks for the explanation, @Andy-2639.

**Comment by andrewnenakhov** [comment]
Legacy SSL is deprecated, but we've finally put it back in Xabber. Check current Xabber Beta on google play.

**Comment by kapitan-iglu** [comment]
Thanx!
Many old servers (with Legacy SSL) are still alive...

**Comment by andrewnenakhov** [comment]
Unfortunately. Legacy SSL was deprecated not without a reason - and it's not even part of XMPP standard now.

**Comment by gudnm** [comment]
I'm getting this same error on Xabber Beta

**Comment by rrjanbiah** [comment]
FWIW, I got same error in Xabber Beta too.. but after couple of refresh, it started to work. So, for me, Beta is working for this fix.
