### ISSUE TITLE
Does not connects with nimbuzz after update

### ISSUE THREAD

**Issue by shah-95** [redsolution/xabber-android#701]
Its stuck on connecting with nimbuzz, previous version worked fine , but the update do not conne ts

**Comment by andrewnenakhov** [comment]
@shah-95 check out Xabber beta, tomorrow update should contain fix for this issue. Reopen if it won't work for you. Main Xabber will be updated next week

**Comment by shah-95** [comment]
Hello Sir, xabber still has issues with nimbuzz, now it says online but none of my contacts are online and i cant see anything, but in the menu it says account online. Dont know whats the problem, bombusmod works fine. Used both latest xabber stable release and beta from play store , both have same issue.
Device : non rooted stock samsung galaxy s7 edge, android 7.0
