### ISSUE TITLE
[12 Aprl]Nicknames are not visible within conference after update.

### ISSUE THREAD

**Issue by PatchDotExe** [redsolution/xabber-android#702]
After latest update nicknames aren't visible within MUC. 
All messages seems to be send by conference, with no specified participant(list of active users is actually correct).
Using conference.xmpp.ru

**Comment by M4lr** [comment]
Same issue here. Updated today (04/12/2017), connecting to a private openfire server.
Everything is fine with Spark & Pidgin, not with the last version of Xabber.

Problem occurs in all the MUCs hosted on the server.

**Comment by grigoryfedorov** [comment]
Please check version 2.0.1 which is out now.

**Comment by M4lr** [comment]
It seems to be working fine now. 
![screenshot_20170412-231350](https://cloud.githubusercontent.com/assets/27359098/24979791/d8d7bf34-1fd5-11e7-81c5-d0f952a24d03.png)

Thanks alot.

**Comment by PatchDotExe** [comment]
Yeah. Fixed. Thanks!
