### ISSUE TITLE
Issues with latest version and self-signed-certificate

### ISSUE THREAD

**Issue by DenSA-Inc** [redsolution/xabber-android#703]
I just updated xabber to the latest version and wanted to use it with my ejabberd-instance. Of course, the servers certificate is self-signed. Although I disabled "Check server certificate" in "Options -> Security", trying to connect with my account raises an

    org.jivesoftware.smack.SmackException: java.security.cert.CertificateException:
    Hostname verification of certificate failed. Certificate does not authenticate my.domain

I was using xabber without problems before the update. But now, somehow my self-signed certificate isn't enough anymore.

(If needed I can post my complete stacktrace, I didn't do this now because typing that is very tiring)

**Comment by wrooot** [comment]
Self-signed certificates are not enough always. Newest Xabber version is using newer Smack version (library), which is why it throws this exception now. Same with other clients which has updated to the latest Smack version (like Spark for desktops).

**Comment by DenSA-Inc** [comment]
and what can i do about that?

**Comment by wrooot** [comment]
At least in Spark we had to add an option to accept self-signed certificates or ones not matching the domain. Not sure if Xabber has such interface or maybe it needs to be added.

**Comment by wrooot** [comment]
Btw, in your case it looks like certificate is issued for a different domain than what you are trying to login to. Not exactly a self-signed cert problem. And maybe you should change something about the way you have everything setup.

**Comment by DenSA-Inc** [comment]
i changed the domain name in the stacktrace to "my.domain". actually, the certificate is issued for the domain i'm connecting to.

**Comment by grigoryfedorov** [comment]
I think this issue will be fixed with AllowAllHostnameVerifier which will be used in case of not checking certificate checkbox.

**Comment by wrooot** [comment]
I understand that you have changed it, but the error says Hostname verification of certificate failed. This happens when there is a mismatch. Say you certificate is for server.domain.my, but in Xabber you put user@domain.my. What server are you using? Can you check are the certificates for your domain or some other name?

**Comment by DenSA-Inc** [comment]
@grigoryfedorov this checkbox was unchecked for me the entire time and it worked. the problem startet after the update.
@wrooot I'm using ejabberd and I'm pretty sure i entered the right hostname when the certificate-question came up during installation. But i'll check.

**Comment by DenSA-Inc** [comment]
@wrooot You were right, the certificate was not issued for my domain. **Even though** I entered my domain during the installation process (I did a dpkg-reconfigure of ejabberd). It turns out the CN of the certificate was "ejabberd", no wonder why it failed. The solution was creating a new certificate and restarting ejabberd.

**Comment by wrooot** [comment]
Glad to help
