### ISSUE TITLE
Xabber Crashes When Connected to Conference

### ISSUE THREAD

**Issue by yourealwaysbe** [redsolution/xabber-android#706]
This seems distinct from #705 since there is no obvious kicking involved.  Instead Xabber just crashes as soon as connecting to the conference.  

This is in version 1.0.155 from fdroid.

I have attached a logcat.  The offending lines seem to be

    04-15 09:34:36.871  8914  8914 E AndroidRuntime: FATAL EXCEPTION: main 
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: Process: com.xabber.androiddev, PID: 8914
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: java.lang.IllegalStateException: Request background thread message realm from UI thread
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.xabber.android.data.database.MessageDatabaseManager.getNewBackgroundRealm(Unknown Source)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.xabber.android.data.extension.muc.RoomChat.onPacket(Unknown Source)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.xabber.android.data.message.MessageManager.onStanza(Unknown Source)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.xabber.android.data.connection.ConnectionItem$3$1.run(Unknown Source)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6126)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    04-15 09:34:36.871  8914  8914 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    04-15 09:34:36.879   756  1435 W ActivityManager:   Force finishing activity com.xabber.androiddev/com.xabber.android.ui.activity.ChatActivity
    04-15 09:34:36.899   756  1435 W ActivityManager:   Force finishing activity com.xabber.androiddev/com.xabber.android.ui.activity.ConferenceAddActivity
[xabber-crash-3.txt](https://github.com/redsolution/xabber-android/files/923445/xabber-crash-3.txt)

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
