### ISSUE TITLE
Missing some messages in MUC history

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#709]
Using 2.0.1. When i connect to open_chat room at conference.igniterealtime.org, Xabber doesn't show some of the messages. It's like it has gaps at some intervals. Misses 2 messages, then shows everything (10-15 messages), then again misses a few. Comparing to Conversations, Spark (which show everything).

**Comment by Artiom-M** [comment]
The same issue. Even with stable 2.0.2 from GooglePlay. Other clients shows everything

**Comment by andrewnenakhov** [comment]
We cannot reproduce this issue on our servers. @Artiom-M @wrooot can you give us account on your servers so we can see what's going on there?

**Comment by wrooot** [comment]
How can i share the test account credentials?

**Comment by andrewnenakhov** [comment]
@wrooot email them info@xabber.com - and please provide details how to access affected conference (say how it is named). We'll try to look at it this week then.

**Comment by wrooot** [comment]
Sent. I haven't tried Xabber for a while, but as Artiom mentions it, maybe this issue is still there.

**Comment by andrewnenakhov** [comment]
@wrooot I don't see incoming email with credentials there... re-send please.

**Comment by wrooot** [comment]
Resent. Though i saw test in the chat. Thought maybe it was you.

**Comment by Artiom-M** [comment]
Additional info: the same conference works well with Xabber 1.0.74

**Comment by andrewnenakhov** [comment]
@wrooot it wasn't us yet, developer is currently ill :(

**Comment by andrewnenakhov** [comment]
Closing, since we're going to replace MUC protocol with new superior group chat protocol.
