### ISSUE TITLE
Extended message archive settings

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#71]
Account settings:
- Save preferences
- Location preferences

Chat settings:
- Save preferences

Save preferences:
- Save required (save=body, otr=forbid)
- Save (save=body, otr=oppose)
- Don't save (save=false, otr=prefer)
- Don't allow (save=false, otr=require)

Location preferences:
- Nowhere (auto=forbid, local=forbid)
- Local (auto=forbid, local=prefer)
- Remote (auto=prefer, local=forbid)
- Both (auto=prefer, local=prefer)

**Comment by andrewnenakhov** [comment]
Too complicated.
