### ISSUE TITLE
Resolving SRV DNS record fails, no retry -> cannot connect to A record

### ISSUE THREAD

**Issue by cooox** [redsolution/xabber-android#712]
Hi,
I had some trouble with reconnections when roaming or switching from wifi to mobile in Xabber 2.0.1! Maybe you can use the information to improve the connection handling in Xabber.

Setup: 
- Prosody 0.9
- Xabber 2.0.1 on Android 6, using Java DNS resolver
- SRV DNS record for the XMPP server
- A record to another server (which is a web server)

Problem: when wifi drops and Android switches to mobile, the DNS server of my provider fail to resolve the SRV record (edit: it fails, because the connection fails, see comment below). Xabber then tries to reconnect to the A record, and obviously fails. Same problem happens while roaming when the connection must be reestablished.

What I tried: I looked into Prosody first, but it's not a server issue. Then I looked into Xabber, which led me to Smack - nothing suspicious. I analysed Xabber logs and compared them with logs from logcat and could pin the problem to DNS.
```
2017-04-19_17-05-23 D/org.jivesoftware.smack.util.DNSUtil Could not resolve DNS SRV resource records for _xmpp-client._tcp.<domain>. Consider adding those.
2017-04-19_17-05-23 D/org.jivesoftware.smack.tcp.XMPPTCPConnection Trying to establish TCP connection to <domain>/<ip_of_webserver> at port 5222
```
```
2017-04-19_17-05-53 W/ConnectionThread: <user/resource>: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '<webserver>:5222' failed because: <webserver> exception: java.net.SocketTimeoutException: failed to connect to <webserver> (port 5222) after 30000ms
```
There's no problem with the record, since everything works when starting Xabber while a stable connection exists (stable mobile, wifi). I have now pointed the A record to the XMPP server as well, so people don't get mad :smile: 

- So maybe you could improve requerying the SRV record when it fails? 
- Or add a delay for DNS queries when reconnecting to make sure a stable connection to the providers DNS server is established?
- I know this is more a Smack problem, but why does a DNS query happen if the TTL cannot yet be expired? If I connect via the SRV record, and reconnect, why does it not reuse the cached SRV record?

Thank you guys for the update to Xabber 2.x, I really enjoy the UI with the new features!

**Comment by casperklein** [comment]
> the DNS server of my provider fail to resolve the SRV record.

IMHO: If it's really an issue of your provider, then I don't think Xabber could/should fix it ;-)

> So maybe you could improve requerying the SRV record when it fails?

It's common practice to take the A record, if SRV fails (NXDOMAIN). Think about a domain without  SRV records and 5 additional retries to resolve. The reconnect would take 5 times longer and still fail. I prefer a reconnect as fast as possible.

> Or add a delay for DNS queries when reconnecting to make sure a stable connection to the providers DNS server is established?

There is a connection or not. So if your mobile phone tells Xabber, there is a connection, why should Xabber delay anything? That is not, how things work.

> I know this is more a Smack problem, but why does a DNS query happen if the TTL cannot yet be expired? If I connect via the SRV record, and reconnect, why does it not reuse the cached SRV record?

The cache is cleared every time a connection is loss (which is common I think and not limited to Android).

Further things I would investigate:

- Is it really a provider issue? Test with a different one.
- Does switching to MiniDNS Resolver helps?
- Try different mobile phone brand
- If you have the opportunity, try also with Android 7 (there where a lot of things improved).

fyi: I am from Germany too and using the o2 mobile network. I've encountered no problems with roaming or switching from wifi to mobile (same setup as you, but on Android 7).

**Comment by cooox** [comment]
Thanks for the feedback!

> IMHO: If it's really an issue of your provider, then I don't think Xabber could/should fix it ;-)

I thought about rephrasing this, I of course mean "fails because the network/the DNS server does not respond fast enough".

> It's common practice to take the A record, if SRV fails (NXDOMAIN). Think about a domain without SRV records and 5 additional retries to resolve. The reconnect would take 5 times longer and still fail. I prefer a reconnect as fast as possible.

That's understandable in a setup with SRV and A aiming at the same machine. In my case it takes ~60 seconds for Smack to even recognize that A fails. Maybe we can meet in between and reduce the timeout for A records, including a requery for SRV after A fails.

> There is a connection or not. So if your mobile phone tells Xabber, there is a connection, why should Xabber delay anything? That is not, how things work.

As I said, a fresh connection with initially high RTT might lead to a race condition where Xabber immediatelly gives up on the DNS, even though 1 second later the route would be stable and fast.

> The cache is cleared every time a connection is loss (which is common I think and not limited to Android).

This is not how DNS caching with TTLs should work.. of course, a client software can decide to not cache since that's what the first-hop DNS is for. But in this special case this DNS fails, so the caching must be done on the device itself.

> Is it really a provider issue? Test with a different one.

See my rephrasing, sorry for the misunderstanding!

> Does switching to MiniDNS Resolver helps?

No, this made no difference.

**Comment by casperklein** [comment]
Just for the record: I am not involved in Xabber development ;-)

**Comment by Str4tocaster** [comment]
@cooox This issue was fixed in https://github.com/redsolution/xabber-android/commit/8fd90dff8051d73829b85f4bec042ba93240819d. Please, check it and close issue if it works.

**Comment by cooox** [comment]
Had no problems so far, closing this issue!
