### ISSUE TITLE
problem with android studio

### ISSUE THREAD

**Issue by zulguamusang** [redsolution/xabber-android#713]
Hi, suddenly i can't build this project anymore with my android studio.. anyone faced this problem before? here's my laptop spec:

i5-7200u
12gb ddr4 ram
win10 64bit
java 1.8.0_111

and here's error log while building this project:

Information:Gradle tasks [:abetopup:generateProdDebugSources, :abetopup:generateProdDebugAndroidTestSources, :abetopup:assembleProdDebug]
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
:xabber:preBuild UP-TO-DATE
:xabber:preProdDebugBuild UP-TO-DATE
:xabber:checkProdDebugManifest
:xabber:extractProguardFiles
:xabber:preProdReleaseBuild
:xabber:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:xabber:prepareComAndroidSupportAppcompatV72531Library
:xabber:prepareComAndroidSupportDesign2531Library
:xabber:preProdDebugAndroidTestBuild UP-TO-DATE
:xabber:prepareComAndroidSupportMultidex101Library
:xabber:prepareComAndroidSupportRecyclerviewV72531Library
:xabber:prepareComAndroidSupportSupportCompat2531Library
:xabber:prepareComAndroidSupportSupportCoreUi2531Library
:xabber:prepareComAndroidSupportSupportCoreUtils2531Library
:xabber:prepareComAndroidSupportSupportFragment2531Library
:xabber:prepareComAndroidSupportSupportMediaCompat2531Library
:xabber:prepareComAndroidSupportSupportV132531Library
:xabber:prepareComAndroidSupportSupportV42531Library
:xabber:prepareComAndroidSupportSupportVectorDrawable2531Library
:xabber:prepareComAndroidSupportTransition2531Library
:xabber:prepareComFrogermcsAndroiddevmetricsAndroiddevmetricsRuntime04Library
:xabber:prepareComGetkeepsafeRelinkerRelinker122Library
:xabber:prepareComMelnykovFloatingactionbutton130Library
:xabber:prepareComSoundcloudAndroidAndroidCrop101Library
:xabber:prepareDeHdodenhofCircleimageview210Library
:xabber:prepareIoRealmRealmAndroidLibrary311Library
:xabber:MemorizingTrustManager:preBuild UP-TO-DATE
:xabber:MemorizingTrustManager:preReleaseBuild UP-TO-DATE
:xabber:MemorizingTrustManager:checkReleaseManifest
:xabber:MemorizingTrustManager:prepareReleaseDependencies
:xabber:MemorizingTrustManager:compileReleaseAidl UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseNdk UP-TO-DATE
:xabber:MemorizingTrustManager:compileLint UP-TO-DATE
:xabber:MemorizingTrustManager:copyReleaseLint UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseShaders UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseShaders UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseAssets UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseAssets UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseProguardFiles UP-TO-DATE
:xabber:MemorizingTrustManager:packageReleaseRenderscript UP-TO-DATE
:xabber:MemorizingTrustManager:compileReleaseRenderscript UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseResValues UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:packageReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseManifest UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseBuildConfig UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseResources UP-TO-DATE
:xabber:MemorizingTrustManager:generateReleaseSources UP-TO-DATE
:xabber:MemorizingTrustManager:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:xabber:MemorizingTrustManager:javaPreCompileRelease
:xabber:MemorizingTrustManager:compileReleaseJavaWithJavac UP-TO-DATE
:xabber:MemorizingTrustManager:processReleaseJavaRes UP-TO-DATE
:xabber:MemorizingTrustManager:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:mergeReleaseJniLibFolders UP-TO-DATE
:xabber:MemorizingTrustManager:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
:xabber:MemorizingTrustManager:bundleRelease UP-TO-DATE
:xabber:emojicon:preBuild UP-TO-DATE
:xabber:emojicon:preReleaseBuild UP-TO-DATE
:xabber:emojicon:checkReleaseManifest
:xabber:emojicon:preDebugAndroidTestBuild UP-TO-DATE
:xabber:emojicon:preDebugBuild UP-TO-DATE
:xabber:emojicon:preDebugUnitTestBuild UP-TO-DATE
:xabber:emojicon:preReleaseUnitTestBuild UP-TO-DATE
:xabber:emojicon:prepareComAndroidSupportSupportCompat2530Library
:xabber:emojicon:prepareComAndroidSupportSupportCoreUi2530Library
:xabber:emojicon:prepareComAndroidSupportSupportCoreUtils2530Library
:xabber:emojicon:prepareComAndroidSupportSupportFragment2530Library
:xabber:emojicon:prepareComAndroidSupportSupportMediaCompat2530Library
:xabber:emojicon:prepareComAndroidSupportSupportV132530Library
:xabber:emojicon:prepareComAndroidSupportSupportV42530Library
:xabber:emojicon:prepareReleaseDependencies
:xabber:emojicon:compileReleaseAidl UP-TO-DATE
:xabber:emojicon:compileReleaseNdk UP-TO-DATE
:xabber:emojicon:compileLint UP-TO-DATE
:xabber:emojicon:copyReleaseLint UP-TO-DATE
:xabber:emojicon:compileReleaseRenderscript UP-TO-DATE
:xabber:emojicon:generateReleaseBuildConfig UP-TO-DATE
:xabber:emojicon:generateReleaseResValues UP-TO-DATE
:xabber:emojicon:generateReleaseResources UP-TO-DATE
:xabber:emojicon:mergeReleaseResources UP-TO-DATE
:xabber:emojicon:processReleaseManifest UP-TO-DATE
:xabber:emojicon:processReleaseResources UP-TO-DATE
:xabber:emojicon:generateReleaseSources UP-TO-DATE
:xabber:emojicon:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:xabber:emojicon:javaPreCompileRelease
:xabber:emojicon:compileReleaseJavaWithJavac UP-TO-DATE
:xabber:emojicon:extractReleaseAnnotations UP-TO-DATE
:xabber:emojicon:mergeReleaseShaders UP-TO-DATE
:xabber:emojicon:compileReleaseShaders UP-TO-DATE
:xabber:emojicon:generateReleaseAssets UP-TO-DATE
:xabber:emojicon:mergeReleaseAssets UP-TO-DATE
:xabber:emojicon:mergeReleaseProguardFiles UP-TO-DATE
:xabber:emojicon:packageReleaseRenderscript UP-TO-DATE
:xabber:emojicon:packageReleaseResources UP-TO-DATE
:xabber:emojicon:processReleaseJavaRes UP-TO-DATE
:xabber:emojicon:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:xabber:emojicon:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:xabber:emojicon:mergeReleaseJniLibFolders UP-TO-DATE
:xabber:emojicon:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:xabber:emojicon:transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
:xabber:emojicon:bundleRelease UP-TO-DATE
:xabber:prepareProdDebugDependencies
:xabber:compileProdDebugAidl UP-TO-DATE
:xabber:compileProdDebugRenderscript UP-TO-DATE
:xabber:generateProdDebugBuildConfig UP-TO-DATE
:xabber:generateProdDebugResValues UP-TO-DATE
:xabber:generateProdDebugResources UP-TO-DATE
:xabber:mergeProdDebugResources UP-TO-DATE
:xabber:processProdDebugManifest UP-TO-DATE
:xabber:processProdDebugResources UP-TO-DATE
:xabber:generateProdDebugSources UP-TO-DATE
:xabber:prepareComAndroidSupportMultidexInstrumentation101Library
:xabber:prepareProdDebugAndroidTestDependencies
:xabber:compileProdDebugAndroidTestAidl UP-TO-DATE
:xabber:processProdDebugAndroidTestManifest UP-TO-DATE
:xabber:compileProdDebugAndroidTestRenderscript UP-TO-DATE
:xabber:generateProdDebugAndroidTestBuildConfig UP-TO-DATE
:xabber:generateProdDebugAndroidTestResValues UP-TO-DATE
:xabber:generateProdDebugAndroidTestResources UP-TO-DATE
:xabber:mergeProdDebugAndroidTestResources UP-TO-DATE
:xabber:processProdDebugAndroidTestResources UP-TO-DATE
:xabber:generateProdDebugAndroidTestSources UP-TO-DATE
:xabber:incrementalProdDebugJavaCompilationSafeguard UP-TO-DATE
:xabber:javaPreCompileProdDebug
:xabber:compileProdDebugJavaWithJavac UP-TO-DATE
:xabber:compileProdDebugNdk UP-TO-DATE
:xabber:compileProdDebugSources UP-TO-DATE
:xabber:mergeProdDebugShaders UP-TO-DATE
:xabber:compileProdDebugShaders UP-TO-DATE
:xabber:generateProdDebugAssets UP-TO-DATE
:xabber:mergeProdDebugAssets UP-TO-DATE
:xabber:transformClassesWithRealmTransformerForProdDebug UP-TO-DATE
:xabber:transformClassesWithJarMergingForProdDebug UP-TO-DATE
:xabber:transformClassesWithMultidexlistForProdDebug UP-TO-DATE
:xabber:transformClassesWithDexForProdDebug
Running dex as a separate process.
To run dex in process, the Gradle daemon needs a larger heap.
It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at least 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environment.html
Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(jnamed$2) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(jnamed$3) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(jnamed$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Error:UNEXPECTED TOP-LEVEL ERROR:
Error:java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:	at com.android.dx.cf.direct.StdAttributeFactory.exceptions(StdAttributeFactory.java:399)
Error:	at com.android.dx.cf.direct.StdAttributeFactory.parse0(StdAttributeFactory.java:145)
Error:	at com.android.dx.cf.direct.AttributeFactory.parse(AttributeFactory.java:96)
Error:	at com.android.dx.cf.direct.AttributeListParser.parse(AttributeListParser.java:142)
Error:	at com.android.dx.cf.direct.AttributeListParser.parseIfNecessary(AttributeListParser.java:115)
Error:	at com.android.dx.cf.direct.AttributeListParser.getEndOffset(AttributeListParser.java:96)
Error:	at com.android.dx.cf.direct.MemberListParser.parse(MemberListParser.java:213)
Error:	at com.android.dx.cf.direct.MemberListParser.parseIfNecessary(MemberListParser.java:108)
Error:	at com.android.dx.cf.direct.MethodListParser.getList(MethodListParser.java:54)
Error:	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:551)
Error:	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Error:	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Error:	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Error:	at com.android.dx.command.dexer.Main.parseClass(Main.java:772)
Error:	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
Error:	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1700)
Error:	at com.android.dx.command.dexer.Main.processClass(Main.java:755)
Error:	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:723)
Error:	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
Error:	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1653)
Error:	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
Error:	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
Error:	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Error:	at com.android.dx.command.dexer.Main.processOne(Main.java:677)
Error:	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:569)
Error:	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
Error:	at com.android.dx.command.dexer.Main.run(Main.java:275)
Error:	at com.android.dx.command.dexer.Main.main(Main.java:245)
Error:	at com.android.dx.command.Main.main(Main.java:106)
:xabber:transformClassesWithDexForProdDebug FAILED
Error:Execution failed for task ':xabber:transformClassesWithDexForProdDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --multi-dex --main-dex-list C:\Users\Mohd Zulkifli\MyApk\xabber\xabber\build\intermediates\multi-dex\prod\debug\maindexlist.txt --output C:\Users\Mohd Zulkifli\MyApk\xabber\xabber\build\intermediates\transforms\dex\prod\debug\folders\1000\1f\main C:\Users\Mohd Zulkifli\MyApk\xabber\xabber\build\intermediates\transforms\jarMerging\prod\debug\jars\1\1f\combined.jar}
Information:BUILD FAILED
Information:Total time: 2 mins 14.511 secs
Information:32 errors
Information:3 warnings
Information:See complete output in console

**Comment by Human** [comment]
FYI, you can create a gradle.properties file in the project's root directory, with these contents:

```org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xms256m -Xmx2048m```
