### ISSUE TITLE
Privacy issue: chat history now always stored to device's memory. Users of early versions became vulnerable

### ISSUE THREAD

**Issue by wangchenglee** [redsolution/xabber-android#715]
In version 1.0.30 there was an option to disable writing chat history to phone's storage:
Account -> Store message history -> Don't store

In new versions, the option "Don't store" is not available anymore and chat history (even OTR!) is always stored on device.

This is serious security flaw as once stored on device, information can be recovered later by scanning with special software.

What is worse, all users who used version 1.0.30 and were confident that history is never saved, by updating to a new version of Xabber they are silently forced to save history on device without knowing that.

Please fix this issue.

**Comment by casperklein** [comment]
There is a new option in the account setting "Chat history" --> "Delete all chat messages from device before exiting Xabber."
I cannot say, if the messages are saved and deleted or if they entirely are kept in RAM.

**Comment by wangchenglee** [comment]
Deleting does not help. The concept of OTR (Off The Record) privacy is broken in this case, because once data is saved to device's storage (it is really saved in xabber 2.0), It can be recovered later by special tools. 
"Deleting chat messages" is useless as it often leaves saved data on physical storage which only makes the feeling of false confidence.

I suggest to return the ability of keeping chat history in RAM only, even if it can cause lose of unread messages during app crash. Please let users decide what is more important - reliability or safety,

**Comment by andrewnenakhov** [comment]
Actually Xabber was never intended to be a completely device-seizure proof chat app with encrypted contents. OTR allows users to feel safe that server owner and sinister guys from CIA/FBI/KGB/MI6/Google/Facebook/Microsoft won't intercept and read their messages. 

Current architecture allows us to easier provide a functional and robust chat experience, and it's much easier for us to achieve this task by storing msgs not in runtime but in realm db. So, we won't fix it. Maybe we'll add a PIN lock and do something about app data encryption, but it's not on top of our priorities list.

**Comment by SatoshiBourguiba** [comment]
The guy was right. Now, it's even worse. Chat history is always there. If this is not fixed, i'll fork the project and implement it on my own. OTR is meant to increase privacy. Storing the history defeats the whole purpose of user's security and privacy. What if the device is stolen ? You guys should learn more about what users need if you want it to be useful completely and not just Hippocratic app like many out there.

**Comment by andrewnenakhov** [comment]
> You guys should learn more about what users need 

@SatoshiBourguiba we know exactly what our paying customers need. A dozen or so cryptonerds are very vocal, but don't really add anything to our bottom line.

The harsh reality is that without paying the choice is to either accept whatever we intend to share with humanity due to our goodwill, use different software or fork app and implement whatever you think necessary.
