### ISSUE TITLE
when project is biuled

### ISSUE THREAD

**Issue by xcdf** [redsolution/xabber-android#716]
Error:Project :xabber declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :xabber:MemorizingTrustManager.

**Comment by zulguamusang** [comment]
run this first

git submodule init
git submodule update

**Comment by xcdf** [comment]
how to run git submodule init and git submodule update ?

**Comment by xcdf** [comment]
can u give the step for git submodule

**Comment by Str4tocaster** [comment]
Run in terminal:
git submodule init
git submodule update

**Comment by Str4tocaster** [comment]
@shravanteegala Open terminal, by click to "terminal" panel at the bottom of Android Studio window. Execute following commands in terminal:
```
git submodule init
git submodule update
```
Be sure that modules emojicon and memorizingTrusManager has been downloaded in your local project.
