### ISSUE TITLE
Native code?

### ISSUE THREAD

**Issue by JeremyRand** [redsolution/xabber-android#717]
Does Xabber use any native code?  If so, what language(s) is that code written in?  C/C++?

**Comment by andrewnenakhov** [comment]
Xabber is written in Java only.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Andrew Nenakhov:
> Xabber is written in Java only.

F-Droid seems to disagree, see
https://f-droid.org/repository/browse/?fdfilter=xabber&fdid=com.xabber.a
ndroiddev

> This version uses native code and is built for: arm64-v8a 
> armeabi-v7a mips x86 x86_64

Is F-Droid incorrect?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZKV6mAAoJELPy0WV4bWVwfOQQAI85KfIR27WV8237n0bZmnCG
4NOyjONkaRl1EyB+PsuiW7eucmChUQhiU7WSauknSKPUZiaedjndrlyCyxFVJHqZ
PGxmUrb9cPWXCPKe26HD4qCsv4IsE1K0yI2ra82Q5kln3m6ueR5KaQ33d4d9lUFc
RHbrUvnNngdLqwuhmmdOaQfDEHq0H6enVZOltS6GMUv/ngvGMcTC2RKEpv7uHE2k
ITGHDjqa33fLDqOUgw+GD9Y9zkj3O7o80eAxFWk1Zmkd6p1h03nfI/sw9gC7nxAP
JUzfY+LbM0ceV3f7v9VO0l1MhjMnNpU1ln1cD9Dz/CQsRY3KV+k1Scu1lnxOWu7O
2ETz9XBQwExdFErwpVpI1Eh5Kdix8bWHKGQEnKVm2MhkxVED3St9tPOi6I9KesTW
w37nnt5d+HvdXXywzzRgk3tAc59uXUVWZ0kYwQ53gS7lZ8RLSrIC4M3WX1aVW3hJ
fZAStmKxkOhburK5RFRpZYqEOp3lZhtnu0F74w1QzkdOmPcdvOm+KSSN2QueZ3XZ
WrfY6rF+jnmrrQL4DkbE4A0e5ZVaO7Tq/HppaE8z/FR5EjwS8N11Wi5QU0sQjoe4
U0DgAkZKbnpW/t6hivcQx5lGtcXKwfzfKe+jczhdDkbsULcfn/679vKXFPRlrSwd
MEKL1hQcwcbrCNONnJhd
=pplX
-----END PGP SIGNATURE-----

**Comment by andrewnenakhov** [comment]
@JeremyRand well, you may try finding non-Java code in this repository.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Andrew Nenakhov:
> @JeremyRand well, you may try finding non-Java code in this
> repository.

Are you telling me that 100% of the code that ends up in a Xabber APK
is located in this Git repository?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZKZiuAAoJELPy0WV4bWVwZLAQAJQyCX/HGUiP01wD/Xm9y5qx
LNiSBGoA0Q9MnWODVMrax1Y7Wl2m1i6QGe2FXyhvwQlWESYkrwKuCoLsxyMg2ebF
SpgUVue+RA/Daj4XFVzVXGQYa17wNBeHSy991xBhnCUYZ0DuXpa6hpt1vpVvNTk9
11R1tcmTulDaXrQ0IWAy45RmabaRIL8z09mfc+4U5q4uaqw5QXJnmeCFl+iKYZ2Z
VQj/K54wCPrp6+SM4Z6T4DjkHYiZ2ztihCJrQ+51ktsqRciNEsMO/i3Ik1D3WRGD
AViRq9nerr6qhNXz6zmMXhQXB9jJtkCTaUM2cwVlGLrDsFfvITW4g87HpJotNznK
TW12gF8h8NhGXRvqorFTPkWu3tfSqBmAbabx5jXyLcfEO2IyzoHLvVZuiJ2enX09
l5Pfv+JFFs5fgtuN8+5dd9oGSYVwwpwEWkN0EgwiuOOhysF7MXilII3Cu6oAHG+7
r+b9dcEC9Pp/2gwYnaMPv3xXsuai5KV8ISIltBkKMwl5iEIViXorvJ6jBlWopwgv
L6eQeP6sCmsF40mv+lHySH81RodQ0TmyG3sAKEwFNzvDyWxMpo8T1hsHQ8QNzF6F
hrWrJBYpRWjee9qe/JQ2Fp6KHmfZY3F5xG/Ip77zcNIhLd2J0XYwgaLvQTpBmjuR
MzIb/sENfQq9a9q3/KvP
=Lf7z
-----END PGP SIGNATURE-----

**Comment by andrewnenakhov** [comment]
I'm telling you that this discussion is pointless.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Andrew Nenakhov:
> I'm telling you that this discussion is pointless.

Indeed.  Clearly it's pointless for me to be using and recommending an
app whose developers are either incompetent or lying about its
codebase.  I will be switching to Conversations, whose developers
answered this inquiry without any difficulty or fraud whatsoever.

Nice talking to you.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZKZwEAAoJELPy0WV4bWVw1vYP/j3o5DKCxf52CtNmAabgtqHk
6N9A5PkwzrUwjgRInDA0T0v48hBKwml/sTUzqAJH5/ytTtkVWeqgDQWt7zxYF8gt
Fj9+yoR89RDEGo3joG1BMPeRio5D+dGN+IuwVlkIXqBnKdZDvPv98uwc1KhdKXcx
mcZe3bprvhVghalDq9BoopZ4FFeH72vpl2e9RLz+kf+8J1xyADC4rkCHTPG4+fgh
Zi6DLf0aRlQl1Jk+bvsJYxLY4ndHJqlUBGIE7k6fjKqXskep1pcPFjpDWuBC7Niq
GYhLyFiOwbC+gHiXSWN3yhOAwYmk91Oc/vaae3wJhIePdN9aSUYY2/z9cNDlimeJ
+uI+wC9G+i5nKyHoImC1lLnK+GBbF61o64gKfGLWkJlKCF/5oPJddIrWzoPkYkXk
QyonEJMp+H8reLlmjOd+2U4VO8+eBE5o0Ant0LZ4P2GcH7xhTHunh3+wEacOXt7K
IcRryoOiaK41KXqdMY7r6Oi/ufi67mwkU1rS3dCVFnreg1Xyqs8irUoktVR1VGCT
bO5vbxg3ezwghEZqsWPdM/ZDugLtnkgexkUVFQOSruqx/dj8hBSO2P0GgPK0faDf
ZN65p1UzhDgKt5eeD1AwudccN6rIVLMusSG4xMkHr7X4mvDeIA/cYLUgogKdb2Id
chl08nX/H3PPRxCpLPhK
=9Ixa
-----END PGP SIGNATURE-----

**Comment by andrewnenakhov** [comment]
@JeremyRand you have been answered. Anyway, I'm glad you chose to spam some other issue trackers with pointless questions.
