### ISSUE TITLE
google talk does not work anymore

### ISSUE THREAD

**Issue by sena73** [redsolution/xabber-android#718]
Hi
I used Xabber for a long time on Android to chat with other Google talk (now hangouts) users. Since last update from F-Droid repo it does not work anymore. Not sure which version was working...

**Comment by alexte** [comment]
Google is shutting down all xmpp ports, federation is already gone and xmpp clients are soon to be shut down by Google. Shame on you google. "Don't be evil" does not apply any more. Google like Facebook and others imprison their users in their island.
Your problem may be actually be Googles fault.

**Comment by sena73** [comment]
You are probably right, as older version of Xabber does not work too. Shame on you, Google.

Can you recommend something to keep using Xabber and still somehow communicate with Hangout users? May be some sort of the bridge or plugin?

**Comment by sena73** [comment]
Not a Xabber problem.

**Comment by BlauerHunger** [comment]
you could try to get your Hangouts friends to switch to a free jabber server like pimux.de or trashserver.net

**Comment by alexte** [comment]
Perhaps you could make your friends at hangout file a bug report at google. At least they should set a statement that they don't want to be shut down from internet wide communication. 

Or would you stay with AT&T if they close all lines to other mobile operators like T-mobile ? 
That's exactly what apple, facebook, whatsapp and google did in the last years.

**Comment by sena73** [comment]
Well... It works again. Single thing I changed was disabling the check-box "specify host manually" (translating from Russian). So Google is not the culprit. Hope this can help somebody.

**Comment by yekibud** [comment]
@sena73 Unfortunately I think we are going to be completely screwed [as of June 26](http://techdows.com/2017/04/google-talk-hangouts.html).  Pretty much _all_ of my contacts are using Google accounts, so not sure how I'm going to chat with them on my phone anymore without using the Hangouts app.  Maybe someone will contribute Hangouts compatibility to Xabber like libpurple does for Pidgin.
