### ISSUE TITLE
Can support sending pictures or audio or  files?

### ISSUE THREAD

**Issue by cl1069573062** [redsolution/xabber-android#719]

**Comment by casperklein** [comment]
XEP-0363 (HTTP File Upload) is supported. So sending any kind of file is possible.

**Comment by g4b0** [comment]
How can I send an image? In Xabber beta from playstore I didn't found any option to do it

**Comment by casperklein** [comment]
There is a paperclip icon right to the text field, where you enter you message.
Keep in mind, that the XMPP server you are using have to support XEP-0363 as well.

**Comment by g4b0** [comment]
I can't find the paperclib icon (Xabber Beta 2.0.2(352)). The server is prosody with http_upload module enabled:

```
May 17 11:55:11 general info    Shutting down...
May 17 11:55:11 general info    Shutdown status: Cleaning up
May 17 11:55:11 general info    Shutdown complete
May 17 11:55:11 general info    Hello and welcome to Prosody version 0.9.7
May 17 11:55:11 general info    Prosody is using the select backend for connection handling

[..snip...]

May 17 11:55:11 xxx.net:mam info    Using in-memory fallback archive driver
May 17 11:55:11 xxx.net:http_upload info    URL: <https://xxx.net:5281/upload>; Storage path: /var/lib/prosody/http_upload
```

**Comment by casperklein** [comment]
This is how it looks for me: http://i.imgur.com/UEMz8WJ.jpg

I just disabled http_upload in my prosody config and the paperclip disappeared. So probably there is a problem with your mod_http_upload and Xabber.

Two things you could try:

- Use the latest version of the module --> https://hg.prosody.im/prosody-modules/file/tip/mod_http_upload
- Update Prosody to the latest stable version 0.9.12

In Xabbers account setting, you can view the supported XEPs of the server via "Serverinfo". Check if HTTP File Upload is detected there.

**Comment by g4b0** [comment]
Thanks for your help. Actually it's a bit difficult for me to upgrade prosody and http_upload module, since I'm using the official debian jessie pagacke. I will further investigate on the prosody side.

**Comment by casperklein** [comment]
It should be easy to do a quick test: rename your current http_upload.lua file. Put the new version in place. Restart prosody.

**Comment by g4b0** [comment]
It does't work, also with the new module. Maybe also the other contact I'm trying to chat with should have the xabber beta version?

**Comment by g4b0** [comment]
looking at Account -> Server info xabber says:

XEP-0363: HTTP File Upload: X (and not V)

So it's definitely a Prosody issue, maybe I have to open some port in my server firewall?

**Comment by casperklein** [comment]
For sure, in your case tcp/5281 must be reachable..

**Comment by g4b0** [comment]
It works! Thanks a lot

**Comment by andrewnenakhov** [comment]
I think I can close it now. @casperklein thanks for help)
