### ISSUE TITLE
Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by shahidkarimi** [redsolution/xabber-android#720]
Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

**Comment by andrewnenakhov** [comment]
Can you provide some more context? Logs from device?

**Comment by Str4tocaster** [comment]
Closed due to lack of response
