### ISSUE TITLE
Update from 1.0.79 to 2.0.1 (f-droid) vanishes me out of history

### ISSUE THREAD

**Issue by Avispa** [redsolution/xabber-android#721]
Updated from 1.0.79 to 2.0.1 via F-Droid. While the messages of the respect conversation partner is intact all my messages in between are gone as like as I would have never said a word.

#### Questions
1. How to maybe re-gain my messages?
2. I have backups -- ya, you don't hear that often, don't you. ;) -- but does an import merge cleanly, just append, overwrite or what does it do? With what kind of message history would I be left?

#### Further Info
I'm pretty sure I set message storage to "store on server if possible otherwise locale". Since the update this option is gone completely and now it is set to "Store all messages on server" again by default even though the description on this button/entry already states/knows "The server does not support storing chat history".

**Comment by andrewnenakhov** [comment]
@Avispa  Probably you had a data migration gone wrong. We'll hardly be able to help you do a better migration, though  you may try restoring backup and updating to new 2.0.2 version (currenlty build 355 but stable build will be later this week or next) when it's released on main Xabber 

And if you did store messages on server using Xep-0313, you may just wipe app and reconnect account, Xabber will load message history when you'll need it.

**Comment by Avispa** [comment]
Well, I never heard things "just" going wrong like a dice role -- oops, bad luck. Even though things may be complex but however I opened the issue because as you mentioned some migration seems to be handled wrong. I'm going to do the same migration on another device and I would be sad to see the same issue over there as well. At least some work around or warning at the right place (in beforehand) would be helpful.

Even though I asked just to get sure but for real I never expected that I can re-gain messages out of nowhere. ;) However I still wonder how the import feature interacts with the already existing messages. Maybe somebody who is into the code or maybe already tried it out has some hint here... :)

**Comment by andrewnenakhov** [comment]
@Avispa well we did migrate from one database backend to another. At testing all was good, however, in real world scenarios it somehow turned out to be not that good. Since most users have already migrated, I think we can close this issue. (and we promise to do best we can with future migrations)
