### ISSUE TITLE
OTR key verification fails with pidgin if answer to question is non-ascii

### ISSUE THREAD

**Issue by yurkobb** [redsolution/xabber-android#722]
Question-and-answer verification of OTR keys doesn't work if the answer contains non-ascii characters (tested Cyrillic and ń, xabber-pidgin and pidgin-xabber). Probably an encoding mismatch? Does the OTR protocol specify an encoding for the answer?

**Comment by Str4tocaster** [comment]
@yurkobb We tested OTR Verification with non-ascii characters on next configurations: 
Xabber-Xabber, Xabber-Pidgin(Ubuntu), Pidgin(Ubuntu)-Xabber, Gajim(Ubuntu)-Xabber, Xabber-Gajim(Ubuntu) and Conversations-Xabber, Xabber-Conversations

**Comment by yurkobb** [comment]
Thank you for these tests. I would just add that in my case the problem was with Pidgin on Linux. It may as well be related to system locale settings, etc. Just a quick question (for a possible bug report to Pidgin) - the encoding of the q&a is utf8 in Xabber I suspect?

**Comment by Str4tocaster** [comment]
@yurkobb The Android default encoding is UTF-8
