### ISSUE TITLE
It is not possible to run app - FATAL EXCEPTION

### ISSUE THREAD

**Issue by piterskikh** [redsolution/xabber-android#725]
It is not possible to run app from branch "master" if device has SDK lower 21 (FATAL EXCEPTION), it's every thing is ok with branch "develop".
Also if add some dependency e.g.  'com.android.support:design:25.3.1' (and many others common dependencies) app will throw fatal exception.  It's about both branches and SDK lower 21.

**Comment by Str4tocaster** [comment]
@piterskikh Try to build latest "develop" branch. Supporting of android 4 were fixed.
