### ISSUE TITLE
HttpFileUploadManger returns file transfer services as false.

### ISSUE THREAD

**Issue by Prasadph123** [redsolution/xabber-android#727]
First of all sorry for my bad english.. 

I went with sample code of Xabber Android. Using Ignite server with XMPP protocol. In the repo there is file uploading code inside, httpFileUpload package. But it's not working. **HttpFileUploadManger** returning false to it's file transfer service. 

In server side, both Jingle and SI protocols are implemented. But HttpFileUpload manger is throwing null for upload server. 

Please help me to resolve this issue.. I will be very thank full to you..

**Comment by oxoWrk** [comment]
To use HttpFileUpload, the server must support HTTP File Upload XEP-0363.
Openfire does not directly support xep363, but you could use the https://github.com/siacs/HttpUploadComponent together with Openfire or use another server with direct support HTTP File Upload XEP-0363

**Comment by Prasadph123** [comment]
Thanks for the support.. 

But, 

We implemented HTTP  upload component. I am using Xabber client in Android. Inside a source directory there  is one file called, "HttpFileUploadManger.java". In that, upload server url is coming as null every time. Which means the below function in the code returning false always. 

public boolean isFileUploadSupported(AccountJid account) {
        return uploadServers.containsKey(account);
}

Kindly help me to resolve this issue..

**Comment by oxoWrk** [comment]
https://xmpp.org/extensions/xep-0363.html#disco

**Comment by andrewnenakhov** [comment]
@Prasadph123 I believe you have a server setup issue. Unfortunately we can't currently help you setting up your server correctly. To use file upload feature your server has to correctly support XEP-0363
