### ISSUE TITLE
Offline contact leaves the Group coversion.

### ISSUE THREAD

**Issue by Prasadph123** [redsolution/xabber-android#728]
Hi, 

Sorry for my bad English. Successfully Apk is installed using the git hub source code. Created conference in Xabber dev version. Once user is offline, suddenly we are getting a "user left" message in a chat screen. Once user comes again to the same screen, he/she is unable to receive any of the group message. Kindly help me to resolve this. 

I am looking for a group chat, which should work like a whatsap.. Each and every user of the group should get the message notification, once he/she comes to online.. 

Please reply to me regarding this query. 

:)

**Comment by andrewnenakhov** [comment]
XMPP conferences do not work like group chat. This is bad but not something we can do at the moment.
