### ISSUE TITLE
Cannot connect to Icewarp Server after update to 2.0.1

### ISSUE THREAD

**Issue by sasha3465** [redsolution/xabber-android#734]
After updating Xabber to version 2.0.1 it no longer can connect to Icewarp Server 12.0.1. Problem persists even after upgrading to Xabber 2.0.2. Worked flawlessly with previous version of Xabber.

Connection log attached (username and domain deliberately changed).
[Xabber_2.0.2(356)_2017-06-18_14-48-50.txt](https://github.com/redsolution/xabber-android/files/1083090/Xabber_2.0.2.356._2017-06-18_14-48-50.txt)

**Comment by oxoWrk** [comment]
Install [Xabber Beta](https://play.google.com/store/apps/details?id=com.xabber.android.beta) from Google Play

**Comment by sasha3465** [comment]
Thank You, Xabber Beta works fine. No problems with connecting.
Is there update planned for stable branch that resolves this issue?

**Comment by Str4tocaster** [comment]
@sasha3465 [Stable version](https://play.google.com/store/apps/details?id=com.xabber.android) also have this update now.
