### ISSUE TITLE
Can get groupchat offline member?

### ISSUE THREAD

**Issue by JakeWoki** [redsolution/xabber-android#735]

**Comment by oxoWrk** [comment]
No. [xep-0045](https://xmpp.org/extensions/xep-0045.html)

**Comment by JakeWoki** [comment]
[Conversations](https://github.com/siacs/Conversations) this project can get offline members,but it not use smack.
I has a friend use smack and send IQ this:
`<query xmlns='http://jabber.org/protocol/muc#admin'><item affiliation='member'></item></query>`
Server may do something,it also can get offline members.

**Comment by andrewnenakhov** [comment]
@JakeWoki that depends on what you understand by 'groupchat'. Multi user chat described in XEP-0045 does not allow to chat with offline users.
