### ISSUE TITLE
per-account notification sounds?

### ISSUE THREAD

**Issue by Human** [redsolution/xabber-android#736]
I'm using xabber for home automation notifications, and I want to hear different audio for different priority events. To that end, I've created three accounts for receiving corresponding low, medium, or high priority messages, but they all make the same sounds at the moment.

Would you be interested in me providing a patch to support per-account notification sounds? Or, is there some better method I should be employing to vary the notification sounds using jabber?

**Comment by andrewnenakhov** [comment]
You see, Xabber already has a very complex settings and such capabilities will add even more complexity. 

However, from what I understand, existing functionality with notifications for key phrases should work for you (especially if you can edit messages that are sent to you by your automated devices). Key phrases even support regular expressions!! See Settings - Notifications - Key phrases

Let me know if that helps.

**Comment by Human** [comment]
@andrewnenakhov I think this will work very well for me, thanks!

**Comment by andrewnenakhov** [comment]
Happy to hear it! )
