### ISSUE TITLE
Crashlytics

### ISSUE THREAD

**Issue by vanitasvitae** [redsolution/xabber-android#737]
Hi!
I saw in your commits, that you [added crashlytics](https://github.com/redsolution/xabber-android/commit/0025317ec7553923c81c19c82ba9d42952538c11) as a dependency.
Afaik this might lead to Fdroid dropping the app in the future (crashlytics is a non-free dependency). Just want to make sure, this is on your radar.

**Comment by andrewnenakhov** [comment]
Yea, we'll remove this dependency for Fdroid builds. Thanks for your concern.

**Comment by jumpwe-movim-eu** [comment]
🙆

**Comment by andrewnenakhov** [comment]
We'll make a special build for F-droid once we're done with significant redesign in Xabber that is currently underway. Expect it done in a couple of weeks. We'll remove Crashlytics and G+/FB/Twitter dependencies there.

**Comment by vad1m** [comment]
Any news on this ? No updates in f-droid since 2017-05-15. Thank you!

**Comment by Str4tocaster** [comment]
We are resolve this issue in https://github.com/redsolution/xabber-android/issues/770
So i close this one.
