### ISSUE TITLE
Authorisation error after upgrading to latest version

### ISSUE THREAD

**Issue by RedRat** [redsolution/xabber-android#738]
After automatic upgrade to the latest version 2.0.2 (360) Xabber cannot connect to the server and every time shows error: "SASLError using DIGEST-MD5 incorrect-encoding". Debug log attachet to this issue.

[Xabber_2.0.2(360)_2017-07-02_21-47-22.txt](https://github.com/redsolution/xabber-android/files/1118063/Xabber_2.0.2.360._2017-07-02_21-47-22.txt)

**Comment by andrewnenakhov** [comment]
That's a server set up issue, it happens when server uses MD5 (outdated and insecure) and has a malformed security certificate. We are able to do a workaround but feel that it's not really necessary.

**Comment by RedRat** [comment]
It's a pity that only Xabber can not work with this server. All other clients on Android or PC works like a charm. Is it possible to choose manually authorization mechanism for Xabber? PLAIN, for example?

**Comment by Cricko25** [comment]
I don't think this is the best way to enforce your vision (e.g. to convince people that something is obsolete and insecure).

In particular: 11 years ago I installed jabberd2 for one small friendly working group; this server is still used by 5 to 10 people, most of them dislike smartphones so incompatibility with xabber wasn't an issue.  Recently they accepted another member and asked that person to join them at their jabber server (so as to avoid unnecrssary inter-server traffic), but this new member uses a smartphone.  Failure to connect to that (yes, very old) server with xabber, actually, will not help anyone to achieve anything.  I've got no time now to upgrade that server to newer version, so what effectively will happen is that perhaps the whole group will move to whatsapp, telegram or whatever proprietary messenger there are around.  Thank you for this :-\

**Comment by andrewnenakhov** [comment]
@Cricko25 there is nothing to discuss here. Outdated security standards should be updated in timely manner.

**Comment by andrewnenakhov** [comment]
@Cricko25 also, thanks for framing it this way that it is somehow our fault that you can't dedicate some of your precious time to update your server. You know, we have so much free time to program, support and maintain the features you want to have.

**Comment by Cricko25** [comment]
First of all, if YOU think that something "should" be done, then it is perhaps okay to issue a warning.  I strongly believe people have the right to decide what level of security fits their needs (e.g. email is still transferred in plain text, and noone actually have problems out of that; let me skip the analyses of a situation with digest md5 in this particular situation, heh).  Anyway, _forcing_ others to do what you like in the way you did here is exactly what is known as "techno fascism".

As about _your_ precious time: as far as I understand older versions of xabber supported digest md5, so actually you preferred to spent (waste?) your time to remove this feature from the code.  Perhaps it could save you a minute or two not to try this way of forcing people into policies you like that much.

However, I'd like to thank you for your prompt response.  I've just made a screenshot of it.  What I've just seen here means xabber must not be used at all, in order for people not to become hostages of fascists like you.

**Comment by andrewnenakhov** [comment]
@Cricko25 wow, some users never cease to amaze us.
