### ISSUE TITLE
Xabber does not rejoin in joined chatrooms after reconnecting to server.

### ISSUE THREAD

**Issue by persmule** [redsolution/xabber-android#758]
Like issue #611, all conferences I have joined will get lost if my connection to server gets lost due to network and resumed. In such situation, Xabber believes I have joined in the conferences and I am often even able to query who are currently participating them, but I cannot find my own account in the participants list, and all attempts to send messages to the chatroom will fail. 

To escape such situation, I have to manually leave all conferences I have joined, and rejoin manually, or to quit and restart the whole program.

Confirmed on 2.0.1 from F-Droid.

**Comment by Str4tocaster** [comment]
@persmule Please, check it out in Xabber Beta 2.3 (471). Now Xabber automatically rejoin in MUC after reconnection.
