### ISSUE TITLE
version 2.0.2 conference.oracle.com not connecting

### ISSUE THREAD

**Issue by Vlkoff** [redsolution/xabber-android#759]
Connection to any conference on server conference.oracle.com is not working.
You have already added support for old ssl stbeehive.oracle.com, I believe this is a similar case.
Xabber 2.0.2 can send messages to a conference, but does not receive any and the room is shown as disconnected.

Could you please add the same for conferences? older xabber 1.0.30 is working fine.

Sorry for bothering...

**Comment by MichaelTiernan** [comment]
I'm having problems with a conference connection also (not same server).
Is there a better thread to be dealing with this?
Currently, the server I'm using works with 'adium' and conferences but keeps disconnecting the Xabber connections.
I *assume* it is on my server's side that the problem exists so I'd like to help troubleshoot it to nail it down but am not sure where to start.

Running Xabber beta {2.2.1 (468)} on $amsung S8+

**Comment by andrewnenakhov** [comment]
@Vlkoff  It seems that oracle does something nonstandard with conferences, and it's unlikely that we'll be able to solve this issue without an oracle account, sorry. 

We tried to registering some demo account a year ago, but it looked to work differently from what we've been getting from some @oracle.com users.

**Comment by andrewnenakhov** [comment]
@MichaelTiernan perhaps you should create separate thread and possibly include logs and ways to replicate the issue from developers account.

**Comment by MichaelTiernan** [comment]
I will however, just for the record I was assuming that there was a thread already about this sort of problem.

I'm *assuming* that the problem is on my end and I was looking for some steps to take before dumping it onto the developers.

**Comment by icetwig** [comment]
I also have the same issue using conferences.oracle.com , its basically the same issue that Vlkoff has. To note, this was working in the 1.x version.

**Comment by andrewnenakhov** [comment]
@icetwig we need a functioning @oracle.com account to solve this issue. If you can arrange that, maybe we'll be able to take a look.

**Comment by icetwig** [comment]
Will the logs help? Add you may imagine, an Oracle Account is most likely
not possible

**Comment by icetwig** [comment]
Also... this use to work in 1.x FYI

**Comment by andrewnenakhov** [comment]
Most likely it is due to Xabber using a new Smack library to work with XMPP, lots of things changed there. As for Oracle accounts... well... people from oracle use our app rather often, so maybe your management or tech personnel might be persuaded to issue us one temporary account. Without it fixing this issue is likely not possible without HUGE efforts, logs won't really help much.

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
