### ISSUE TITLE
Build failed: google-services.json is missing

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#762]
That happens when I try to build the current dev branch:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xabber:processProdDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  /tmp/xabber-android/xabber/src/prod/debug/google-services.json
  /tmp/xabber-android/xabber/src/debug/prod/google-services.json
  /tmp/xabber-android/xabber/src/prod/google-services.json
  /tmp/xabber-android/xabber/src/debug/google-services.json
  /tmp/xabber-android/xabber/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by Str4tocaster** [comment]
You may build a 'dev' flavor of project. This does not require additional files.

Or, if you want to build other flavors, you need to copy the file: "xabber-android / xabber / src / dev / google-services.json" to the "xabber-android / xabber" folder
and copy the file "xabber-android / xabber / src / dev / res / values / social_keys.xml" to the folder "xabber-android / xabber / src / main / res / values /".

**Comment by casperklein** [comment]
Thank you for the feedback. I saw your recent commits and was able to fix the missing file issue. Not exactly like you suggested, but with the same result.

For the record, I basically use this for building the xabber dev branch:

```
git clone -b develop https://github.com/redsolution/xabber-android.git &&
cd xabber-android &&
git submodule init &&
git submodule update &&
# my google-services workaround
cp ./xabber/src/dev/google-services.json ./xabber/google-services.json &&
gradle assembleProd
```

PS: What did you mean by building "dev" flavor? There is no gradle job "assembleDev". Do you mean assembleBeta? I tried assembleBeta as well assambleDebug. Same issue with the missing file, no matter which "assemble" I choose.

Now the fix by copying the file works, I ran into another exception:

```
> Task :xabber:emojicon:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :xabber:processProdDebugGoogleServices
Parsing json file: xabber-android/xabber/google-services.json

xabber-android/xabber/build/intermediates/manifests/full/prod/arm64-v8a/debug/AndroidManifest.xml:544:28-60: AAPT: No resource found that matches the given name (at 'value' with value '@string/SOCIAL_AUTH_FACEBOOK_KEY').

xabber-android/xabber/build/intermediates/manifests/full/prod/arm64-v8a/debug/AndroidManifest.xml:560:39-74: AAPT: No resource found that matches the given name (at 'scheme' with value '@string/SOCIAL_AUTH_FACEBOOK_SCHEME').

xabber-android/xabber/build/intermediates/manifests/full/prod/arm64-v8a/debug/AndroidManifest.xml:542: error: Error: No resource found that matches the given name (at 'value' with value '@string/SOCIAL_AUTH_FACEBOOK_KEY').

xabber-android/xabber/build/intermediates/manifests/full/prod/arm64-v8a/debug/AndroidManifest.xml:560: error: Error: No resource found that matches the given name (at 'scheme' with value '@string/SOCIAL_AUTH_FACEBOOK_SCHEME').

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xabber:processProdArm64-v8aDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by culugyx** [comment]
I found this works:
`./gradlew -Pbuild=dev clean assembleDevDebug `

**Comment by culugyx** [comment]
When building from the latest develop (3dbd1b3f), the empty app ids failed some checks, and I have a patch is in #766.

**Comment by casperklein** [comment]
Thanks @Str4tocaster and @culugyx. My build just finished without exceptions 😃 

For reference: I saw the readme was updated regarding the social keys (cp ./xabber-android/xabber/src/dev/res/values/social_keys.xml ./xabber-android/xabber/src/main/res/values/).

One further question as I am not that familiar with android/gradle development. **What is the correct way of building an APK from the development branch?**

I now use this for building:

```
git clone -b develop https://github.com/redsolution/xabber-android.git &&
cd xabber-android &&
git submodule init &&
git submodule update &&
cp ./xabber/src/dev/google-services.json ./xabber/google-services.json &&
cp ./xabber/src/dev/res/values/social_keys.xml ./xabber/src/main/res/values/
# gradle execution, see next snippet
```

Is there a difference between those two ways executing gradle?

```
./gradlew assembleProd
./gradlew -Pbuild=dev assembleDevDebug
```

@culugyx where did you get the information about the task 'assembleDevDebug' from?
When I run `./gradlew -Pbuild=dev tasks` the only tasks for assemble I see are:

```
Build tasks
-----------
assemble - Assembles all variants of all applications and secondary packages.
assembleAndroidTest - Assembles all the Test applications.
assembleDebug - Assembles all Debug builds.
assembleDev - Assembles all Dev builds.
assembleRelease - Assembles all Release builds.
```

Thank you very much for clarification!

**Comment by crazypioneer** [comment]
Str4tocaster

Thank you!!!
9999+ times.
