### ISSUE TITLE
Contact list: "group by account" bug

### ISSUE THREAD

**Issue by culugyx** [redsolution/xabber-android#765]
Version: 2.1(398) from the play store

When I have two xmpp accounts enabled and online, the contact list displays all the contacts under one account group, not two. "Contact list -- Group by account" is enabled as in default setting.

**Comment by culugyx** [comment]
For comparison: version 2.0.2(353) (built from git) was good.

**Comment by andrewnenakhov** [comment]
@culugyx can you provide a screenshot(s)? I don't see such behavior even with groups of the same name

**Comment by culugyx** [comment]
In the screenshots: the green account and the dark cyan account are merged and listed as a single account (the green account) in the contact list, so there're two copies of yellow contact (debug01@mydomain) listed together, although they come from different accounts.

This bug is really difficult to reproduce and only shows up for the green and the dark cyan accounts. I've created three accounts for debugging, but they are just listed normally.

![bug_contact_list](https://user-images.githubusercontent.com/9831000/30944375-57c6fd14-a3c5-11e7-9577-f663708db249.png)
![bug_accounts](https://user-images.githubusercontent.com/9831000/30944379-61178140-a3c5-11e7-930d-8bdac4cf7d78.png)

**Comment by culugyx** [comment]
Probably related to the migration of XMPPAccountSettings to realm.

See if reproducible with this procedure:
- install a version before the migration: eg. 2.0.2(353)
- add more than one accounts
- upgrade to 2.1(398)

**Comment by andrewnenakhov** [comment]
@culugyx to be honest we do not plan to support migrations between versions that were not published on Google Play. If you can reproduce this bug with production versions of Xabber, we'll investigate further

**Comment by culugyx** [comment]
OK, I see. As google play doesn't publicly show a complete version history, I need a way to determine the published versions. (Sorry, but I don't regularly use the production version.)

**Comment by culugyx** [comment]
@andrewnenakhov Hi, I'm able to reproduce this bug by
- Start with a fresh installation of 2.0.2(369) (equals the current production version) (62501746)
- Add two XMPP accounts
- Upgrade to 2.1(400) (3dbd1b3f), now all the contacts are listed under one account
- New: after reordering the accounts, this bug goes away 

The transition probably happened between the latest production version (2.0.2(369)) and the current beta or develop version(2.1(400)), thus I can only test with two versions built from git.
`./gradlew -Pbuild=dev assembleDevDebug`
Hopefully 2.0.2(369) 62501746 is where the current google play version came from. (btw, the 2.0.2 tag is missing...)

**Comment by Str4tocaster** [comment]
@culugyx Thanks. Fixed with 76bfe77

**Comment by culugyx** [comment]
@Str4tocaster Thank you! I tried again with current develop branch (89c4572e), and the bug doesn't show up anymore.
