### ISSUE TITLE
lost history for a contact not in roster

### ISSUE THREAD

**Issue by ohhai** [redsolution/xabber-android#773]
I had a conversation with a contact who is not added to my contact list.
Now can't find the log. The list of recent chats does not have it. That contact name is not present anywhere.

Is there any workaround to recover the log like grep on some dir, anything?

xabber 2.1(405), android 6.0.1

**Comment by andrewnenakhov** [comment]
That's actually a problem. Xabber polls archive for every contact in your roster and loads it's history. If there is none, client can't know that some interaction existed, and current message archives do not allow to get all last conversations from server. Simplest workaround is to re-add said contact to roster, then Xabber will load his history from message archive. Even if he'll block you.

**Comment by ohhai** [comment]
Thanks a lot, got the history by that.

For a wishlist, xabber may add such a contacts in some temporary form as done by some clients. Or store a separate list invisible to user, maybe, and parse it while chats loading. I'm not sure what is better.

**Comment by andrewnenakhov** [comment]
@ohhai such functionality should be implemented on servers,not on clients. One of biggest XMPP problems is that many client developers do some ad-hoc clientside solutions to do things that should be done on serverside.
