### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by shah-95** [redsolution/xabber-android#776]
Hello Sir, xabber still has issues with nimbuzz, now it says account online but none of my contacts are online and i cant see anything, but i can join conferences, but after joining it says connection not established and i dont see any messages, but in the menu it still says account online. Dont know whats the problem, bombusmod works fine. Used both latest xabber stable release and beta from play store , both have same issue.
Device : non rooted stock samsung galaxy s7 edge, android 7.0

**Comment by andrewnenakhov** [comment]
Maybe you should ask Numbuzz why that happens, or use Bombusmod? We don't have an account there and little desire to get one to test some proprietary web server that (clearly) does not work according to standard.

**Comment by shah-95** [comment]
Sir , i really wanted to use Xabber like before, bombus is not anything like xabber, please look into it, i can provide account if you want. But please fix this if you could. Also bombus don't use tls encryption. I don't know why on a less secure client like bombus I could connect , but not on xabber. Please help. Thanks a lot.
