### ISSUE TITLE
Add a possibility to send and re-send authorization request manually in user's options

### ISSUE THREAD

**Issue by ghsrcgh** [redsolution/xabber-android#777]
Please add a possibility to send and re-send authorization request manually in user's options.

Currently if user had de-authorized you, you will not able to request authorization.
Also if you had added user and for some reasons authorization request is lost, you will not be able to re-request authorization.

You just need to add simple option like in Miranda (in user's options following ":" button) - "Re-request authorization". And just send it after taping this menu.

**Comment by Str4tocaster** [comment]
@ghsrcgh Fixed in https://github.com/redsolution/xabber-android/commit/2c76b846895a67003a29055f60c6ad014dfae397
You can check it out in last Xabber Beta 2.3 (471)
