### ISSUE TITLE
XMPP-SPAM: Blocked accounts can still spam authorization requests

### ISSUE THREAD

**Issue by kkarhan** [redsolution/xabber-android#780]
Please add the following options:

Auto-Reject authorization requests from blocked accounts.
 - This way, xmpp spammers won't flood my notification bar, which I can't prevent. Ignoring doesn't help, since the same request will reappear over and over again. If a contact is blocked they shouldn't be able to continue spamming and bothering the person that blocked them.
- Currently, I get bothered each few mins with the same request, making any notification from Xabber almost always a waste of time and annoyance.

Block all messages and/or authorization requests from specific servers.
- This is kinda emergency solution, as xmpp-spamming in combination with inband registration allows spammers to circumvent blockades.

Reason:
XMPP Spamming really gets out of control, and while it is not as heavy as eMail Spams, it's worse due to absence of minimalistic features to combat it on clientside. It's frustrating and annoying, espechally when users need to be online.

I also highly suggest to support upcoming and existing XEPs that target XMPP-Spam, and to implement them ASAP.

**Comment by andrewnenakhov** [comment]
Blocked accounts auth requests should be stopped by server. It's not a client task.
