### ISSUE TITLE
[Xabber Beta] RU-locale bugs to place

### ISSUE THREAD

**Issue by MikhailKasimov** [redsolution/xabber-android#783]
Hello!

Xabber Beta 2.2(448)

1. ... поделится --> поделиться (что сделать?)
2. ... о сбоях вы --> о сбоях, вы (пропущена запятая, закрывающая деепричастный оборот).

![screenshot_2017-12-28-02-12-23](https://user-images.githubusercontent.com/7167300/34396566-72bbc76a-eb75-11e7-8935-956a2f88b796.png)

**Comment by MikhailKasimov** [comment]
"Настройки" -- "Настройки присутствия"

1. Унифицировать текст для указанных фрагментов: либо "при блокировании", либо "при блокировке".

2. записей будет --> записей, будут (пропущеная закрывающая причастный оборот запятая и множественное число для "Приоритеты... будут").
![screenshot_2017-12-28-02-21-48](https://user-images.githubusercontent.com/7167300/34396701-0a7b4c5a-eb77-11e7-9c4f-cdf04a7db029.png)

**Comment by MikhailKasimov** [comment]
"Настройки" -- "Оповещения"

сообщениях содержащих --> сообщениях, содержащих (пропущена открвающая причастный оборот запятая).

![screenshot_2017-12-28-02-32-26](https://user-images.githubusercontent.com/7167300/34396758-e0ea7a0e-eb77-11e7-9e6c-89ce7a58aa60.png)

**Comment by MikhailKasimov** [comment]
"Настройки" -- "Список контактов"

группы даже если --> группы, даже если (пропущена запятая)
![screenshot_2017-12-28-02-40-23](https://user-images.githubusercontent.com/7167300/34396826-d1b5bc82-eb78-11e7-94d9-6eb5b8f6a860.png)

**Comment by Str4tocaster** [comment]
Thanks for help. Fixed in 5146fd2.
