### ISSUE TITLE
Add support for XEP-0071

### ISSUE THREAD

**Issue by the-djmaze** [redsolution/xabber-android#785]
Could you add support for XEP-0071?

I've tried sending
`<message id="xmpp_5a51ffe2f0bb8" type="chat" to="djmaze@example.com"><body>this is green strong https://example.com/</body><html xmlns="http://jabber.org/protocol/xhtml-im"><body xmlns="http://www.w3.org/1999/xhtml">this is <span style="font-color: green">green</span> <strong>strong</strong> <a href="https://example.com/">https://example.com/</a></body></html></message>`

But only the text &lt;body&gt; is used.
When sending only a &lt;html&gt; nothing is shown at all.

**Comment by andrewnenakhov** [comment]
We do not plan to support this in Xabber, it leads to bad UX. When sending formatted messages you should also include non-formatted text in stanzas. If sender client fails to do that it's an issue to be fixed on sending side. 

Some popular desktop XMPP clients do notoriously put html-formatted text in main body, but it's incorrect.
