### ISSUE TITLE
File transfer error due to malformed URL in HTTP_UPLOAD

### ISSUE THREAD

**Issue by webmst** [redsolution/xabber-android#786]
I'm getting a red "x" when I attempt a file transfer. 

I'm connecting some Xabber 2.2 clients to a Prosody 0.9.7 server behind a router, accessing it via the "CUSTOM HOST" option, set to its Dynamic DNS FQDN.

Checking Xabber's logs to debug the issue, I found a "malformed" URL in the PUT request that is generated for the HTTP_UPLOAD; it's in the form:

https://LOCALNAME:5281/DDNSFQDNupload/SLOT/FILE

So I notice the following inconsistencies:

- Xabber is composing the destination URL using the LOCALNAME (e.g. "server.private") instead of the "CUSTOM HOST" as server address, that is not addressable on the public internet
- Xabber is also adding the DDNSFQDN address (the one set in CUSTOM HOST, e.g. "server.dyndns.org") immediately followed by the folder name "upload" (missing slash)

I would expect the generated URL to be corrected using just the "custom host" address (plus port), to make file transfer to work.

**Comment by casperklein** [comment]
According to https://xmpp.org/extensions/xep-0363.html#request, the PUT/GET URLs are generated by the server. I don't think Xabber alters them, but I may be wrong.

Did you test file upload with a different client, to ensure there is no problem with the server configuration?

Using the latest version of prosody (0.10.0) and community modules is also worth testing :)

**Comment by webmst** [comment]
You are right in saying that, still - as I said - there are some reasons that justify a client-side check:

- my server is currently *not* aware of its DDNS address, simply it is not in its configuration; the server only knows its LAN name, so the WAN FQDN should come from somewhere else
- the generated URL is not just wrong, it is malformed, having two addresses badly merged together, this seems a bug for the new HTTP_UPLOAD function when CUSTOM_HOST is used
- in trying to solve the issue, I set the HTTP_EXTERNAL_URL (an option designed to set the external URL for Prosody's internal HTTP server) in the server's configuration, with absolutely no change

At the moment I haven't tried any other XMPP client but - on server side - I know Prosody 0.10 has some issues, so I thought it was easier to start excluding Xabber's responsibility in this specific case, that involves a "non-DNS-resolved" server configuration.

**Comment by oxoWrk** [comment]
Xabber not alters URLs.
