### ISSUE TITLE
The option to delete the complete history has disappeared

### ISSUE THREAD

**Issue by sesom42** [redsolution/xabber-android#787]
In version 2.2 the option to delete the complete history has been removed. Only individual messages can be deleted from the history.

I get status messages through an XMPP contact. There can be a lot of them. After checking (and repairing the error) I was able to delete all messages at once. Deleting 100 messages individually is no longer practicable.

**Comment by andrewnenakhov** [comment]
Did you try swiping left and looking for options there?

**Comment by sesom42** [comment]
Thank you! That's very well hidden.

**Comment by andrewnenakhov** [comment]
Well, turns out users have a hard time finding this option. Perhaps we'll do something about it when we get to updating chat activity.
