### ISSUE TITLE
Very strange behavior with matterbridge

### ISSUE THREAD

**Issue by jadjay** [redsolution/xabber-android#789]
Used software : 

- Xabber 2.2(454)
- Matterbridge 1.6.3 [42wim/matterbridge](42wim/matterbridge)

Use case : 

- Bridge between mattermost and openfire MUC (same with Muc on server jabberfr.org)
- writing on xmpp to mm : Ok displayed on muc and mm channel
- writing on mm to xmpp : Message is ok (displayed on other clients software) but not by xabber...

Problem : 
- It works with other clients (e.g. kandruIM)

Could you have a look ? I'm okay to give you a test access if you want... Or configuring a bridge for your test.

**Comment by oxoWrk** [comment]
Show Xabber logs

**Comment by andrewnenakhov** [comment]
no updates shown
