### ISSUE TITLE
xabber declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :xabber:MemorizingTrustManager.

### ISSUE THREAD

**Issue by abhin-dexlock** [redsolution/xabber-android#793]

**Comment by Str4tocaster** [comment]
Xabber uses Gradle build system. The only specific thing is git submodule for ge0rg/MemorizingTrustManager library. To make it work use following commands:

git submodule init
git submodule update

**Comment by vicky1198** [comment]
but how

**Comment by Str4tocaster** [comment]
@vicky1198 Terminal in Android Studio.

**Comment by vicky1198** [comment]
but it say failed to clone,why??

**Comment by aamir-github** [comment]
> Xabber uses Gradle build system. The only specific thing is git submodule for ge0rg/MemorizingTrustManager library. To make it work use following commands:
> 
> git submodule init
> git submodule update

do I have to write these commands for path "xabber-android-master\xabber-android-master\xabber>" OR "xabber-android-master\xabber-android-master>"
