### ISSUE TITLE
Notification still appearing after they are purged via restart when clear history is checked

### ISSUE THREAD

**Issue by mariusft** [redsolution/xabber-android#797]
There is a strange behavior regarding notifications.

If you clear them from android or when you exit xabber with clear history option checked notifications still appears on android system and even on xabber recent chats, showing you that you still have # messages to read but there are none. Behavior is the same even if you decide to archive them.

This happens if you don't actually read the messages.

**Comment by Str4tocaster** [comment]
@mariusft This bug was fixed in latest Xabber Beta 2.3 (471) from Google Play. Please, check it out and tell us.

**Comment by mariusft** [comment]
@Str4tocaster Seems OK now with the beta, I'll test it more when will be merged to stable release, thank you.

**Comment by mariusft** [comment]
This is partially solved in 2.3(473):
 - clearing up the notifications from android indeed fixes the android notifications.

 - number of messages are still present when you exit with "Clear history on exit" ON even if there are no messages to display since they are purged by clear history option.

 - question: archive chat is supposed to be cleared out when "Clear history on exit" is ON?
