### ISSUE TITLE
v2.0.1 no inbound messages on slack conference

### ISSUE THREAD

**Issue by ron-edison** [redsolution/xabber-android#798]
Have been using xabber for years with slack xmpp gateway no major issues. Recently able to reproduce issue with xabber dev v2.0.1 that does not occur with 1.0.74 which is that while slack conference can be added to v2.0.1 without issue, only outbound messages can be sent. Inbound messages to do not reach xabber somehow.

Have troubleshot extensively and not found any other controlling factor other than the version of Xabber in use. Dev v1.0.74 works fine, 2.0.1 is one way only (outbound only) on slack conferences.

Possibly this is an issue with other conference situations as well not just Slack. Possibly this is a similar issue being described:

https://discourse.igniterealtime.org/t/xabber-delivering-only-one-way-chat/61270

If anyone knows of a workaround or any relevant info on this I'd be interested.

**Comment by andrewnenakhov** [comment]
@ron-edison  Normally we don't support third party services that require us to sign up for testing to solve some issue. However, we DO happen to have Slack account registered a while back, so I might give a shot at testing it. However, since we do not really use Slack, please provide detailed instructions to reproduce issue. Like, open slack, go to section b, press button c to create conference, then open Xabber, ...

**Comment by ron-edison** [comment]
Thanks very much - first in your slack account ensure that the XMPP gateway is enabled (under gateways), create a user obviously and a channel.
Create an account in xabber based on the details located on the gateways page, once that account is online in xabber, add conference, select the corresponding xmpp slack account, the server details for the conference will also be on the slack gateways page and is normally conference.accountname.xmpp.slack.com - under conference enter the name of the channel without the #, hit next, pick a nickname and leave the password blank, hit join conference.

If all has gone correctly the conference will be joined in xabber. Hopefully you can reproduce the behavior I'm seeing on v2.0.1 where chats in the conference simply don't show up but chats sent from xabber show up in the channel without issue.

Thanks again

**Comment by andrewnenakhov** [comment]
@ron-edison oh what  a can of worms was uncovered while investigating Slack's lousy MUC implementation... team of 3 is working on it for two days already. Mostly due to even better understanding how MUC standard is broken by design.

**Comment by andrewnenakhov** [comment]
https://news.ycombinator.com/item?id=16539857

We had fairly good understanding how to fix this issue, but since slack announced closure of xmpp gateway, I believe this issue is no longer relevant. Sorry, @ron-edison
