### ISSUE TITLE
Connections from Samsung S8+ 

### ISSUE THREAD

**Issue by MichaelTiernan** [redsolution/xabber-android#813]
Just "upgraded" OS to Android 8.0.0 (Kernel 4.4.78) and it broke my Xabber {2.2.1(468)} connections. (Actually, only broke 2, xabber.org continued to work.)

But, I reinstalled 2.2(454) and it seems to work fine.

I'm generating two logs and hoping this helps. (One using new, one using old.)

[Xabber 2.2(454) 2018-03-23 13-13-06 log file.txt](https://github.com/redsolution/xabber-android/files/1842800/Xabber.2.2.454.2018-03-23.13-13-06.log.file.txt)
[XabberBeta 2.2.1(468) 2018-03-23 13-11-01 log file.txt](https://github.com/redsolution/xabber-android/files/1842802/XabberBeta.2.2.1.468.2018-03-23.13-11-01.log.file.txt)

For this, I only tried to connect to xabber.org and gmail.com, not my other.

**Comment by andrewnenakhov** [comment]
Library that we use for DNS resolving does not work on Android 8, and it's still not fixed in upstream. Currently Xabber can't resolve SRV records (aka correct way to point to server), probably for now you can circumvent this issue and add host address manually, that should work.

**Comment by MichaelTiernan** [comment]
Now that I understand the problem, I can use the "Custom Host" setting in the "Connection settings" page when setting up the account. Now it works.
Thanks!

**Comment by andrewnenakhov** [comment]
Actually is should work in coming update even without custom host
