### ISSUE TITLE
Connecting to conferences.

### ISSUE THREAD

**Issue by MichaelTiernan** [redsolution/xabber-android#814]
I am assuming that the error is specific to our server. My proof of that is that my xabber.org id can stay logged into the test conference at xabber.

I have three conference "rooms" that I want to be connected to and the xabber app from my Android won't stay connected. I can establish a connection and send a line. It will then give me a "connection unavailable" message. BUT, subsequent lines /are/ sent to the conference. It just seems to not know how to stay connected.

Attached is a log. I sanitised it a little.
What do I need to tell our end to correct this?
[XabberBeta 2.3(473) 2018-03-27 14-50-45 log file.txt](https://github.com/redsolution/xabber-android/files/1853416/XabberBeta.2.3.473.2018-03-27.14-50-45.log.file.txt)

Thanks for everyone's time.

**Comment by oxoWrk** [comment]
Your server uses  out-of-date time-stamp format("CCYYMMDDThh:mm:ss"). Smack crashes when parsing this stamp

**Comment by MichaelTiernan** [comment]
Okay, I'll ask a loaded question. I know the server on this end is broken and using the wrong format but, shouldn't the Smack software deal with it more elegantly?

**Comment by MichaelTiernan** [comment]
And, sorry, hit return too fast.

Is there anything I can do to deal with this? I'll ask the server folks to look into an update or whatever but I won't hold my breath.

**Comment by andrewnenakhov** [comment]
@MichaelTiernan perhaps you can post an issue on Smack issue tracker and have it fixed there. 

However, there are major concerns how much efforts 'good' software developers must waste to provide interoperability with developers who don't give a damn. Perhaps best way is to use decent server like ejabberd, fixing this once and for all.

**Comment by MichaelTiernan** [comment]
Not asking the developers to deal with it. Just asking for advice on what to tell the server folks. :(

**Comment by andrewnenakhov** [comment]
> Just asking for advice on what to tell the server folks. :(

@MichaelTiernan that depends on what server you are having issues with. Do you have this information?

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
