### ISSUE TITLE
Unable to resolve dependency 

### ISSUE THREAD

**Issue by Abdulqa** [redsolution/xabber-android#825]
i am going to import project in my Android studio 3.1. getting errors given below.

Unable to resolve dependency for ':xabber@prodDebug/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@prodDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@prodDebugAndroidTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@prodDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@prodDebugUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@prodDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@prodRelease/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@prodRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@prodReleaseUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@prodReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebug/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebugAndroidTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebugUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@ruDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@ruRelease/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@ruRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@ruReleaseUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@ruReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebug/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugAndroidTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devRelease/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@devRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devReleaseUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@devReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebug/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebugAndroidTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebugUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@vipDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@vipRelease/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@vipRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@vipReleaseUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@vipReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebug/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebugAndroidTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebugUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@betaDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@betaRelease/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@betaRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@betaReleaseUnitTest/compileClasspath': Could not resolve project :xabber:MemorizingTrustManager.
Open File
Show Details

Unable to resolve dependency for ':xabber@betaReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

**Comment by Str4tocaster** [comment]
@Abdulqa Just read the README file and follow the instructions.
