### ISSUE TITLE
Contributing a new logo 

### ISSUE THREAD

**Issue by artjeck** [redsolution/xabber-android#826]
Hi developers!
I am a graphic designer, I want to contribute to make a logo on your project, before I start it, I have to ask your permission first 😃
Best Regards, @artjeck

**Comment by andrewnenakhov** [comment]
Well, you can provide samples, we'll use one of them if we'll like it. But actually we like Xabber logo as it is today. Has some issues with current 'flat' trend, but trends change all the time.

**Comment by andrewnenakhov** [comment]
It's pretty well explained on main page for this repository and links contained there.

**Comment by artjeck** [comment]
Thank you sir, I will prepare as soon as possible 👍

**Comment by amirdesaingrafis** [comment]
Hello, I want to contribute to this awesome project, and I have a new logo design for you, if you allowed I will send to you :)

**Comment by Str4tocaster** [comment]
@amirdesaingrafis You can post it here so we can look ;)

**Comment by amirdesaingrafis** [comment]
![xabber](https://user-images.githubusercontent.com/36655856/39808150-62238e6a-53a8-11e8-844b-1ce2d2d8b240.png)
What do you think?
My logo is designed from without changing the old logo shape, with the concept of the globe at the top position in the incandescent light bulb icon.

**Comment by amirdesaingrafis** [comment]
it's the letter "x" hidden inside it. I will revise to make it look real. is there any suggestion from you @oxoWrk
