### ISSUE TITLE
Wish: Ability to discover the real JID of participants of MUC chat when room allows it.

### ISSUE THREAD

**Issue by persmule** [redsolution/xabber-android#827]
MUC chatroom could be configured to allow a participant to discover the real JID of other participants, and moderators should have such capability even without such configuration, but it seems impossible to do so with xabber, while using pidgin, psi, or even Conversations can achieve this.

Could such capability be added in a future revision of xabber, please?

**Comment by andrewnenakhov** [comment]
MUC is not a standard but an atrocious pile of garbage. We are working on better group chat solution and intend to eventually phase out MUC support out of Xabber for Android. This is also the reason why we never even considered adding MUC support to Xabber for Web or iOS.
