### ISSUE TITLE
Custom notification sounds broken on Android 8

### ISSUE THREAD

**Issue by dolda2000** [redsolution/xabber-android#828]
I just upgraded my phone to Android 8.0, and doing that seems to have broken custom notification sounds in Xabber. I'm not really into Android development enough to offer informed commentary, but there seems to have been changes to how notifications work in 8.0 that have affected others too:

https://stackoverflow.com/questions/46019496/notification-sound-on-api-26/46192246

**Comment by andrewnenakhov** [comment]
Indeed. We'll look into it.

**Comment by jpastuszek** [comment]
No sounds at all - I was using text match for alerts.

**Comment by dolda2000** [comment]
I can confirm that this appears to be fixed now.

**Comment by Str4tocaster** [comment]
@dolda2000 Glad to hear that!
