### ISSUE TITLE
Allow http_upload to send bigger pictures OR autoresize image into smaller (minimal) size

### ISSUE THREAD

**Issue by Wohlstand** [redsolution/xabber-android#830]
I have own XMPP server where I have enabled BOSH and the support to receive HTTP Uploads and I have allowed big files on my end. I have found it's very inconvenient when I making 8MP photos and I can't send them due their "too big size". That forces me to set smaller size of photo and retry the shot, OR manually resize the picture in any image editor I can find on my phone.
Can you allow sending of bigger images or make the automatic resize of the photo into smaller size?

P.S. As another suggestion, can you add the ability to take the picture from the camera than from gallery?

**Comment by Str4tocaster** [comment]
@Wohlstand This is what we are currently working on. Stay tune!

**Comment by Wohlstand** [comment]
Neat! :fox_face: 
Waiting for the release that will include this! :smile:

**Comment by Wohlstand** [comment]
I see you have made something, however, on attempt to send a bigger image, the crash happens at me. The assembly is 501 from Google Play, Android 4.3 (Samsung Galaxy S III device). I trying to send 8MP photo. When I using default camera app, the crash happens on "Camera" app itself. When I shoted it separately and trying to send it - crash of Xabber itself.

**Comment by Str4tocaster** [comment]
@Wohlstand I was test it on images which size is 20 and 50MB and it is work correctly.
Please, try version 557 from GP and give your feedback here. Thank you.

**Comment by Wohlstand** [comment]
Okay, will pull the update... Latest version I have installed some weeks ago was still be buggy, however, it said "NullPointerException" Java upload error instead of crash which is much better, but still inconvenient. Gonna to test...

**Comment by Wohlstand** [comment]
Just now I have tested and I have made a 8MP shot to send. Yeah, it doesn't crashing, but showing ":x:" icon which contains "java.lang.NullPointerException" error inside. Still won't send big photos...

**Comment by Wohlstand** [comment]
Note, it was a test to send a shot from the camera... Gonna to try upload image from the gallery...

**Comment by Wohlstand** [comment]
Attempt to send from the gallery was caused a crash of Xabber... I have sent the report with the "GitHub issue 830" description, is it's useful or not?

**Comment by Str4tocaster** [comment]
@Wohlstand i see your crash report. There are android 4 on your device, right?
I need to test this crash on android 4. Thanks.

**Comment by Wohlstand** [comment]
@Str4tocaster , Yes, Android 4.3

**Comment by bleedingcrow** [comment]
Could http upload file limits be circumvented slicing images into segments

**Comment by andrewnenakhov** [comment]
Images are shrinked to smaller size on send, so this issue is no longer relevant. However, for the time being there is no an option to send an image without resizing. We'll add it in the future
