### ISSUE TITLE
attempting to load a conference in bookmarks crashes app

### ISSUE THREAD

**Issue by johnnybubonic** [redsolution/xabber-android#831]
i have a persistent conference bookmark set up via [XEP-0048](https://xmpp.org/extensions/xep-0048.html), set to auto-join.

however, in recent versions (incl. xabber beta), when i attempt to load/switch into that conference window, the entire app crashes.

i'm on lineageOS 15.1 (which uses android 8.1 as a base). let me know if you need any more information.

**Comment by andrewnenakhov** [comment]
We're obsoleting conferences, in 2019 or in 2020 with a better protocol to replace them.
