### ISSUE TITLE
Unable to sync and compile in Android Studio.

### ISSUE THREAD

**Issue by prashantcore** [redsolution/xabber-android#836]
I cloned the project from github and followed the instructions as prescribed in the Readme file but couldn't succeed to sync and compile the project. Can you please assist me in the same.

`Unable to resolve dependency for ':xabber@devDebug/compileClasspath': Failed to transform file 'MemorizingTrustManager-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Failed to resolve: crashlytics
Show in File

Failed to resolve: beta
Open File

Failed to resolve: crashlytics-core
Open File

Failed to resolve: answers
Open File

Failed to resolve: fabric
Show in File

Unable to resolve dependency for ':xabber@devDebugAndroidTest/compileClasspath': Failed to transform file 'MemorizingTrustManager-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugAndroidTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugUnitTest/compileClasspath': Failed to transform file 'MemorizingTrustManager-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devDebugUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devRelease/compileClasspath': Failed to transform file 'MemorizingTrustManager-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devRelease/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devReleaseUnitTest/compileClasspath': Failed to transform file 'MemorizingTrustManager-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details

Unable to resolve dependency for ':xabber@devReleaseUnitTest/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
Open File
Show Details`

**Comment by shravanteegala** [comment]
Iam Facing same issue.

**Comment by Str4tocaster** [comment]
Read readme again. Execute following commands in terminal:
```
git submodule init
git submodule update
```
Be sure that modules  **emojicon** and **memorizingTrusManager** has been downloaded in your local project.

**Comment by prashantcore** [comment]
I have tried it a lot, but no success.

**Comment by Str4tocaster** [comment]
@prashantcore Try File -> Invalidate Caches / Restart. Or retry clone to new project.

**Comment by DivyaPrajapati09** [comment]
Resolved by just clean build the project
