### ISSUE TITLE
[Feature Request] Make SOCKS-proxy configuration for every Jabber account (not a common for all)

### ISSUE THREAD

**Issue by ghsrcgh** [redsolution/xabber-android#843]
Please make a possibility to configure different SOCKS-proxy for each one Jabber account, but not a common proxy for all. I want to have a possibility to not combine accounts between each other. Make them all separately by IP address to have no possibility to see that they are used on the same device.

[Orbot allows](https://github.com/n8fr8/orbot/issues/176#issuecomment-423374727) to use a different SOCKS proxy on one device. Moreover, different internet (non-local) proxies maybe used.

**Comment by xmarxthespot** [comment]
>  to have no possibility to see that they are used on the same device

By your contacts?  Or what context?

**Comment by andrewnenakhov** [comment]
@ghsrcgh actually, Xabber supports different proxies since forever - proxies are configured on connections settings separately for each XMPP account.
