### ISSUE TITLE
fix gradle sync failed, android studio 3.2  (git fix, it didn't work, emojicon library errors)

### ISSUE THREAD

**Issue by HackM3nt3** [redsolution/xabber-android#845]
I'm trying to compile the apk but when i open the code using android studio and i got  50 errors and 1 warning from gradle sync failed. (Before several updates)

In the section Read me there is and explanation about how to make it work with git
git clone https://github.com/redsolution/xabber-android.git
then  cd xabber-android 
and
git submodule init
git submodule update

And i updated the submodule from https://github.com/ge0rg/MemorizingTrustManager in xabber-android/MemorizingTrustManager and i updated the build.gradle in xabber/MemorizingTrustManager

But i still got the 5 errors but always is the same:

Unable to resolve dependency for ':xabber@prodDebug/compileClasspath': Failed to transform file 'emojicon-release.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

I already tried to clean the cache and i didn't work
How can i fix this please?

![captura4](https://user-images.githubusercontent.com/13055051/48432142-95633f00-e741-11e8-8acc-44ce3b28bf1f.JPG)

**Comment by HackM3nt3** [comment]
![captura](https://user-images.githubusercontent.com/13055051/48363223-6c747880-e673-11e8-9703-4db303ecf42f.JPG)

**Comment by fabilqis** [comment]
I have same problem too with android studio 3.2.

**Comment by tarekfaroukhamouda** [comment]
U need to update smack lib

**Comment by Str4tocaster** [comment]
@HackM3nt3 which version of gradle you use? 
On android studio 3.2 and gradle 4.1 - build is successful.

@tarekfaroukhamouda No. Xabber use custom version of Smack. It is correctly work on android studio 3.2 and gradle 4.1

**Comment by ariebrainware** [comment]
@Str4tocaster  I'm using Android Studio v3.2.1 and gradle 4.10 , still error

![image](https://user-images.githubusercontent.com/26453961/48977987-94ce8f00-f0d7-11e8-8ef6-6df7c1bd9305.png)


![image](https://user-images.githubusercontent.com/26453961/48977982-82545580-f0d7-11e8-815f-9bbab28fe8ef.png)

**Comment by Str4tocaster** [comment]
@ariebrainware Try latest update from master branch. It is contains changes for Android Studio 3.2.1 with gradle 4.6 and build-tools 3.2.1
