### ISSUE TITLE
URLs cannot be clicked/touched in chat

### ISSUE THREAD

**Issue by KonomiKitten** [redsolution/xabber-android#853]
**App version:** Xabber VIP 2.6(557)
**Android versions:** 7.1.2

**Problem:** URLs are no longer treated as links and cannot be touched to open them since the chat redesign in the latest build, they worked fine in the previous build, screenshot below.

![screenshot_20190104-195156](https://user-images.githubusercontent.com/12713710/50702800-1b4a9900-10a6-11e9-9185-7773cefe961b.png)

**Comment by andrewnenakhov** [comment]
Yes, we're aware of that. It's a side-effect of a new chat interface, we had some issues with links, but decided to release without links highlighting. Will likely fix it in next release.

**Comment by shaynem** [comment]
+1 super annoying

**Comment by Str4tocaster** [comment]
Fixed in 97f255bc1ade4a4b5cdf3194983068d16f13025c
