### ISSUE TITLE
Confererence NONAME user

### ISSUE THREAD

**Issue by panpansh** [redsolution/xabber-android#855]
![screenshot_20190108-170750_messenger](https://user-images.githubusercontent.com/790586/50843246-9d69e480-1368-11e9-8e57-c4a6883fbb6f.jpg)

When I create a conference, I can see a user without name and because, I click on it and BAM.

`D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xabber.androiddev, PID: 11146
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jxmpp.jid.parts.Resourcepart.toString()' on a null object reference`

**Comment by panpansh** [comment]
This visitor is only visible by xabber

**Comment by ge0rg** [comment]
I've encountered `null` named participants in MUCs that have a MUC avatar and send it as a presence from the bare JID. It shouldn't have the participant status code, but might be interpreted as a participant by less sophisticated implementations.

**Comment by andrewnenakhov** [comment]
thing is, we see little value in fixing obvious bugs that are related to functionality that is soon to be made obsolete.

**Comment by Str4tocaster** [comment]
@panpansh I have no idea why your conference have empty occupants. But i fixed NPE. 67af00b62ca904d7245cf64e67d94627d38df8a2

**Comment by panpansh** [comment]
The visitor is conference.associations.fr/null => can I hide it please ?

**Comment by panpansh** [comment]
fixed  here : https://github.com/redsolution/xabber-android/compare/develop...panpansh:patch-1
