### ISSUE TITLE
 Hide lock icon in MUCs

### ISSUE THREAD

**Issue by licaon-kter** [redsolution/xabber-android#859]
...as OTR is not supported anyway, right?

Also, pressing `activate` will crash the app:
```
E AndroidRuntime: java.lang.ClassCastException: com.[01;31m[Kxabber[m[K.android.data.extension.muc.RoomChat cannot be cast to com.xabber.android.data.message.RegularChat
E AndroidRuntime: 	at com.[01;31m[Kxabber[m[K.android.ui.fragment.ChatFragment$19.onClick(Unknown Source:24)
```
_(Yeah, ignore the formatting garbage in logcat)_

2.6 (557)

**Comment by Str4tocaster** [comment]
Fixed crash in 4d7144701c84ef62c57725febefb71b8ae6c32cf
Hide OTR button in MUC - 01aa9d565a2494fc457ccbbbada3daadfe64bacb
Thanks
