### ISSUE TITLE
OTR not encrypt files

### ISSUE THREAD

**Issue by panpansh** [redsolution/xabber-android#861]
`I/com.xabber.android.data.extension.otr.OTRManager@36a3620: transform incoming message... ?OTR:AAMDM0Jyl+6MGlQAAAAAAQAAAAEAAADAa2StsqLSy6OxfT33vY6CgYzsuGib7uMgU3QVc0RDRn31/r5IAI/uEYb6oRbBYDrKAYmSLGOwhTSgZLY7MbeMPs8GNn/lft6b/cHzv1R/QBXRhi/VTi2tlbysvcRst0hLxjCZE+RusicJiG1OrTcjgblY9oCMsWbIy4o060gWefvY5EHm5rouCDDRpGOBpkURFRS3yt4QAcC/6FdREyv1Vu1EnXONzbe9xSYt5MksIewnbkjH7fp2/TJK5nSjNrWaAAAAAAAAAAEAAACTmDESYYfuP3oqjRKL1Mt+D/aGaYQQMMzu8mVAZ4BLpt1NWP5siXu4xiCq4DwvrgXjs8poVJ9eShyCMsFCFLQau70O7r2KOcmMaH6v4ECS/XGsZV0XIGvi29D8uMqEbUkTRzbzxUDsNEkDESXGnSfuhBDTy60B6ZlCcDooyL4NYXfs0KkeZRe2BWltfi5Eq4GTTKIV3fV1+wbwiQ2/8NZQXTcq9J56tg4AAAAA.
    Found session with id k7@associations.fr/xabber-android-3q03wlb1_xmpp_floflo@associations.fr with status ENCRYPTED for user floflo@associations.fr
I/com.xabber.android.data.extension.otr.OTRManager@36a3620: transformed incoming message: https://xmpp.ams1.associations.fr:5280/upload/0f66137a1b3ff702759d7d77a2e13677b1072630/wi63pIT4kbgt6o8HRUFXZtr5R0U1I8iu1lZ26UAu/JPEG_20190112_112459.jpg session status: ENCRYPTED`

Sending from floflo@associations.fr
Servers is not world wide accessible (normal firewall rules)
But the file is not encrypted

**Comment by andrewnenakhov** [comment]
OTR encryption isn't supposed to encrypt files. Also, there is no standard in XMPP to encrypt files uploaded with HTTP Upload. Some clients make custom implementations for this, but they are just it: custom implementations, totally not interoperable.

**Comment by panpansh** [comment]
There is something to do on HttpFileUploadManager and OTRManager if OTR is activated, there is no sense to upload a file in PLAIN in my opinion

**Comment by panpansh** [comment]
![otr-http_upload-xabber](https://user-images.githubusercontent.com/790586/51629870-f9c42b00-1f48-11e9-8462-19b6c2bc5b67.jpg)

Let that ticket open please ..

**Comment by andrewnenakhov** [comment]
@panpansh this ticket can't be left open because it's invalid. If you want us to add a feature to send encrypted files, just create a corresponding issue. It would be best if you could find some standard to base this feature upon. Other clients should be able to decrypt files sent with Xabber, right?

**Comment by panpansh** [comment]
working on that using extension .otre
Status : 
encrypt ok
upload encrypted ok
receive encrypted ok
decrypt ok
display from app ok
only work from filePaths (like images)
need to do for Uris
wait more

**Comment by Neustradamus** [comment]
@panpansh: any news?
