### ISSUE TITLE
App Not Installed Error APK

### ISSUE THREAD

**Issue by giampa** [redsolution/xabber-android#862]
I'm having issue trying to install open debug or open release version of xabber.
I'm not doing anything special, just "generate apk" from Android Studio.
I'm using universal apk generated. The message I get is "App not installed". This happens on emulator and on a real device. What this could be possibly related to?
Many thanks in advance.

**Comment by Str4tocaster** [comment]
@giampa If you have any installed versions of Xabber on you device, delete them.

**Comment by panpansh** [comment]
Whats in debug log ?

**Comment by andrewnenakhov** [comment]
> Whats in debug log ?

@panpansh log of debug messages.

**Comment by Str4tocaster** [comment]
@giampa I close this issue. If it is not solved, open issue again.

**Comment by JanisSharma** [comment]
Already solved At [here](icetutor.com/question/app-not-installed-error-on-android)
