### ISSUE TITLE
Bookmarks support

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#87]
http://xmpp.org/extensions/xep-0048.html

**Comment by Abyss777** [comment]
I'm voting for this enhancement.
The only way to autojoin MUCs on login is implementing XEP-0048.
I'm using ejabberd in corporate environment with precreated MUCs and bookmarks for users depending on his membership in some groups. It would be nice to have ability to autojoin rooms in mobile client.

**Comment by andrewnenakhov** [comment]
Actually this one was implemented a long time ago
