### ISSUE TITLE
Start on boot not working

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#870]
Xabber: 2.6.2 (587)
Android: 9

I just installed Xabber on a new phone and noticed, that after a reboot, Xabber does not start automatically. Settings / "Start on boot" is of course activated.

**Comment by andrewnenakhov** [comment]
Strange, we've specifically tested it on all our available devices in latest update... email us info@xabber.com pls and specify device type, we'll try to think of how to fix it.

**Comment by casperklein** [comment]
Sorry for the noise! It just took some time to start.

(fyi: whatsapp almost instandly started, Xabber took about 2min - but thats no problem for me)

**Comment by andrewnenakhov** [comment]
@casperklein how do you know that whatsapp started almost instantly? Because you received a whatsapp message?

**Comment by casperklein** [comment]
Yes. I sent me a Whatsapp and Jabber message while my phone was off. Then I started the phone. After unlocking, the WA message almost instantly arrived. Xabber took 2 minutes to start/login (I also verified it by looking at the prosody logs). There is no battery optimization or anything like that for both, WA & Xabber.

**Comment by andrewnenakhov** [comment]
@casperklein most likely WhatsApp simply received a push notification. Xabber will have push notifications support soon, but it'll only work on servers with XEP-0357.
