### ISSUE TITLE
Crash in Chat screen on android 4

### ISSUE THREAD

**Issue by Str4tocaster** [redsolution/xabber-android#871]
Crashes when trying to check messages since I upgraded to Xabber 2.6.2 (588). Previously, with Xabber 2.6.x (probably 569) everything was fine. Of course, since this is a very old mobile device, Samsung did not push any updates for me. The device is stuck at Android 4.2.2.

I already uninstalled and reinstalled this version (Xabber 2.6.2 (588)) and tried Xabber Beta which appears to be the same version number.

**Comment by Str4tocaster** [comment]
Fixed in 450c06c1f158a4e1d272acc2a38996c74053716c. Version with this fix will release as 489. Please check it and reply.

**Comment by gonter** [comment]
Thanks for the quick response and fix.

"will release as 489" ... where would I find this?

**Comment by andrewnenakhov** [comment]
@gonter wait for next update. First on Xabber Beta on Google play.

**Comment by gonter** [comment]
I installed the new version (Xabber Beta 2.6.2(591)) on my mobile phone and it is workin again, thanks!
