### ISSUE TITLE
XEP-0363 (HTTP File Upload) support of server not detected

### ISSUE THREAD

**Issue by TaylanUB** [redsolution/xabber-android#872]
Xabber doesn't seem to detect the XEP-0363 (HTTP File Upload) support of the XMPP server of feministwiki.org. It's marked as not supported under "Server info" and trying to send a file gives an error message saying the server doesn't support it.

Gajim on Windows successfully detects the support and is able to send files to other users just fine, so the server definitely supports it.

What might be causing Xabber to think it's not supported?

**Comment by Str4tocaster** [comment]
@TaylanUB Hello. Please specify version of Xabber and android that you use?

**Comment by TaylanUB** [comment]
Android: 8.1.0 (LineageOS 15.1)
Device: Nexus 6p (angler)
Xabber: 2.6.2 (588)

I actually still had the Valentine's Day edition,
but updating to 588 didn't help.

By the way the app is now constantly crashing. :-(

Valeriy Miller <notifications@github.com> schrieb am Mi., 13. März 2019,
07:24:

**Comment by Str4tocaster** [comment]
@TaylanUB Are you use Deutsch locale? In this locale was a issue with translation, that also fixed. Please, wait for next update.

**Comment by TaylanUB** [comment]
Indeed, my device was set to German.
Thanks for the info, works fine in English. :-)

Would it help if I created you an account on the
XMPP server, by the way? I can send you the
password privately, since it's an invite-only server.

Valeriy Miller <notifications@github.com> schrieb am Mi., 13. März 2019,
16:38:

**Comment by andrewnenakhov** [comment]
@TaylanUB it would definitely help. Email credentials to info@xabber.com, we'll check it out.

**Comment by TaylanUB** [comment]
All right, I sent an email to that address with a login.
Thanks for looking into it.

**Comment by oxoWrk** [comment]
This is your server disco info and it does't have http-upload (used Gajim)

```
<iq from='f***ki.org' to='********/gajim.D8O9NYQY' id='02b3f9ce-108d-422b-bda4-7720de90da12' type='result'>
<query xmlns='http://jabber.org/protocol/disco#info'>
<identity category='pubsub' type='pep'/>
<identity category='server' type='im' name='ejabberd'/>
<x xmlns='jabber:x:data' type='result'>
<field var='FORM_TYPE' type='hidden'>
<value>http://jabber.org/network/serverinfo</value>
</field>
</x>
<feature var='http://jabber.org/protocol/commands'/>
<feature var='http://jabber.org/protocol/disco#info'/>
<feature var='http://jabber.org/protocol/disco#items'/>
<feature var='http://jabber.org/protocol/pubsub'/>
<feature var='http://jabber.org/protocol/pubsub#access-authorize'/>
<feature var='http://jabber.org/protocol/pubsub#access-open'/>
<feature var='http://jabber.org/protocol/pubsub#access-presence'/>
<feature var='http://jabber.org/protocol/pubsub#access-whitelist'/>
<feature var='http://jabber.org/protocol/pubsub#auto-create'/>
<feature var='http://jabber.org/protocol/pubsub#auto-subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#collections'/>
<feature var='http://jabber.org/protocol/pubsub#config-node'/>
<feature var='http://jabber.org/protocol/pubsub#create-and-configure'/>
<feature var='http://jabber.org/protocol/pubsub#create-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#delete-items'/>
<feature var='http://jabber.org/protocol/pubsub#delete-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#filtered-notifications'/>
<feature var='http://jabber.org/protocol/pubsub#get-pending'/>
<feature var='http://jabber.org/protocol/pubsub#instant-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#item-ids'/>
<feature var='http://jabber.org/protocol/pubsub#last-published'/>
<feature var='http://jabber.org/protocol/pubsub#manage-subscriptions'/>
<feature var='http://jabber.org/protocol/pubsub#member-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#modify-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#outcast-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#persistent-items'/>
<feature var='http://jabber.org/protocol/pubsub#presence-notifications'/>
<feature var='http://jabber.org/protocol/pubsub#presence-subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#publish'/>
<feature var='http://jabber.org/protocol/pubsub#publish-only-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#publisher-affiliation'/>
<feature var='http://jabber.org/protocol/pubsub#purge-nodes'/>
<feature var='http://jabber.org/protocol/pubsub#retract-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-affiliations'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-default'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-items'/>
<feature var='http://jabber.org/protocol/pubsub#retrieve-subscriptions'/>
<feature var='http://jabber.org/protocol/pubsub#shim'/>
<feature var='http://jabber.org/protocol/pubsub#subscribe'/>
<feature var='http://jabber.org/protocol/pubsub#subscription-notifications'/>
<feature var='http://jabber.org/protocol/stats'/>
<feature var='iq'/>
<feature var='jabber:iq:last'/>
<feature var='jabber:iq:privacy'/>
<feature var='jabber:iq:version'/>
<feature var='msgoffline'/>
<feature var='presence'/>
<feature var='urn:xmpp:blocking'/>
<feature var='urn:xmpp:carbons:1'/>
<feature var='urn:xmpp:carbons:2'/>
<feature var='urn:xmpp:mam:0'/>
<feature var='urn:xmpp:mam:1'/>
<feature var='urn:xmpp:mam:tmp'/>
<feature var='urn:xmpp:ping'/>
<feature var='urn:xmpp:time'/>
<feature var='vcard-temp'/>
</query>
</iq>
```

and further

```
<iq from='echo.f*****ki.org' to='*******/gajim.D8O9NYQY' type='error' xml:lang='ru' id='2fa98052-c856-4e3d-84c5-28c9a4884324'>
<query xmlns='http://jabber.org/protocol/disco#info'/>
<error code='404' type='cancel'>
<remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>

<iq from='groups.f*****ki.org' to='********/gajim.D8O9NYQY' type='error' xml:lang='ru' id='2dd60810-3bd5-402f-a3ac-79ecfe6c9408'>
<query xmlns='http://jabber.org/protocol/disco#info'/>
<error code='404' type='cancel'>
<remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>

<iq from='pubsub.f*****ki.org' to='*******/gajim.D8O9NYQY' type='error' xml:lang='ru' id='489af970-30b6-4bcb-845b-3bbc0bfea125'>
<query xmlns='http://jabber.org/protocol/disco#info'/>
<error code='404' type='cancel'>
<remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>

<iq from='upload.f*****ki.org' to='*******/gajim.D8O9NYQY' type='error' xml:lang='ru' id='2db0cb25-4a1d-4eaa-93b9-bf5e56378009'>
<query xmlns='http://jabber.org/protocol/disco#info'/>
<error code='404' type='cancel'>
<remote-server-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>
```

Check server config

**Comment by FeministWiki** [comment]
Hi, server admin here.

I don't know how exactly you've produced that XML output (I know about the XML console of Gajim but not how you made it generate that output) but Gajim certainly indicates in its GUI that HTTP File Upload is supported (with a green checkmark in the window "Accounts -> Advanced -> Server Information"). See following screenshot for clarification.

![screenshot](https://user-images.githubusercontent.com/43093636/54807495-78f68680-4c8e-11e9-89d2-44901d2c0314.png)

Uploading/sending files also simply works when using Gajim, so the server really does support it. I've tested this with Gajim 1.1.2 / python-nbxmpp 0.6.9 on Windows 10.

I also messed around with the config to make sure that the domain names advertised by the server (such as "upload.feministwiki.org") really exist in DNS (as CNAME entries pointing to "xmpp.feministwiki.org"), and that the SSL certificate of feministwiki.org is valid for those subdomains. I'm not sure if this is even necessary, but in any case it didn't solve the issue either.

Do you have any further ideas where the problem could be?

**Comment by FeministWiki** [comment]
I've just checked what the Gajim XML console prints out when I newly connect to the server, and found the following snippet:

```xml
<iq xmlns="jabber:client" from="xmpp-upload.feministwiki.org" to="testuser@feministwiki.org/gajim.2QJOJZQ9" id="6af1df4b-8068-4d6c-803a-91e5b73c219a" type="result">
<query xmlns="http://jabber.org/protocol/disco#info">
<identity category="store" type="file" name="HTTP File Upload" />
<feature var="urn:xmpp:http:upload" />
<feature var="eu:siacs:conversations:http:upload" />
<x xmlns="jabber:x:data" type="result">
<field var="FORM_TYPE" type="hidden">
<value>http://jabber.org/network/serverinfo</value>
</field>
</x>
</query>
</iq>
```

So the server is definitely advertising support for `urn:xmpp:http:upload`. That also seems to be the token Xabber is looking for in the following place in the code:

https://github.com/redsolution/xabber-android/blob/7db2ed766d24c4d4ad49455b565986b33f0faccc/xabber/src/main/java/com/xabber/android/data/extension/httpfileupload/HttpFileUploadManager.java#L142-L162

The `NAMESPACE` constant being defined here:

https://github.com/redsolution/xabber-android/blob/7db2ed766d24c4d4ad49455b565986b33f0faccc/xabber/src/main/java/com/xabber/xmpp/httpfileupload/Request.java#L11

I don't have time to dig into the code further right now to find out what exactly isn't working. I might be able to debug it tomorrow. I even happen to have Android Studio installed... Let me know if you find something on the meanwhile.

**Comment by Str4tocaster** [comment]
@FeministWiki I checked id. This is a bug in the application. Will be fixed in next update.

**Comment by FeministWiki** [comment]
Thanks! Much appreciated.

**Comment by Str4tocaster** [comment]
@FeministWiki This issue was fixed in new version of Xabber Beta (601). Please check it and comment here.

**Comment by TaylanUB** [comment]
Sorry about the delay. I now installed Xabber Beta and tried to send an image. The server's support is detected and I was able to send the image. :-)
