### ISSUE TITLE
OTR session start while counterpart is offline

### ISSUE THREAD

**Issue by thedolphin** [redsolution/xabber-android#873]
OTR session start must be attempted regardless of state of counterpart.
Offline state may be due to presence problems.

**Comment by andrewnenakhov** [comment]
That's not how OTR is supposed to work. We are plan to move away from OTR anyway so no point doing this, sorry.

**Comment by thedolphin** [comment]
May be I wasn't clear enough.
The problem is that all buddies is online, but one is invisible. Then Xabber refuses to start OTR, while, for example, mcabber will start OTR without problems.

**Comment by andrewnenakhov** [comment]
I understand your request. I'm sorry, that is not something I can spend our resources on. Also, I think your problem has an easy workaround: xmpp clients have the ability to advertise their online presence. Your buddy should make himself visible, like the rest of you.
