### ISSUE TITLE
Weird sorting of chat participants

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#877]
I join a room on a server and swipe to see participants. They are not sorted by name or status, seems random. But all moderators are showing at the bottom. Is there a setting to set sorting order?

**Comment by wrooot** [comment]
It seems it first shows users with names starting with capital letters. https://photos.app.goo.gl/G8eQC17ZntmqGJmq7

**Comment by bleedingcrow** [comment]
Sorted by most recently active?

**Comment by wrooot** [comment]
No, it is in alphabetical order, but users with names starting with a capital letter are at the top for some reason. Sorting is case sensitive.

**Comment by wrooot** [comment]
Also noticed that all moderators are at the bottom. Maybe more logical to show them at the top. Although i would prefer all users just to be sorted alphabetically.

**Comment by andrewnenakhov** [comment]
We are going to remove MUC support this year from Xabber for Android. Xabber Server and other versions of Xabber already have support for a far superior group chat protocol.
