### ISSUE TITLE
Additional share feature (request)

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#879]
When sharing e.g. a URL in chrome browser, you can choose Xabber and then a contact to share with.
It would be nice, to have also the ability to share the URL directly with a Xabber contact.
Whatsapp provides something like that. When sharing a URL you can choose "Whatsapp" or directly a contact with which you recently had a chat with.

**Comment by andrewnenakhov** [comment]
this Android feature is called 'Direct share', and it is indeed a good idea to add it.
