### ISSUE TITLE
Can't get rid of a chat

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#883]
I have a few recent chas showing at the top when i run Xabber. I try to archive them, but every time i run xabber again, they show up. Only removing room bookmark or contact makes it disappear for good. Xabber is not allowed to run in background. Maybe it can't save state of chats because of that.

**Comment by Str4tocaster** [comment]
Chat status may not be saved if you close the application immediately after you archive the chat.
We know about this problem and will try to fix it in the future.

**Comment by wrooot** [comment]
I have tried waiting for 10 seconds and then manually exit Xabber via settings. Still the same. Ok, will wait for a fix.

**Comment by andrewnenakhov** [comment]
@wrooot but you know you that Xabber *should* be allowed to run in the background to work properly, do you?

**Comment by wrooot** [comment]
I need to clarify, that I haven't added it to restricted apps list in Android settings. I only disable tray icon, which in turn makes it not stay in background. I only need Xabber sporadically and don't need it to stay all the time. Also don't like icon showing in notifications bar all the time 😀 so i understand the drawbacks and accept them. I have tried to enable tray icon again and test by manually exiting. Chat still shows up. I guess this issue is not related to unloading from memory.

**Comment by andrewnenakhov** [comment]
@wrooot btw, these chats aren't conferences, are they?

**Comment by wrooot** [comment]
First one was conference. So i have removed the bookmark and it is gone now. I also have one one-on-one chat showing. I don't want to remove this contact from my roster to hide the chat. Not a major issue, can live with that 😀

**Comment by Str4tocaster** [comment]
> I guess this issue is not related to unloading from memory.
@wrooot It is directly related. If you close app before it saves chat status to db, it wont be saved. You should not exit app manually.

**Comment by wrooot** [comment]
If i try to archive chats (both conference and one on one) and wait in the app for a minute or so and then go to desktop, then launch Xabber again, the issue is still present. So, maybe it is related to unloading from memory, but Xabber takes long time before it saves the state to db even when the app is actively used.

**Comment by Str4tocaster** [comment]
@wrooot Thanks for your observations, this will help us.

**Comment by wrooot** [comment]
In the latest version i was able to remove saved chat and now it doesn't appear again

**Comment by wrooot** [comment]
As a side effect now I can't disable xabber's icon in notifications bar.. 😊

**Comment by wrooot** [comment]
This looks confusing. Keep bulbs look similar to Xabber bulb.. :) 
![Screenshot_20190726-123655](https://user-images.githubusercontent.com/7195609/61994659-0eaf8180-b086-11e9-9115-bed1d3359f30.png)

**Comment by andrewnenakhov** [comment]
Permanent icon is necessary to keep xabber working in background. Sorry about that but it's how Android works these days.

**Comment by wrooot** [comment]
Actually we have discussed this a few months ago (above). I was ok with the option to remove that icon and not having it in the background all the time. Now there is no such option anymore. Anyway, the issue with stuck chats is fixed, so i have closed this issue.

**Comment by andrewnenakhov** [comment]
@wrooot we are planning to add support to push notifications, so users of servers that support XEP-0357  will not have this persistent icon at all.
