### ISSUE TITLE
Feature request: options to reduce iddle traffic

### ISSUE THREAD

**Issue by sergey-feo** [redsolution/xabber-android#884]
Hello!
Excuse me for my poor English please :-)

When I do nothing, Xabber creates traffic about several kylobytes per hour or more.
Feature request: add some options that can significantly reduce this iddle traffic (just guesses: rare server pings, do not transmit and receive presence states, etc).

With best regards, Sergey

**Comment by andrewnenakhov** [comment]
Server pings are controlled by, you guess it, server. IT's not supposed to be configured on clientside. 

We are working on push notifications, however, that'll allow app to remain dormant until some message is received by server that should be delivered to client.

**Comment by sergey-feo** [comment]
Thank you very much for explanation!

**Comment by ToEatFreshBabies** [comment]
> working on push notifications

I hope you are not abandoning those who have sanitized android (removed google cruft, gapps, services).

@andrewnenakhov
