### ISSUE TITLE
Two messages shown as sending on Android 10

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#889]
Just updated Pixel XL 1st gen and when i send a message in MUC it sends it and then shows a second copy of it with a clock icon (pending?). Which is not sent and i can delete it from history. Can be a bug in server software, but was working fine before the update.

**Comment by andrewnenakhov** [comment]
This is a known error, happens because MUC is an ugly protocol. We don't plan to fix it, because we're preparing to support a far superior group chat protocol.
