### ISSUE TITLE
Non-free contents in repository

### ISSUE THREAD

**Issue by Natureshadow** [redsolution/xabber-android#9]
The repository (and thus, Xabber) contains non-free content. From the LICENSE file:

Following files are distributed under "Creative Commons Attribution Non-Commercial No Derivatives":
res/drawable*/ic_connect.png
res/drawable*/ic_disconnect.png
res/drawable*/ic_information.png
res/drawable*/ic_launcher.png
res/drawable*/ic_stat_*.png
res/drawable*/title_logo.9.png

The "No Derivatives" part essentially makes the content non-free (Non-Commercial also does, but not in the sense of the GPL). Please re-license these graphics as at least CC-BY-NC-SA, or better, CC-BY-SA.

**Comment by andrewnenakhov** [comment]
that should be fixed by now, @grigoryfedorov ?
