### ISSUE TITLE
BaseLoginActivity class not found

### ISSUE THREAD

**Issue by RajanVindaloo** [redsolution/xabber-android#902]
As XabberAccountActivity extends BaseLoginActivity, 
But there is no sign of BaseLoginActivity in any of the branches. 
Neither in "master" nor in "v2.6.6" nor in "v2.6.7".

So, it's quite difficult to build source code.

Help me with this.
Thanks

**Comment by popovvitaly** [comment]
Describe all steps which are lead to this problem. Because I couldn't repeat it. Try to clear all files and re clone anew.

**Comment by RajanVindaloo** [comment]
Thank you for your reply. It's happy to hear from you.

I am attaching a screenshot.

![xabber issue](https://user-images.githubusercontent.com/46807770/66892934-89939300-f00a-11e9-9639-658a4f96b9a7.png)



The above screenshot contains my problem. "BaseLoginActivity" should be here. 

In addition to that, I've followed steps that are given in the README file.
I am looking for "BaseLoginActivity" into the source that you have provided. Please guide me if I am missing something anywhere. 

Thank you

**Comment by popovvitaly** [comment]
This class located at [open dir](https://github.com/redsolution/xabber-android/tree/master/xabber/src/open/java/com/xabber/android/ui/activity), not main. Did you make any changes in code after cloning (especially at build part)?

**Comment by RajanVindaloo** [comment]
Okay, let me check for the link. 
No, I did not make any changes in code.
