### ISSUE TITLE
OAuth 2.0 authorization support for GTalk

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#91]

**Comment by andrewnenakhov** [comment]
Issue no longer relevant, Gtalk is dead.

**Comment by skudi** [comment]
Only the application GoogleTalk is deprecated. Google servers still supports XMPP and they will be, so support for OAuth2 is still needed.

http://www.theregister.co.uk/2015/02/18/gtalk_is_dead_long_live_gtalk/
"Now Mayur Kamat, product manager for Google Voice and Hangouts, has said the Google Talk servers will continue to support XMPP, allowing all XMPP chat clients to continue nattering away on Google Talk."
