### ISSUE TITLE
vCard title gets cut when folded

### ISSUE THREAD

**Issue by bodqhrohro** [redsolution/xabber-android#910]
https://0x0.st/zYvB.mp4

Which is more interesting, it gets centered at some moment, but other vCards still are cut when displayed and folded first time.

**Comment by andrewnenakhov** [comment]
we're changing vCard look in a radical way, it'll look like this:

<a href="url"><img src="https://xmpp.redsolution.com/upload/4bddf4f264f5c6577f16551f16a0abdf3f7ff84d/VYGRkzQj/Screenshot_20191031-032825.png" align="left" width="360" ></a>

I'll be closing this issue for now. If you have questions, feel free to ask
