### ISSUE TITLE
xabber unable to connect

### ISSUE THREAD

**Issue by mgrunwald** [redsolution/xabber-android#912]
There is an exception when I try to connect:

```java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.jivesoftware.smack.packet.Mechanisms.getMechanisms()' on a null object reference
	at com.xabber.xmpp.smack.XMPPTCPConnection.loginInternal(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(Unknown Source)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread.connectAndLogin(Unknown Source)
	at com.xabber.android.data.connection.ConnectionThread$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
```

xabber 2.6.6.644
android 7.1.2 / lineage os 14.1

Its not the servers fault since Conversations works on the same device

**Comment by andrewnenakhov** [comment]
> Its not the servers fault since Conversations works on the same device

Lol. 

Anyway, if Xabber does not connect to a server, this means that the server is likely improperly configured. Most probable guess is that you run an OpenFire server with a broken certificate, but since we have no real data it's just a guess. Enable debug logs and attach them here, or email them to info@xabber.com, then we'll probably be able to tell you what's exactly wrong.

**Comment by mgrunwald** [comment]
Ok, you were half correct: The server is [ejabber](https://www.ejabberd.im), the certificate has a problem: it is for *.the-grue.de, not for the-grue.de. But that never was a problem, xabber just asked if I trust it an that was it.

[Xabber_2.6.6.644_2019-11-10_17-04-23.txt](https://github.com/redsolution/xabber-android/files/3828677/Xabber_2.6.6.644_2019-11-10_17-04-23.txt)

**Comment by mgrunwald** [comment]
The certificate is fixed now - xabber still crashes :(

Still "lol" ?

**Comment by andrewnenakhov** [comment]
@mgrunwald we don't like your attitude so we are not really into fixing your issue dropping everything else.

**Comment by mgrunwald** [comment]
Sorry, what? You "Lol"ed at me!
What's wrong with my first post? I mean it honest, I want to learn what I did wrong. From my point of view, I noticed you of a segfault, gave some detailes, followed your instructions and now you "don't like my attitude"?

And nobody even even gave a hint that you should "drop everything else". Ok, I was annoyed by your "lol". Sorry for that, I'll never mention that again.

**Comment by andrewnenakhov** [comment]
1. Your server is very likely to be set up incorrectly. The fact that some other client is more tolerant to some errors does not mean that everything is OK.
2. It is likely you encountered a simple error message (yeah, it's not really pretty, i admit), not a segfault error. We don't see crashes in crashlytics either. 
3. If you really want to solve this issue, best course is to give us a test account. Send requisites to info@xabber.com

**Comment by mgrunwald** [comment]
Thanks for offering 3. I just send you the credentials.

**Comment by vitaliipopov23** [comment]
Fixed at latest update on Google Play.

**Comment by mgrunwald** [comment]
@popovvitaly : I thank you really very much for fixing the error. Honestly!

@andrewnenakhov ... in spite of not liking my attitude, in spite of not having an error in the client at all, in spite of (not) having a misconfigured server. Now you have a reason to not like my attitude, I don't like yours, neither.

**Comment by andrewnenakhov** [comment]
@mgrunwald yet, I am the one who ended up paying for your issue to be resolved. :-/

**Comment by mgrunwald** [comment]
Maybe, when I report the next bug, we could start from scratch. Without attitudes on both sides.

**Comment by andrewnenakhov** [comment]
OK)
