### ISSUE TITLE
http_upload: NullPointerException

### ISSUE THREAD

**Issue by casperklein** [redsolution/xabber-android#915]
Android: 10
Device: Samsung S10
Xabber Version: 2.6.6.644
(But also tested with 2.6.6.645 after grabbing the log below; when recognized there was an update on the play store)

"http_upload" does not work anymore for me. When trying to send an image for example, I get
"Could not upload any file". If I click the error description in the chat, I see:

```myimage.jpg: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference```

Debug log:
[Xabber 2.6.6.644 2019-12-08 12-51-32 log file.txt](https://github.com/redsolution/xabber-android/files/3936194/Xabber.2.6.6.644.2019-12-08.12-51-32.log.file.txt)

**Comment by casperklein** [comment]
I tested further with other files, file types and locations. I also got this error sometimes:

```myimage2.png: java.io.FileNotFoundException: /storage/emulated/0/some-app-folder/myimage2.png: open failed: EACCES (Permission denied)```

I checked the Android permissions for Xabber and all are granted.

PS: I've added Device/Android Info to my initial post.

**Comment by vitaliipopov23** [comment]
We have a fix for this problem which appeared at 10 Android, but we doesn't tested it enough, especially at Samsung devices. You can write us to info@xabber.com and we send special version for you, cause this fix will not be soon in Google Play.
