### ISSUE TITLE
Remove faggot and lesbian smiles

### ISSUE THREAD

**Issue by evadogstar** [redsolution/xabber-android#916]
Hello,

How to remove faggot and lesbian smiles from my messenger? Why you force me to see this immoral smiles every day and advertise this **** for all xabber users? Also I did not know that they are here and install xabber to my grandmother phone to chat with she. And what I must say her if she will find this immoral advertising of unconventional relationships?

If some faggot want to use this then give him plugin with this. Why you force all to see this?

Thanks

**Comment by julijane** [comment]
Hello,

How to remove moronic people from our world? Why you force us to see these hateful people every day and advertise this hate to all world users? Unfortunately I did very well that they are here and had not even any influence on my grandmother being born. And what I must say her if she will find this moronic advertising of hateful behavior?

If some lowlife want to see this then give him your hate with this. Why you force us all to see this?

No thanks

**Comment by l29ah** [comment]
Just patch it, it's open source!

**Comment by zinid** [comment]
SJW brigade is on the way. Expect some downvoting.

**Comment by xmarxthespot** [comment]
> immoral smiles

The preferable term is:  **moralphobic**

[moralphobia:  irrational fear of Natural Law resulting in fear based actions like hate and violence]

**Comment by andrewnenakhov** [comment]
Hm. I expected that reporting & blocking user would remove their content as well. Apparently, no.

**Comment by greatredheron** [comment]
Hey dude that's really not cool. Being homophobic is not okay. It's open source and you can change things how you would like.

**Comment by termermc** [comment]
this is hilarious

**Comment by lex-github** [comment]
based
poor grandmas not only forced to wear triple mask but also triple glasses to avoid seeing haram smiles

**Comment by alonsobustamante98** [comment]
why the drama? this is common sense
