### ISSUE TITLE
File Upload working for just 2-3 users, not working for others. 

### ISSUE THREAD

**Issue by shubham2110** [redsolution/xabber-android#917]
There is this strange issue, File upload is working for two user IDs and it is not working for any other user. 

Other xmpp clients like Conversations, Pidgin, Gajim are already supporting file upload for same accounts. 

 I am using Ejabberd server with mod_http_upload plugin. 

When try to send an attachment,  I am getting error: "Error Sending File, server does not seem to support file transfer...". 

I also followed a similar issue, issue was closed as bug was resolved. 

When I login to xabber,  sometimes it allows to send file,  sometimes it is giving warning just after I click on attachment button in a chat.

**Comment by vitaliipopov23** [comment]
@shubham2110  Describe problem more clearly (steps to reproduce, log files, androids version, server info, etc).
