### ISSUE TITLE
Conferences do not reconnect.

### ISSUE THREAD

**Issue by VA2XJM** [redsolution/xabber-android#927]
Xabber Version: 2.6.6.645

Previous version was working flawlessly. In actual version, conferences do not reconnect when account is reconnecting to server.

So when the phone switch from LTE to Wi-Fi, Wi-Fi to LTE or just get back from no network to any network, the user account re-auth with the server but conferences stay "offline". I have to manually leave the conference and then join again to be able to receive messages again and display the green dot.

**Comment by andrewnenakhov** [comment]
We have already removed support for conferences (XEP-0045) from main branch of Xabber, once the updates make it to the main version, conferences would be replaced by our developed superior (by far!) protocol for group chat. So it's a 'won't fix'. If that functionality is critical for you, then you'll have to use a different client. Sorry about that.
