### ISSUE TITLE
Conform media references to XEP-0385

### ISSUE THREAD

**Issue by singpolyma** [redsolution/xabber-android#934]
Xabber seems to send payload like this:

```
<reference xmlns="urn:xmpp:reference:0" type="media" end="74" begin="0">
  <media>
    <file>
      <media-type>image/jpeg</media-type>
      <name>blah.jpg</name>
      <height>2448</height>
      <width>3264</width>
      <size>3151915</size></file>
      <uri>https://...</uri>
    </media>
</reference>
```

But XEP-0385 shows payloads that look like this:

```
  <reference xmlns='urn:xmpp:reference:0' type='data' end='74' begin='0'>
    <media-sharing xmlns='urn:xmpp:sims:1'>
      <file xmlns='urn:xmpp:jingle:apps:file-transfer:5'>
        <media-type>image/jpeg</media-type>
        <name>summit.jpg</name>
        <size>3151915</size>
        <hash xmlns='urn:xmpp:hashes:2' algo='sha3-256'>2XarmwTlNxDAMkvymloX3S5+VbylNrJt/l5QyPa+YoU=</hash>
        <hash xmlns='urn:xmpp:hashes:2' algo='id-blake2b256'>2AfMGH8O7UNPTvUVAM9aK13mpCY=</hash>
      </file>
      <sources>
        <reference xmlns='urn:xmpp:reference:0' type='data' uri='https://...' />
      </sources>
    </media-sharing>
  </reference>
```

**Comment by andrewnenakhov** [comment]
XEP-0385 is one of many unfortunate XEPs that do everything wrong. 

0385 ignores all prior similar formats that existed before, neglects the needs of client app developers. Adoption of such XEPs results in an unbearable mishmash of standards that are ignoring each other's existence. So, naturally, we decided to start from a clean slate, took XEP-372 references and started extending it the way we need. 

It will result in a cohesive set of protocol extensions that allow media sharing, text formatting, mentions, location sharing, replies/forwarded messages, hashtags, etc. 

So with respect, but we decline to conform to 0385.
